# Complete Marathi (mr) catalog. Run from frontend/: python scripts/tr-mr.py
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emit_locale import emit

T = {
"common": {
"appName": "CropPilot",
"loading": "लोड होत आहे…",
"retry": "पुन्हा प्रयत्न करा",
"cancel": "रद्द करा",
"close": "बंद करा",
"save": "जतन करा",
"search": "शोधा",
"noData": "माहिती उपलब्ध नाही.",
"errorGeneric": "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.",
"prevSlide": "मागील स्लाइड",
"nextSlide": "पुढील स्लाइड",
"menu": "मोबाइल मेनू टॉगल करा",
"language": "भाषा",
"selectLanguage": "भाषा निवडा",
"commandPalette": "कमांड पॅलेट",
},
"navigation": {
"dashboard": "डॅशबोर्ड",
"markets": "बाजार",
"weather": "हवामान",
"disease": "रोग ओळख",
"schemes": "योजना",
"analytics": "विश्लेषण",
"maps": "नकाशे",
"assistant": "AI सहाय्यक",
},
"auth": {
"signIn": "साइन इन करा",
"signOut": "साइन आउट करा",
"welcomeBack": "परत स्वागत आहे",
"signInSubtitle": "तुमच्या CropPilot खात्यात साइन इन करा",
"email": "ईमेल",
"password": "पासवर्ड",
"enterPassword": "तुमचा पासवर्ड टाका",
"rememberMe": "माझी आठवण ठेवा",
"signingIn": "साइन इन होत आहे…",
"signInBtn": "साइन इन",
"noAccount": "खाते नाही?",
"registerLink": "नोंदणी करा",
"emailRequired": "ईमेल आवश्यक आहे",
"emailInvalid": "अवैध ईमेल पत्ता",
"passwordRequired": "पासवर्ड आवश्यक आहे",
"passwordMin": "पासवर्ड किमान 6 अक्षरी असावा",
"invalidCredentials": "अवैध माहिती. कृपया पुन्हा प्रयत्न करा.",
"createAccount": "खाते तयार करा",
"registerSubtitle": "CropPilot मध्ये सामील व्हा आणि स्मार्ट शेती सुरू करा",
"fullName": "पूर्ण नाव",
"fullNamePlaceholder": "तुमचे पूर्ण नाव",
"phone": "फोन नंबर",
"selectState": "राज्य निवडा",
"selectDistrict": "जिल्हा निवडा",
"createPassword": "पासवर्ड तयार करा",
"confirmPassword": "पासवर्डची पुष्टी करा",
"confirmPasswordPlaceholder": "तुमच्या पासवर्डची पुष्टी करा",
"registerBtn": "नोंदणी करा",
"registering": "नोंदणी होत आहे…",
"haveAccount": "आधीच खाते आहे?",
"signInLink": "साइन इन करा",
"nameRequired": "नाव आवश्यक आहे",
"phoneInvalid": "अवैध फोन नंबर",
"phoneLong": "फोन नंबर खूप लांब आहे",
"selectStateRequired": "कृपया राज्य निवडा",
"selectDistrictRequired": "कृपया जिल्हा निवडा",
"passwordMismatch": "पासवर्ड जुळत नाहीत",
"showPassword": "पासवर्ड दाखवा",
"hidePassword": "पासवर्ड लपवा",
"nameMin": "पूर्ण नाव किमान 2 अक्षरी असावे",
"phoneMin": "फोन नंबर किमान 10 अंकी असावा",
"confirmRequired": "कृपया तुमच्या पासवर्डची पुष्टी करा",
"acceptTerms": "तुम्ही अटी व शर्ती स्वीकारल्या पाहिजेत",
"registerFailed": "नोंदणी अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
"acceptPrefix": "मी स्वीकारतो",
"termsService": "सेवा अटी",
"termsAnd": "आणि",
"privacyPolicy": "गोपनीयता धोरण",
"creatingAccount": "खाते तयार होत आहे…",
"authLayoutTitle": "CropPilot मध्ये स्वागत आहे",
"authLayoutBody": "आधुनिक शेतीसाठी ओपन-सोर्स व्यासपीठ. डॅशबोर्डसाठी साइन इन करा.",
},
"landing": {
"badge": "मोफत आणि ओपन-सोर्स सॉफ्टवेअर",
"tagline": "स्मार्ट शेतीसाठी ओपन-सोर्स साधने.",
"heroBody": "पीक आरोग्य, रोग ओळख, हवामान माहिती आणि नोंदवलेल्या मंडी बाजारभावांसाठी शेतकरी-केंद्रित व्यासपीठ.",
"openApp": "CropPilot उघडा",
"viewGithub": "GitHub वर पहा",
"featuresTitle": "तुम्ही काय करू शकता",
"featCrop": "पीक आरोग्य",
"featCropBody": "पीक स्थिती आणि संबंधित शेतमाहितीचा मागोवा घ्या.",
"featDisease": "रोग ओळख",
"featDiseaseBody": "समर्थित रोग ओळख प्रक्रियांसाठी पीक प्रतिमांचे विश्लेषण करा.",
"featWeather": "हवामान माहिती",
"featWeatherBody": "शेती निर्णयांसाठी उपयुक्त हवामान माहिती पहा.",
"featMarket": "बाजार माहिती",
"featMarketBody": "AGMARKNET कडून शासकीय खुल्या डेटाद्वारे नोंदवलेले मंडी भाव एक्सप्लोर करा.",
"appTitle": "अ‍ॅप्लिकेशन",
"appBody": "शेत आढावा, हवामान, पीक आरोग्य आणि बाजार विभागांसह CropPilot डॅशबोर्ड.",
"appCaption": "नमुना डेटासह चालणारा CropPilot डॅशबोर्ड.",
"appAlt": "नमुना डेटासह शेत आढावा, हवामान, पीक आरोग्य आणि बाजार विभाग दाखवणारा CropPilot डॅशबोर्ड स्क्रीनशॉट",
"marketTitle": "बाजार माहिती",
"marketBody": "राज्य, जिल्हा, बाजार, जिंस, जात, प्रत आणि कलानुसार नवीनतम नोंदवलेले मंडी भाव तपासा, तसेच कल आणि बाजार-तुलना पहा.",
"marketSource": "स्रोत: शासकीय खुल्या डेटाद्वारे AGMARKNET. मूल्ये निरीक्षण तारखांसह नोंदवलेली निरीक्षणे आहेत, चालू बाजारभाव म्हणून कधीही सादर केलेली नाहीत.",
"marketCta": "बाजारभाव एक्सप्लोर करा",
"whyTitle": "शेतकऱ्यांसाठी बनवले. खुलेपणाने बनवले.",
"whyBody": "CropPilot हे मोफत आणि ओपन-सोर्स सॉफ्टवेअर आहे जे शेती साधने आणि माहिती सुलभ करते. हे MIT परवान्यावर चालते आणि विकास GitHub वर पारदर्शकपणे होतो.",
"archTitle": "आर्किटेक्चर",
"archBody": "शेत आणि स्थानिक डेटासाठी PostgreSQL आणि PostGIS, पार्श्वभूमी कामांसाठी Celery वर्कर्स आणि रोग ओळखीसाठी PyTorch व्हिजन मॉडेल्ससह FastAPI सेवेवर आधारित Next.js फ्रंटएंड. सर्व काही Docker Compose सह स्थानिकपणे चालते.",
"ossTitle": "GitHub वर ओपन सोर्स",
"ossBody": "कोड ब्राउझ करा, समस्या नोंदवा आणि सुधारणांमध्ये योगदान द्या. MIT परवानाधारक.",
"footerTag": "ओपन-सोर्स शेती व्यासपीठ.",
"footerDocs": "दस्तऐवजीकरण",
"navFeatures": "वैशिष्ट्ये",
"navArchitecture": "आर्किटेक्चर",
"toggleMenu": "मेनू टॉगल करा",
"footerLabel": "फुटर",
},
"dashboard": {
"welcomeBack": "परत स्वागत आहे, {name}",
"farmer": "शेतकरी",
"selectFarm": "शेत निवडा",
"allFarms": "सर्व शेते",
"wFarmOverview": "शेत आढावा",
"wWeather": "आजचे हवामान",
"wCropHealth": "पीक आरोग्य",
"wDiseaseAlerts": "रोग सूचना",
"wRevenue": "महसूल",
"wExpenses": "खर्च",
"wNetProfit": "निव्वळ नफा",
"wYield": "उत्पादन",
"wMarketTrends": "बाजार कल",
"wSchemes": "योजना शिफारसी",
"wNotifications": "सूचना",
"wQuickActions": "जलद क्रिया",
"vsLastMonth": "मागील महिन्याच्या तुलनेत",
"totalYield": "एकूण उत्पादन",
"perHectare": "प्रति हेक्टर",
"noAlerts": "सक्रिय रोग सूचना नाहीत",
"cropsHealthy": "तुमची पिके निरोगी आहेत",
"noNotifications": "सूचना नाहीत",
"qaScan": "पिके स्कॅन करा",
"qaWeather": "हवामान तपासा",
"qaMarkets": "बाजार पहा",
"qaAssistant": "AI सहाय्यक",
"statFarms": "एकूण शेते",
"statArea": "एकूण क्षेत्र",
"statPlots": "सक्रिय प्लॉट",
"statSeason": "चालू हंगाम",
"notifMarkRead": "सर्व वाचले म्हणून चिन्हांकित करा",
"marginLabel": "मार्जिन:",
},
"weather": {
"title": "हवामान",
"subtitle": "तुमच्या शेतासाठी रिअल-टाइम हवामान डेटा आणि अंदाज",
"searchLocation": "स्थान शोधा…",
"noLocations": "स्थाने आढळली नाहीत",
"hourly": "तासन्तास अंदाज",
"details": "हवामान तपशील",
"rainProbability": "पावसाची शक्यता",
"windSpeed": "वाऱ्याचा वेग",
"humidity": "आर्द्रता",
"uvIndex": "UV निर्देशांक",
"pressure": "दाब",
"visibility": "दृश्यता",
"weekly": "7-दिवसीय अंदाज",
"feelsLike": "{temp}° सारखे वाटते",
"highShort": "कमाल: {temp}°",
"lowShort": "किमान: {temp}°",
},
"disease": {
"title": "रोग ओळख",
"subtitle": "AI-शक्तीच्या रोग निदानासाठी पीक प्रतिमा अपलोड करा किंवा कॅप्चर करा",
"newDetection": "नवीन तपासणी",
"analyzing": "तुमच्या पीक प्रतिमेचे विश्लेषण होत आहे…",
"analyzingBody": "AI रोग नमुने स्कॅन करत आहे",
"readyTitle": "निदानासाठी सज्ज",
"readyBody": "त्वरित AI-शक्तीची रोग ओळख आणि उपचार शिफारसी मिळवण्यासाठी बाधित पिकाचा फोटो अपलोड करा किंवा कॅप्चर करा",
"confidence": "AI विश्वास",
"cameraTitle": "कॅमेरा कॅप्चर",
"cameraBody": "बाधित पिकाचा फोटो घ्या",
"cameraHint": "बाधित पाने किंवा फळे फ्रेममध्ये ठेवा",
"activateCamera": "कॅमेरा सुरू करा",
"capture": "कॅप्चर करा",
"retake": "पुन्हा घ्या",
"uploadTitle": "प्रतिमा अपलोड करा",
"uploadHint": "ड्रॅग आणि ड्रॉप करा किंवा ब्राउझ करा",
"dropHint": "ड्रॅग आणि ड्रॉप करा किंवा अपलोडसाठी क्लिक करा",
"dropFormats": "JPG, PNG, WEBP, 10MB पर्यंत",
"changeImage": "प्रतिमा बदला",
"fileTooBig": "फाइल आकार 10MB पेक्षा कमी असावा.",
"resultTitle": "तपासणी निकाल",
"detectedDisease": "आढळलेला रोग",
"confidenceScore": "विश्वास स्कोअर",
"treatmentAvailable": "उपचार शिफारस उपलब्ध",
"aiAnalysis": "AI-शक्तीचे विश्लेषण",
"symptoms": "लक्षणे",
"recommendedActions": "शिफारस केलेल्या क्रिया",
"preventiveMeasures": "प्रतिबंधात्मक उपाय",
"historyTitle": "तपासणी इतिहास",
"thDate": "तारीख",
"thCrop": "पीक",
"thDisease": "रोग",
"thConfidence": "विश्वास",
"thStatus": "स्थिती",
"sevLow": "कमी",
"sevModerate": "मध्यम",
"sevHigh": "जास्त",
"sevCritical": "गंभीर",
"pastDetections": "{count} मागील तपासण्या",
"searchHistory": "पीक किंवा रोगानुसार शोधा…",
"noDetections": "तपासण्या आढळल्या नाहीत",
"stageCheckingPhoto": "फोटो गुणवत्ता तपासत आहे…",
"stageAnalyzing": "प्रतिमेचे विश्लेषण होत आहे…",
"cropHintLabel": "पीक (पर्यायी - योग्य तज्ञ निवडण्यास मदत करते)",
"cropHintAuto": "स्वयंचलित (सूचना नाही)",
"unknownCrop": "अज्ञात पीक",
"uncertainTitle": "CropPilot समस्येची खात्रीशीर ओळख करू शकले नाही",
"uncertainBody": "निदानासाठी प्रतिमा पुरावा पुरेसा नव्हता. खालील पर्याय अंदाज आहेत, निदान नाही.",
"possibleCauses": "संभाव्य पर्याय",
"analyzeAnotherHint": "चांगल्या उजेडात एका बाधित पानाचा जवळून फोटो घेऊन पुन्हा प्रयत्न करा.",
"supportedCrops": "सत्यापित तज्ञ असलेली पिके",
"capabilitiesOffline": "निदान सेवा सूचीशी संपर्क होऊ शकला नाही. तरीही अपलोड करून पाहू शकता.",
"bandHigh": "जास्त",
"bandMedium": "मध्यम",
"bandLow": "कमी",
"bandUnverified": "असत्यापित स्कोअर",
"bandUnknown": "अज्ञात",
"statusDiagnosed": "संभाव्य निदान",
"statusProbable": "संभाव्य - पडताळणी आवश्यक",
"statusUncertain": "अनिश्चित",
"statusInsufficientImage": "फोटो निरुपयोगी",
"statusUnsupportedCrop": "पीक अद्याप समर्थित नाही",
"statusError": "विश्लेषण अयशस्वी",
"uncalibratedScore": "मॉडेल स्कोअर (अकॅलिब्रेटेड)",
"uncalibratedScoreHint": "कच्चे मॉडेल आउटपुट, कॅलिब्रेटेड संभाव्यता नाही.",
"uploadedPhoto": "अपलोड केलेला फोटो",
"evidenceTitle": "विश्लेषण तपशील",
"routingMode": "रूटिंग",
"modelsUsed": "वापरलेली मॉडेल्स",
"fieldValidation": "शेत पडताळणी",
"imageQuality": "प्रतिमा गुणवत्ता",
"latencyLabel": "विश्लेषण वेळ",
"researchBadge": "संशोधन मॉडेल",
"notVerified": "सत्यापित नाही",
"guidanceFor": "मार्गदर्शन:",
"guidanceSource": "स्रोत",
"similarConditions": "समान स्थिती",
"noGuidance": "CropPilot कडे या निदानासाठी अद्याप सत्यापित मार्गदर्शन नाही.",
"imageNotRetained": "केवळ सत्र इतिहास - प्रतिमा जतन केल्या जात नाहीत.",
"errNetwork": "नेटवर्क त्रुटी. तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
"errTooLarge": "प्रतिमा खूप मोठी आहे. 10 MB पेक्षा लहान फोटो वापरा.",
"errPoorQuality": "फोटो गुणवत्ता विश्लेषणासाठी खूप खराब आहे. एका बाधित पानाचा जवळून फोटो घ्या.",
"errUnsupportedCrop": "CropPilot कडे त्या पिकासाठी अद्याप सत्यापित तज्ञ नाही.",
"errInvalid": "ती फाइल प्रतिमा म्हणून वाचता आली नाही. JPG किंवा PNG फोटो वापरून पहा.",
"errNoModel": "सध्या सत्यापित निदान मॉडेल उपलब्ध नाही. नंतर पुन्हा प्रयत्न करा.",
"errServer": "विश्लेषण अयशस्वी. स्पष्ट फोटोसह पुन्हा प्रयत्न करा.",
"analysisIncomplete": "विश्लेषण अपूर्ण",
"noVerifiedDiagnosis": "सत्यापित निदान नाही",
"analysisStatusLabel": "विश्लेषण स्थिती",
"cropLabel": "पीक",
"cropNotIdentified": "ओळखले नाही",
"cropUnsupported": "असमर्थित",
"cropSourceUser": "तुम्ही निवडले (रूटिंग सूचना, मॉडेल पुरावा नाही)",
"cropSourceUnknown": "या फोटोवरून ओळखले नाही",
"selectCropPrompt": "तुम्हाला पीक माहीत आहे? निवडल्याने CropPilot ला योग्य तज्ञ निवडण्यास मदत होते.",
"analyzeAgain": "पुन्हा विश्लेषण करा",
"retryAnalysis": "पुन्हा प्रयत्न करा",
"coverageBadge": "मॉडेल कव्हरेज अनुपलब्ध",
"serviceBadge": "सेवा अनुपलब्ध",
"temporaryAnalysisFailure": "विश्लेषण तात्पुरते अयशस्वी",
"modelFailureBody": "समर्थित रोग मॉडेल उपलब्ध होते, परंतु विश्लेषण पूर्ण होऊ शकले नाही.",
"photoNeedsImprovement": "फोटो सुधारणा आवश्यक",
"noSpecialistAvailable": "CropPilot कडे या पिकासाठी सध्या सत्यापित रोग मॉडेल नाही.",
"cropUnknownNoModel": "CropPilot या फोटोवरून पीक ओळखू शकले नाही, त्यामुळे सत्यापित रोग मॉडेल निवडता आले नाही.",
"noCoverageTitle": "पीक सध्या समर्थित नाही",
"lowConfidenceTitle": "निदान अनिश्चित",
"lowConfidenceBody": "विश्वसनीय निदान देण्याइतकी उपलब्ध मॉडेल्स सहमत झाली नाहीत.",
"confidenceNotAvailable": "उपलब्ध नाही",
"cropIdentification": "पीक ओळख",
"cropSource": "पीक स्रोत",
"routingLabel": "रूटिंग",
"specialistsLabel": "तज्ञ",
"specialistsNone": "कोणीही पात्र नाही",
"calibrationLabel": "कॅलिब्रेशन",
"calibrationUnavailable": "उपलब्ध नाही (कच्चे मॉडेल स्कोअर)",
"vlmLabel": "VLM फॉलबॅक",
"vlmNotConfigured": "कॉन्फिगर केलेले नाही",
"vlmUsed": "पुनरावलोकनासाठी वापरले",
"vlmNotUsed": "वापरले नाही",
"coverageTitle": "सध्याचे मॉडेल कव्हरेज",
"coverageBody": "{count} सत्यापित प्रोडक्शन मॉडेल मार्ग. कव्हरेज मर्यादित आहे आणि वाढत आहे.",
"whyLabel": "का?",
"whatToDoLabel": "तुम्ही काय करू शकता",
"errNoCoverage": "CropPilot कडे या पिकासाठी सध्या सत्यापित रोग मॉडेल नाही.",
"errModelFailure": "समर्थित रोग मॉडेल उपलब्ध होते, परंतु विश्लेषण पूर्ण होऊ शकले नाही. कृपया पुन्हा प्रयत्न करा.",
"noDiagnosis": "निदान नाही",
"statusNotSupported": "समर्थित नाही",
"statusFailed": "अयशस्वी",
"downloadSummary": "सारांश डाउनलोड करा",
"shareSummary": "सारांश सामायिक करा",
"summaryCopied": "सारांश क्लिपबोर्डवर कॉपी झाला",
"analyzeAnotherPhoto": "दुसऱ्या फोटोचे विश्लेषण करा",
"stepsTitle": "विश्लेषण पायऱ्या",
"stepUpload": "फोटो अपलोड होत आहे",
"stepQuality": "प्रतिमा गुणवत्ता तपासत आहे",
"stepRouting": "रोग तज्ञ निवडत आहे",
"stepAnalysis": "विश्लेषण चालू आहे",
"stepVerify": "निकाल पडताळत आहे",
"supportedCropsNote": "सत्यापित तज्ञ असलेली पिके",
"cropUnknownWeakEvidence": "योग्य रोग तज्ञ निवडण्यासाठी पुरेशा पुराव्यासह CropPilot पीक ओळखू शकले नाही.",
"unknownCropWhy": "उपलब्ध मॉडेलने कमकुवत निकाल दिले, परंतु पीक निश्चित करण्यासाठी प्रतिमेत पुरेसा पुरावा नाही.",
"modelOutputs": "मॉडेल आउटपुट",
"modelOutputsInterpretation": "पारदर्शकतेसाठी कच्चे मॉडेल आउटपुट दाखवले आहेत; ते सत्यापित रोग निदान मानले जात नाहीत.",
"rawScoreLabel": "कच्चा स्कोअर",
},
"assistant": {
"title": "AI सहाय्यक",
"placeholder": "किमती, हवामान, योजनांबद्दल विचारा…",
"send": "पाठवा",
"offline": "सहाय्यक अनुपलब्ध आहे. कृपया नंतर पुन्हा प्रयत्न करा.",
"offlineBackend": "सहाय्यक अनुपलब्ध आहे. बॅकएंड चालू आहे का ते तपासा.",
"sources": "स्रोत",
"newChat": "नवीन गप्पा",
"welcome": "नमस्कार! मी **CropPilot AI** आहे — तुमचा बुद्धिमान शेती सहाय्यक. 🌾\n\nमी तुम्हाला मदत करू शकतो:\n\n- **पीक व्यवस्थापन** — पेरणी, सिंचन, खत वेळापत्रक\n- **रोग ओळख** — पीक रोग ओळखा आणि उपचार करा\n- **बाजार विश्लेषण** — रिअल-टाइम मंडी भाव आणि कल\n- **शासकीय योजना** — तुम्ही पात्र असलेल्या योजना शोधा\n- **हवामान माहिती** — अंदाज आणि पिकांवर परिणाम\n\nआज तुमच्या शेताबद्दल काय जाणून घ्यायचे आहे?",
"welcomeTitle": "CropPilot मध्ये स्वागत आहे",
"welcomePreview": "नमस्कार! मी CropPilot AI आहे…",
"newChatTitle": "नवीन गप्पा",
"newChatPreview": "संभाषण सुरू करा…",
"promptPaddy": "गहू लागवडीसाठी सर्वोत्तम पद्धती",
"promptDisease": "टोमॅटो पानावरील करपा ओळखा",
"promptMarket": "चालू मंडी भाव",
"promptSchemes": "शेतकऱ्यांसाठी शासकीय योजना",
"suggestTitle": "शेतीबद्दल काहीही विचारा — पिके, रोग, बाजार, योजना आणि बरेच काही",
"cardCrop": "पीक सल्ला",
"cardCropBody": "गहू लागवडीसाठी सर्वोत्तम पद्धती",
"cardCropQuery": "गहू लागवडीसाठी सर्वोत्तम पद्धती कोणत्या?",
"cardDisease": "रोग मदत",
"cardDiseaseBody": "टोमॅटोतील पान करपा ओळखा आणि उपचार करा",
"cardDiseaseQuery": "टोमॅटो रोपांतील पान करपा कसा ओळखावा आणि उपचार करावा?",
"cardMarket": "बाजार प्रश्न",
"cardMarketBody": "धान आणि गव्हासाठी चालू मंडी भाव",
"cardMarketQuery": "तेलंगणात धान आणि गव्हासाठी चालू मंडी भाव काय आहेत?",
"cardScheme": "योजना माहिती",
"cardSchemeBody": "लहान शेतकऱ्यांसाठी शासकीय योजना",
"cardSchemeQuery": "भारतातील लहान शेतकरी म्हणून मी कोणत्या शासकीय योजनांसाठी पात्र आहे?",
"cardWeather": "हवामान प्रश्न",
"cardWeatherBody": "आगामी हवामान आणि पिकांवर परिणाम",
"cardWeatherQuery": "आगामी हवामानाचा माझ्या खरीप पिकांवर कसा परिणाम होईल?",
"cardPlan": "शेत नियोजन",
"cardPlanBody": "पीक फेरपालट आणि माती व्यवस्थापन टिपा",
"cardPlanQuery": "माझ्या शेतासाठी कोणती पीक फेरपालट पाळावी?",
"sideNewChat": "नवीन गप्पा",
"sideSearch": "संभाषणे शोधा…",
"sideNoFound": "संभाषणे आढळली नाहीत",
"sideNoYet": "अद्याप संभाषणे नाहीत",
"sideClose": "साइडबार बंद करा",
"sideOpen": "साइडबार उघडा",
"sideDelete": "संभाषण हटवा",
"inputDefault": "पिके, रोग, बाजार, योजनांबद्दल विचारा…",
"voiceError": "आवाज त्रुटी",
"voiceUnreachable": "आवाज सेवा पोहोचेबाहेर",
"micDenied": "मायक्रोफोन प्रवेश नाकारला",
"paletteSearch": "पृष्ठे शोधा किंवा कमांड टाइप करा…",
"paletteEmpty": "निकाल आढळले नाहीत.",
"errorTitle": "काहीतरी चूक झाली",
"errorFallback": "अनपेक्षित त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
"notFoundTitle": "पृष्ठ आढळले नाही",
"notFoundBody": "तुम्ही शोधत असलेले पृष्ठ अस्तित्वात नाही किंवा हलवले आहे.",
"goDashboard": "डॅशबोर्डवर जा",
"goHome": "मुख्यपृष्ठावर जा",
"loadingApp": "CropPilot लोड होत आहे…",
"themeToggle": "थीम टॉगल करा",
"themeCurrent": "सध्याची थीम: {theme}. {next} साठी क्लिक करा",
"themeLight": "लाइट",
"themeDark": "डार्क",
"themeSystem": "सिस्टम",
"attachFiles": "फाइल्स जोडा",
"attachDocs": "प्रतिमा आणि दस्तऐवज",
"takePhoto": "फोटो घ्या",
"copyResponse": "प्रतिसाद कॉपी करा",
"copied": "कॉपी झाले",
"helpful": "उपयुक्त",
"notHelpful": "उपयुक्त नाही",
"fileTypeUnsupported": "\"{type}\" फाइल प्रकार समर्थित नाही",
"sourcesCount": "{count} स्रोत",
"sourcesCountPlural": "{count} स्रोत",
},
"maps": {
"loading": "लोड होत आहे…",
"searchLocation": "गाव, शहर, बाजार किंवा पिन कोड शोधा",
"clearSearch": "शोध साफ करा",
"searchFailed": "स्थान आढळले नाही. दुसरा शोध करून पहा.",
"noResults": "जुळणारी ठिकाणे आढळली नाहीत.",
"useMyLocation": "माझे स्थान वापरा",
"resetView": "भारत दृश्य रीसेट करा",
"fullscreen": "पूर्ण-स्क्रीन नकाशा",
"mapLabel": "भारताचा CropPilot शेती नकाशा",
"location": "स्थान",
"locationInsights": "स्थान माहिती",
"placeUnavailable": "ठिकाणाचे नाव उपलब्ध नाही — निर्देशांक दाखवले आहेत.",
"weather": "हवामान",
"weatherMapTitle": "हवामान नकाशा",
"rainRadar": "पाऊस रडार",
"weatherUnavailable": "हवामान माहिती तात्पुरती अनुपलब्ध आहे.",
"humidity": "आर्द्रता",
"wind": "वारा",
"rain": "पाऊस",
"feelsLike": "असे वाटते",
"wmoCode": "WMO कोड {code}",
"updatedJustNow": "त्ताच अद्यतनित",
"updatedMinutesAgo": "{count} मि. पूर्वी अद्यतनित",
"updatedHoursAgo": "{count} तासांपूर्वी अद्यतनित",
"sourceOpenMeteo": "स्रोत: Open-Meteo",
"nearbyMarkets": "जवळची बाजारपेठा",
"commodityFilter": "जिनसानुसार गाळा",
"allCommodities": "सर्व जिन्नस",
"searchArea": "या क्षेत्रात शोधा",
"marketsUnavailable": "जवळची बाजार माहिती लोड होऊ शकली नाही.",
"noMappedMarkets": "जवळपास नकाशा निर्देशांक असलेली बाजारपेठा आढळली नाहीत.",
"noReportedPrice": "या बाजारासाठी अद्याप नोंदवलेला भाव नाही.",
"latestReported": "नवीनतम नोंद: {date}",
"sourceAgmarknet": "स्रोत: AGMARKNET",
"quintal": "क्विंटल",
"unmappedNote": "येथील आणखी {count} बाजारपेठांचे नकाशा निर्देशांक अद्याप नाहीत; ते मार्केट इंटेलिजन्समध्ये सूचीबद्ध आहेत.",
"closeDetails": "बाजार तपशील बंद करा",
"viewMarketIntel": "मार्केट इंटेलिजन्स पहा",
"cropPilotActions": "CropPilot क्रिया",
"openMarketIntel": "मार्केट इंटेलिजन्स",
"analyzeDisease": "पीक रोग विश्लेषण",
"askAssistant": "CropPilot AI ला विचारा",
"legendSelected": "निवडलेले स्थान",
"legendMarkets": "बाजारपेठा",
"markets": "बाजारपेठा",
"toggleMarkets": "बाजार मार्कर चालू/बंद करा",
"pickHint": "स्थान निवडण्यासाठी नकाशावर क्लिक करा",
"collapseSheet": "पॅनेल लहान करा",
"expandSheet": "पॅनेल मोठे करा",
"geoDenied": "स्थान प्रवेश नाकारला. त्याऐवजी तुमचे स्थान शोधू शकता.",
"geoUnavailable": "सध्याचे स्थान उपलब्ध नाही. त्याऐवजी शोधून पहा.",
"geoTimeout": "स्थान विनंती कालबाह्य. पुन्हा प्रयत्न करा किंवा शोधा.",
"geoUnsupported": "या ब्राउझरमध्ये जिओलोकेशन समर्थित नाही. कृपया शोधा.",
"mapUnavailable": "या डिव्हाइसवर परस्परसंवादी नकाशा अनुपलब्ध आहे (WebGL बंद). शोध आणि स्थान माहिती खाली चालू आहे.",
"agriSnapshot": "शेती स्नॅपशॉट",
"commonCrops": "सामान्य पिके",
"soil": "माती",
"rainfall": "पर्जन्य",
"seasonRain": "{season} मध्ये {mm} मिमी",
"forecastLabel": "अंदाज",
"texture": "पोत",
"organicCarbon": "सेंद्रिय कर्ब",
"clay": "चिकणमाती",
"sand": "वाळू",
"silt": "गाळ",
"nitrogen": "नत्र",
"sourceSoilGrids": "स्रोत: SoilGrids",
"resolutionM": "रिझॉल्यूशन: {m} मी",
"modelledEstimateNote": "मॉडेल अंदाज, प्रयोगशाळा माती चाचणी नाही",
"modelledBadge": "मॉडेल-आधारित",
"soilUnavailable": "या स्थानासाठी माती डेटा उपलब्ध नाही.",
"today": "आज",
"last7days": "मागील 7 दिवस",
"thisMonth": "या महिन्यात",
"season": "हंगाम",
"reanalysisNote": "पुनर्विश्लेषण/अंदाज, स्टेशन डेटा नाही",
"rainfallUnavailable": "या स्थानासाठी पर्जन्य डेटा उपलब्ध नाही.",
"crops": "पिके",
"commonlyTraded": "क्षेत्र मंडईत अलीकडे व्यापार झालेल्या जिन्नस",
"cropsUnavailable": "या क्षेत्रासाठी पीक व्यापार डेटा उपलब्ध नाही.",
"suitabilityTitle": "पर्यावरणीय उपयुक्तता अंदाज",
"water": "जलस्रोत",
"waterUnavailable": "या स्थानासाठी जल डेटा उपलब्ध नाही.",
"waterNote": "भूजल निरीक्षणे नियतकालिक असतात आणि जलाशय साठा शेत-स्तरीय सिंचन उपलब्धता दर्शवत नाही.",
"diseaseContext": "रोग संदर्भ",
"diseaseUnavailable": "या क्षेत्रासाठी रोग संदर्भ उपलब्ध नाही.",
"selectedLocation": "निवडलेले स्थान",
"viewFullMap": "पूर्ण नकाशा पहा",
"yourLocation": "तुमचे स्थान",
},
"markets": {
"title": "मार्केट इंटेलिजन्स",
"subtitle": "AGMARKNET कडून नवीनतम नोंदवलेले मंडी भाव",
"state": "राज्य",
"district": "जिल्हा",
"market": "बाजार",
"commodity": "जिंस",
"days": "दिवस",
"latestPrice": "नवीनतम नोंदवलेला भाव: {price} प्रति क्विंटल",
"arrivalDate": "आवक तारीख: {date}",
"empty": "डेटाबेसमध्ये जुळणारा नवीनतम नोंदवलेला भाव आढळला नाही.",
"unavailableTitle": "बाजार डेटा सध्या अनुपलब्ध आहे",
"tryAgain": "पुन्हा प्रयत्न करा",
"signInRequired": "साइन इन आवश्यक",
"signInPrompt": "मार्केट इंटेलिजन्स पाहण्यासाठी कृपया साइन इन करा.",
"signInNeeded": "मार्केट इंटेलिजन्स पाहण्यासाठी कृपया साइन इन करा.",
"offline": "बाजार सेवेशी संपर्क होऊ शकला नाही. कनेक्शन पूर्ववत झाल्यावर साठवलेली निरीक्षणे दिसतील.",
"loadError": "हा विभाग लोड करताना काहीतरी चूक झाली. तुमची साठवलेली निरीक्षणे सुरक्षित आहेत.",
"loadErrorShort": "हा विभाग लोड करताना काहीतरी चूक झाली.",
"allStates": "सर्व राज्ये",
"allDistricts": "सर्व जिल्हे",
"selectStateFirst": "आधी राज्य निवडा",
"allMarkets": "सर्व बाजारपेठा",
"selectCommodity": "जिंस निवडा",
"allVarieties": "सर्व जाती",
"allGrades": "सर्व प्रत",
"variety": "जात",
"grade": "प्रत",
"statesReporting": "अहवाल देणारी राज्ये",
"marketsReporting": "अहवाल देणारी बाजारपेठा",
"commoditiesReported": "नोंदवलेल्या जिन्नस",
"latestObservation": "नवीनतम निरीक्षण",
"storedObservations": "साठवलेली निरीक्षणे दाखवत आहे",
"storedObservationsBody": "या निवडीसाठी स्रोताने अलीकडील निरीक्षण प्रकाशित केलेले नाही. खालील मूल्ये नवीनतम साठवलेले अहवाल आहेत, नवीन भाव नाहीत.",
"noRecentPrice": "अलीकडील नोंदवलेला भाव नाही",
"emptyHint": "वेगळे राज्य, जिल्हा, जिंस किंवा बाजार वापरून पहा. पुढील स्रोत प्रकाशनानंतर नवीन अहवाल येथे दिसतील.",
"selectionSummary": "निवड सारांश",
"reportedMarkets": "नोंदवलेली बाजारपेठा",
"observationsInTable": "तक्त्यातील निरीक्षणे",
"trendPoints": "कल बिंदू",
"comingLater": "लवकरच येत आहे",
"comingLaterBody": "किंमत अंदाज आणि विक्री शिफारसी अद्याप या दृश्याचा भाग नाहीत. येथे केवळ नोंदवलेली निरीक्षणे दाखवली आहेत.",
"searchStates": "राज्ये शोधा…",
"searchDistricts": "जिल्हे शोधा…",
"searchMarkets": "बाजारपेठा शोधा…",
"noMatchState": "जुळणारे राज्य नाही.",
"noMatchDistrict": "जुळणारा जिल्हा नाही.",
"noMatchMarket": "जुळणारी बाजारपेठ नाही.",
"tableSearch": "लोड केलेल्या निकालांमध्ये शोधा…",
"thMin": "किमान रु",
"thMax": "कमाल रु",
"thModal": "मोडल रु",
"thArrivals": "आवक",
"thObserved": "निरीक्षण",
"showingCount": "{from}–{to} पैकी {total}",
"prevPage": "मागील पृष्ठ",
"nextPage": "पुढील पृष्ठ",
"priceRs": "रु{value}",
"minMaxLine": "किमान रु{min} · कमाल रु{max}",
"arrivalsLine": "आवक: {value}",
"freshNone": "अलीकडील निरीक्षण उपलब्ध नाही",
"freshLatest": "नवीनतम नोंद: {date}",
"freshStale": "डेटा विलंबित असू शकतो",
"sourceLabel": "स्रोत: {name}",
"sourceBody": "नोंदवलेले मंडी भाव बाजारपेठांनी प्रकाशित केलेली निरीक्षणे आहेत आणि विलंबाने येऊ शकतात. ते हमीभाव नाहीत.",
"sourceResource": "संसाधन: {id}",
"cmpNoData": "तुलना उपलब्ध नाही",
"cmpNoDataBody": "या निवडीसाठी अद्याप नोंदवलेले भाव नाहीत.",
"cmpTitle": "बाजार तुलना",
"cmpBody": "जुळणारी जात, प्रत आणि एकक असलेल्या पंक्तींचीच तुलना केली जाते. भाव प्रत्येक बाजाराचे नवीनतम नोंदवलेले निरीक्षण आहेत.",
"cmpMinMax": "किमान ते कमाल रु",
"histNoData": "भाव इतिहास नाही",
"histNoDataBody": "निवडलेल्या बाजार आणि जिनसासाठी या कालावधीत नोंदवलेली निरीक्षणे नाहीत.",
"histTitle": "नोंदवलेला मोडल भाव कल",
"histUnit": "Rs प्रति {unit}",
"histModal": "मोडल",
"histMax": "कमाल",
"histMin": "किमान",
"histCount": "{count} निरीक्षणे",
"histObserved": "{label} रोजी निरीक्षण",
"cmpUnspecified": "अनिर्दिष्ट जात आणि प्रत",
},
"schemes": {
"title": "शासकीय योजना",
"subtitle": "शेती योजना, अनुदाने आणि कल्याण कार्यक्रम शोधा आणि अर्ज करा",
"search": "नाव, वर्णन, टॅगनुसार योजना शोधा…",
"all": "सर्व",
"noFound": "योजना आढळल्या नाहीत",
"noFoundBody": "तुमचा शोध किंवा गाळणी निकष बदला",
"viewDetail": "तपशील पहा",
"eligibility": "पात्रता",
"benefits": "लाभ",
"howToApply": "अर्ज कसा करावा",
"close": "बंद करा",
"moreDetails": "अधिक तपशील",
"applicationProcess": "अर्ज प्रक्रिया:",
"funding": "निधी:",
"checkEligibility": "पात्रता तपासा",
"ministry": "मंत्रालय:",
"eligibilityCriteria": "पात्रता निकष",
"requiredDocuments": "आवश्यक कागदपत्रे",
"active": "सक्रिय",
"inactive": "निष्क्रिय",
"applyNow": "आत्ता अर्ज करा",
},
"analytics": {
"title": "विश्लेषण",
"subtitle": "तुमच्या शेत कामगिरीची सर्वसमावेशक माहिती",
"tabRevenue": "महसूल",
"tabYield": "उत्पादन",
"tabCropHealth": "पीक आरोग्य",
"tabWater": "पाणी वापर",
"tabFertilizer": "खत वापर",
"tabMarket": "बाजार विश्लेषण",
"statRevenue": "एकूण महसूल",
"statYield": "सरासरी उत्पादन/हे",
"statHealth": "आरोग्य स्कोअर",
"statWater": "पाणी कार्यक्षमता",
"rangeCustom": "सानुकूल",
"chRevenueMonthly": "मासिक महसूल",
"chRevenueByCrop": "पिकानुसार महसूल",
"chRevenueCumulative": "संचयी महसूल",
"chYieldByCrop": "पिकानुसार उत्पादन",
"chYieldTrend": "उत्पादन कल",
"chYieldVsTarget": "उत्पादन वि. लक्ष्य",
"chYieldPerHa": "प्रति हेक्टर उत्पादन",
"chYieldTopBottom": "सर्वोत्तम आणि सर्वात कमी कामगिरीची पिके",
"chHealthOverall": "एकूण आरोग्य",
"chHealthRadar": "आरोग्य मेट्रिक्स रडार",
"chHealthTrend": "आरोग्य स्कोअर कल",
"chHealthByPlot": "प्लॉटानुसार आरोग्य",
"chHealthTimeline": "आरोग्य सूचना टाइमलाइन",
"chPriceTrends": "भाव कल - शीर्ष 5 जिन्नस",
"chPriceHeatmap": "भाव हीटमॅप - जिंस वि. महिना",
"chBestTimes": "सर्वोत्तम विक्री वेळा",
"chTrade": "निर्यात / आयात विश्लेषण",
"chVolume": "व्यापार मात्रा",
"chInsights": "AI माहिती",
"chWaterDaily": "पर्जन्यासह दैनिक पाणी वापर",
"chWaterByCrop": "पिकानुसार पाणी वापर",
"chWaterEff": "पाणी कार्यक्षमता (प्रति किलो उत्पादनासाठी लिटर)",
"chWaterSave": "पाणी बचत सूचना",
"chWaterSchedule": "वेळापत्रक शिफारसी",
"chFertBreakdown": "खत प्रकार विभाजन",
"chFertCost": "शिफारसीशी खर्च तुलना",
"chFertNPK": "N / P / K वापर कालांतराने",
"statVolatility": "भाव अस्थिरता निर्देशांक",
"statGainers": "शीर्ष वाढ",
"statLosers": "शीर्ष घसरण",
"statVolume": "एकूण मात्रा",
"trendLow": "कमी",
"thCommodity": "जिंस",
"expShort": "नि",
"impShort": "आ",
},
"voice": {
"start": "आवाज इनपुट सुरू करा",
"stop": "थांबा",
"listening": "ऐकत आहे…",
"transcribing": "लेखन करत आहे…",
"thinking": "विचार करत आहे…",
"speaking": "बोलत आहे…",
"unavailable": "या डिव्हाइसवर आवाज इनपुट अनुपलब्ध आहे.",
"audioUnavailable": "या भाषेसाठी बोललेले आउटपुट अनुपलब्ध आहे.",
"recording": "रेकॉर्ड होत आहे…",
},
"errors": {
"network": "नेटवर्क त्रुटी. तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
"unauthorized": "सत्र कालबाह्य. कृपया पुन्हा साइन इन करा.",
"notFound": "आढळले नाही.",
},
"crops": {
"rice": "तांदूळ",
"paddy": "धान",
"wheat": "गहू",
"cotton": "कापूस",
"maize": "मका",
"sugarcane": "ऊस",
"tomato": "टोमॅटो",
"potato": "बटाटा",
"onion": "कांदा",
"soybean": "सोयाबीन",
"groundnut": "भुईमूग",
"chilli": "मिरची",
},
}

ROOT = Path(__file__).resolve().parents[1] / "i18n" / "messages" / "mr.json"
emit("mr", T)
