# Complete Nepali (ne) catalog. Run from frontend/: python scripts/tr-ne.py
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emit_locale import emit

T = {
"common": {
"appName": "CropPilot",
"loading": "लोड हुँदैछ…",
"retry": "पुनः प्रयास गर्नुहोस्",
"cancel": "रद्द गर्नुहोस्",
"close": "बन्द गर्नुहोस्",
"save": "बचत गर्नुहोस्",
"search": "खोज्नुहोस्",
"noData": "डाटा उपलब्ध छैन।",
"errorGeneric": "केही गलत भयो। कृपया पुनः प्रयास गर्नुहोस्।",
"prevSlide": "अघिल्लो स्लाइड",
"nextSlide": "अर्को स्लाइड",
"menu": "मोबाइल मेनु टगल गर्नुहोस्",
"language": "भाषा",
"selectLanguage": "भाषा छान्नुहोस्",
"commandPalette": "कमाण्ड प्यालेट",
},
"navigation": {
"dashboard": "ड्यासबोर्ड",
"markets": "बजारहरू",
"weather": "मौसम",
"disease": "रोग पहिचान",
"schemes": "योजनाहरू",
"analytics": "विश्लेषण",
"maps": "नक्साहरू",
"assistant": "AI सहायक",
},
"auth": {
"signIn": "साइन इन गर्नुहोस्",
"signOut": "साइन आउट गर्नुहोस्",
"welcomeBack": "पुनः स्वागत छ",
"signInSubtitle": "आफ्नो CropPilot खातामा साइन इन गर्नुहोस्",
"email": "इमेल",
"password": "पासवर्ड",
"enterPassword": "आफ्नो पासवर्ड लेख्नुहोस्",
"rememberMe": "मलाई सम्झनुहोस्",
"signingIn": "साइन इन हुँदैछ…",
"signInBtn": "साइन इन",
"noAccount": "खाता छैन?",
"registerLink": "दर्ता गर्नुहोस्",
"emailRequired": "इमेल आवश्यक छ",
"emailInvalid": "अमान्य इमेल ठेगाना",
"passwordRequired": "पासवर्ड आवश्यक छ",
"passwordMin": "पासवर्ड कम्तीमा 6 अक्षरको हुनुपर्छ",
"invalidCredentials": "अमान्य विवरण। कृपया पुनः प्रयास गर्नुहोस्।",
"createAccount": "खाता बनाउनुहोस्",
"registerSubtitle": "CropPilot मा सामेल हुनुहोस् र स्मार्ट खेती सुरु गर्नुहोस्",
"fullName": "पूरा नाम",
"fullNamePlaceholder": "आफ्नो पूरा नाम",
"phone": "फोन नम्बर",
"selectState": "राज्य छान्नुहोस्",
"selectDistrict": "जिल्ला छान्नुहोस्",
"createPassword": "पासवर्ड बनाउनुहोस्",
"confirmPassword": "पासवर्ड पुष्टि गर्नुहोस्",
"confirmPasswordPlaceholder": "आफ्नो पासवर्ड पुष्टि गर्नुहोस्",
"registerBtn": "दर्ता गर्नुहोस्",
"registering": "दर्ता हुँदैछ…",
"haveAccount": "पहिले नै खाता छ?",
"signInLink": "साइन इन गर्नुहोस्",
"nameRequired": "नाम आवश्यक छ",
"phoneInvalid": "अमान्य फोन नम्बर",
"phoneLong": "फोन नम्बर धेरै लामो छ",
"selectStateRequired": "कृपया राज्य छान्नुहोस्",
"selectDistrictRequired": "कृपया जिल्ला छान्नुहोस्",
"passwordMismatch": "पासवर्ड मिलेनन्",
"showPassword": "पासवर्ड देखाउनुहोस्",
"hidePassword": "पासवर्ड लुकाउनुहोस्",
"nameMin": "पूरा नाम कम्तीमा 2 अक्षरको हुनुपर्छ",
"phoneMin": "फोन नम्बर कम्तीमा 10 अंकको हुनुपर्छ",
"confirmRequired": "कृपया आफ्नो पासवर्ड पुष्टि गर्नुहोस्",
"acceptTerms": "तपाईंले नियम र सर्तहरू स्वीकार्नुपर्छ",
"registerFailed": "दर्ता असफल। कृपया पुनः प्रयास गर्नुहोस्।",
"acceptPrefix": "म स्वीकार्छु",
"termsService": "सेवाका सर्तहरू",
"termsAnd": "र",
"privacyPolicy": "गोपनीयता नीति",
"creatingAccount": "खाता बन्दैछ…",
"authLayoutTitle": "CropPilot मा स्वागत छ",
"authLayoutBody": "आधुनिक खेतीका लागि ओपन-सोर्स प्लेटफर्म। ड्यासबोर्डका लागि साइन इन गर्नुहोस्।",
},
"landing": {
"badge": "निःशुल्क र ओपन-सोर्स सफ्टवेयर",
"tagline": "स्मार्ट खेतीका लागि ओपन-सोर्स उपकरणहरू।",
"heroBody": "बाली स्वास्थ्य, रोग पहिचान, मौसम जानकारी र दर्ता मण्डी बजार भावका लागि किसान-केन्द्रित प्लेटफर्म।",
"openApp": "CropPilot खोल्नुहोस्",
"viewGithub": "GitHub मा हेर्नुहोस्",
"featuresTitle": "तपाईं के गर्न सक्नुहुन्छ",
"featCrop": "बाली स्वास्थ्य",
"featCropBody": "बालीको अवस्था र सम्बन्धित खेत जानकारी ट्र्याक गर्नुहोस्।",
"featDisease": "रोग पहिचान",
"featDiseaseBody": "समर्थित रोग पहिचान प्रक्रियाका लागि बालीका तस्बिरहरूको विश्लेषण गर्नुहोस्।",
"featWeather": "मौसम जानकारी",
"featWeatherBody": "खेती निर्णयका लागि उपयोगी मौसम जानकारी हेर्नुहोस्।",
"featMarket": "बजार जानकारी",
"featMarketBody": "AGMARKNET बाट सरकारी खुला डाटामार्फत दर्ता मण्डी भाव खोज्नुहोस्।",
"appTitle": "एप्लिकेसन",
"appBody": "खेत अवलोकन, मौसम, बाली स्वास्थ्य र बजार खण्डसहित CropPilot ड्यासबोर्ड।",
"appCaption": "नमुना डाटासहित चलिरहेको CropPilot ड्यासबोर्ड।",
"appAlt": "नमुना डाटासहित खेत अवलोकन, मौसम, बाली स्वास्थ्य र बजार खण्ड देखाउने CropPilot ड्यासबोर्ड स्क्रिनसट",
"marketTitle": "बजार जानकारी",
"marketBody": "राज्य, जिल्ला, बजार, जिन्स, जात, ग्रेड र अवधिअनुसार नवीनतम दर्ता मण्डी भाव हेर्नुहोस्, साथै प्रवृत्ति र बजार तुलना।",
"marketSource": "स्रोत: सरकारी खुला डाटामार्फत AGMARKNET। मूल्यहरू अवलोकन मितिसहित दर्ता अवलोकन हुन्, चालु बजार भावका रूपमा कहिल्यै प्रस्तुत गरिँदैनन्।",
"marketCta": "बजार भाव खोज्नुहोस्",
"whyTitle": "किसानका लागि बनेको। खुलापनमा बनेको।",
"whyBody": "CropPilot निःशुल्क र ओपन-सोर्स सफ्टवेयर हो जसले खेती उपकरण र जानकारी सजिलो बनाउँछ। यो MIT अनुमतिमा चल्छ र विकास GitHub मा पारदर्शी रूपमा हुन्छ।",
"archTitle": "आर्किटेक्चर",
"archBody": "खेत र स्थानीय डाटाका लागि PostgreSQL र PostGIS, पृष्ठभूमि कामका लागि Celery वर्करहरू र रोग पहिचानका लागि PyTorch भिजन मोडेलसहित FastAPI सेवामा आधारित Next.js फ्रन्टएन्ड। सबै Docker Compose बाट स्थानीय रूपमा चल्छ।",
"ossTitle": "GitHub मा ओपन सोर्स",
"ossBody": "कोड हेर्नुहोस्, समस्या दर्ता गर्नुहोस् र सुधारमा योगदान दिनुहोस्। MIT अनुमतिप्राप्त।",
"footerTag": "ओपन-सोर्स कृषि प्लेटफर्म।",
"footerDocs": "कागजात",
"navFeatures": "विशेषताहरू",
"navArchitecture": "आर्किटेक्चर",
"toggleMenu": "मेनु टगल गर्नुहोस्",
"footerLabel": "फुटर",
},
"dashboard": {
"welcomeBack": "पुनः स्वागत छ, {name}",
"farmer": "किसान",
"selectFarm": "खेत छान्नुहोस्",
"allFarms": "सबै खेतहरू",
"wFarmOverview": "खेत अवलोकन",
"wWeather": "आजको मौसम",
"wCropHealth": "बाली स्वास्थ्य",
"wDiseaseAlerts": "रोग सूचना",
"wRevenue": "आम्दानी",
"wExpenses": "खर्च",
"wNetProfit": "खुद नाफा",
"wYield": "उत्पादन",
"wMarketTrends": "बजार प्रवृत्ति",
"wSchemes": "योजना सिफारिस",
"wNotifications": "सूचना",
"wQuickActions": "छिटो कार्य",
"vsLastMonth": "अघिल्लो महिनाको तुलनामा",
"totalYield": "कुल उत्पादन",
"perHectare": "प्रति हेक्टर",
"noAlerts": "कुनै सक्रिय रोग सूचना छैन",
"cropsHealthy": "तपाईंका बालीहरू स्वस्थ छन्",
"noNotifications": "सूचना छैनन्",
"qaScan": "बाली स्क्यान गर्नुहोस्",
"qaWeather": "मौसम हेर्नुहोस्",
"qaMarkets": "बजार हेर्नुहोस्",
"qaAssistant": "AI सहायक",
"statFarms": "कुल खेतहरू",
"statArea": "कुल क्षेत्र",
"statPlots": "सक्रिय प्लटहरू",
"statSeason": "चालु सिजन",
"notifMarkRead": "सबै पढेको चिन्ह लगाउनुहोस्",
"marginLabel": "मार्जिन:",
},
"weather": {
"title": "मौसम",
"subtitle": "तपाईंको खेतका लागि ताजा मौसम डाटा र पूर्वानुमान",
"searchLocation": "स्थान खोज्नुहोस्…",
"noLocations": "स्थान भेटिएनन्",
"hourly": "घण्टे-घण्टेको पूर्वानुमान",
"details": "मौसम विवरण",
"rainProbability": "वर्षाको सम्भावना",
"windSpeed": "हावाको गति",
"humidity": "आर्द्रता",
"uvIndex": "UV सूचकांक",
"pressure": "चाप",
"visibility": "दृश्यता",
"weekly": "7-दिने पूर्वानुमान",
"feelsLike": "{temp}° जस्तो लाग्छ",
"highShort": "अधिक: {temp}°",
"lowShort": "न्यून: {temp}°",
},
"disease": {
"title": "रोग पहिचान",
"subtitle": "AI-संचालित रोग निदानका लागि बालीका तस्बिर अपलोड वा कैद गर्नुहोस्",
"newDetection": "नयाँ जाँच",
"analyzing": "तपाईंको बाली तस्बिरको विश्लेषण हुँदैछ…",
"analyzingBody": "AI रोग ढाँचा स्क्यान गर्दैछ",
"readyTitle": "निदानका लागि तयार",
"readyBody": "तुरुन्त AI रोग पहिचान र उपचार सिफारिसका लागि प्रभावित बालीको फोटो अपलोड वा कैद गर्नुहोस्",
"confidence": "AI विश्वास",
"cameraTitle": "क्यामेरा कैद",
"cameraBody": "प्रभावित बालीको फोटो लिनुहोस्",
"cameraHint": "प्रभावित पात वा फल फ्रेममा राख्नुहोस्",
"activateCamera": "क्यामेरा सुरु गर्नुहोस्",
"capture": "कैद गर्नुहोस्",
"retake": "पुनः लिनुहोस्",
"uploadTitle": "तस्बिर अपलोड गर्नुहोस्",
"uploadHint": "ड्र्याग र ड्रप वा ब्राउज गर्नुहोस्",
"dropHint": "अपलोडका लागि ड्र्याग र ड्रप वा क्लिक गर्नुहोस्",
"dropFormats": "JPG, PNG, WEBP 10MB सम्म",
"changeImage": "तस्बिर बदल्नुहोस्",
"fileTooBig": "फाइल आकार 10MB भन्दा कम हुनुपर्छ।",
"resultTitle": "जाँच नतिजा",
"detectedDisease": "भेटिएको रोग",
"confidenceScore": "विश्वास स्कोर",
"treatmentAvailable": "उपचार सिफारिस उपलब्ध",
"aiAnalysis": "AI-संचालित विश्लेषण",
"symptoms": "लक्षणहरू",
"recommendedActions": "सिफारिस गरिएका कार्य",
"preventiveMeasures": "रोकथाम उपाय",
"historyTitle": "जाँच इतिहास",
"thDate": "मिति",
"thCrop": "बाली",
"thDisease": "रोग",
"thConfidence": "विश्वास",
"thStatus": "स्थिति",
"sevLow": "कम",
"sevModerate": "मध्यम",
"sevHigh": "उच्च",
"sevCritical": "गम्भीर",
"pastDetections": "{count} विगत जाँचहरू",
"searchHistory": "बाली वा रोगबाट खोज्नुहोस्…",
"noDetections": "जाँच भेटिएनन्",
"stageCheckingPhoto": "फोटो गुणस्तर जाँचिँदैछ…",
"stageAnalyzing": "तस्बिरको विश्लेषण हुँदैछ…",
"cropHintLabel": "बाली (वैकल्पिक - सही विशेषज्ञ छान्न मद्दत गर्छ)",
"cropHintAuto": "स्वचालित (संकेत छैन)",
"unknownCrop": "अज्ञात बाली",
"uncertainTitle": "CropPilot ले समस्या पक्का पहिचान गर्न सकेन",
"uncertainBody": "निदानका लागि तस्बिर प्रमाण अपर्याप्त थियो। तलका विकल्प अनुमान हुन्, निदान होइन।",
"possibleCauses": "सम्भावित विकल्प",
"analyzeAnotherHint": "राम्रो उज्यालोमा एउटा प्रभावित पातको नजिकको फोटोबाट पुनः प्रयास गर्नुहोस्।",
"supportedCrops": "प्रमाणित विशेषज्ञ भएका बालीहरू",
"capabilitiesOffline": "निदान सेवा सूचीमा पुग्न सकिएन। तापनि अपलोड प्रयास गर्न सक्नुहुन्छ।",
"bandHigh": "उच्च",
"bandMedium": "मध्यम",
"bandLow": "कम",
"bandUnverified": "अप्रमाणित स्कोर",
"bandUnknown": "अज्ञात",
"statusDiagnosed": "सम्भावित निदान",
"statusProbable": "सम्भावित - प्रमाणीकरण चाहिन्छ",
"statusUncertain": "अनिश्चित",
"statusInsufficientImage": "फोटो बेकाम",
"statusUnsupportedCrop": "बाली अझै समर्थित छैन",
"statusError": "विश्लेषण असफल",
"uncalibratedScore": "मोडेल स्कोर (अक्यालिब्रेटेड)",
"uncalibratedScoreHint": "कच्चा मोडेल आउटपुट, क्यालिब्रेटेड सम्भावना होइन।",
"uploadedPhoto": "अपलोड गरिएको फोटो",
"evidenceTitle": "विश्लेषण विवरण",
"routingMode": "रूटिङ",
"modelsUsed": "प्रयोग मोडेलहरू",
"fieldValidation": "खेत प्रमाणीकरण",
"imageQuality": "तस्बिर गुणस्तर",
"latencyLabel": "विश्लेषण समय",
"researchBadge": "अनुसन्धान मोडेल",
"notVerified": "प्रमाणित छैन",
"guidanceFor": "मार्गदर्शन:",
"guidanceSource": "स्रोत",
"similarConditions": "मिल्दा अवस्थाहरू",
"noGuidance": "CropPilot सँग यस निदानका लागि अझै प्रमाणित मार्गदर्शन छैन।",
"imageNotRetained": "सत्र इतिहास मात्र - तस्बिरहरू राखिँदैनन्।",
"errNetwork": "नेटवर्क त्रुटि। आफ्नो जडान हेरेर पुनः प्रयास गर्नुहोस्।",
"errTooLarge": "तस्बिर धेरै ठूलो छ। 10 MB भन्दा सानो फोटो प्रयोग गर्नुहोस्।",
"errPoorQuality": "फोटो गुणस्तर विश्लेषणका लागि धेरै खराब छ। एउटा प्रभावित पातको नजिकको फोटो लिनुहोस्।",
"errUnsupportedCrop": "CropPilot सँग त्यस बालीका लागि अझै प्रमाणित विशेषज्ञ छैन।",
"errInvalid": "त्यो फाइल तस्बिरका रूपमा पढ्न सकिएन। JPG वा PNG फोटो प्रयास गर्नुहोस्।",
"errNoModel": "अहिले प्रमाणित निदान मोडेल उपलब्ध छैन। पछि प्रयास गर्नुहोस्।",
"errServer": "विश्लेषण असफल। स्पष्ट फोटोसहित पुनः प्रयास गर्नुहोस्।",
"analysisIncomplete": "विश्लेषण अधुरो",
"noVerifiedDiagnosis": "प्रमाणित निदान छैन",
"analysisStatusLabel": "विश्लेषण स्थिति",
"cropLabel": "बाली",
"cropNotIdentified": "पहिचान भएन",
"cropUnsupported": "असमर्थित",
"cropSourceUser": "तपाईंले छान्नुभयो (रूटिङ संकेत, मोडेल प्रमाण होइन)",
"cropSourceUnknown": "यस फोटोबाट पहिचान भएन",
"selectCropPrompt": "तपाईंलाई बाली थाहा छ? छान्दा CropPilot लाई सही विशेषज्ञ छान्न मद्दत गर्छ।",
"analyzeAgain": "पुनः विश्लेषण गर्नुहोस्",
"retryAnalysis": "पुनः प्रयास गर्नुहोस्",
"coverageBadge": "मोडेल कभरेज अनुपलब्ध",
"serviceBadge": "सेवा अनुपलब्ध",
"temporaryAnalysisFailure": "विश्लेषण अस्थायी असफल",
"modelFailureBody": "समर्थित रोग मोडेल उपलब्ध थियो, तर विश्लेषण पूरा हुन सकेन।",
"photoNeedsImprovement": "फोटो सुधार चाहिन्छ",
"noSpecialistAvailable": "CropPilot सँग यस बालीका लागि हाल प्रमाणित रोग मोडेल छैन।",
"cropUnknownNoModel": "CropPilot ले यस फोटोबाट बाली पहिचान गर्न सकेन, त्यसैले प्रमाणित रोग मोडेल छान्न सकिएन।",
"noCoverageTitle": "बाली हाल समर्थित छैन",
"lowConfidenceTitle": "निदान अनिश्चित",
"lowConfidenceBody": "विश्वसनीय निदान दिन पर्याप्त उपलब्ध मोडेल सहमत भएनन्।",
"confidenceNotAvailable": "उपलब्ध छैन",
"cropIdentification": "बाली पहिचान",
"cropSource": "बाली स्रोत",
"routingLabel": "रूटिङ",
"specialistsLabel": "विशेषज्ञहरू",
"specialistsNone": "कोही योग्य छैन",
"calibrationLabel": "क्यालिब्रेसन",
"calibrationUnavailable": "उपलब्ध छैन (कच्चा मोडेल स्कोर)",
"vlmLabel": "VLM फल ब्याक",
"vlmNotConfigured": "कन्फिगर गरिएको छैन",
"vlmUsed": "समीक्षाका लागि प्रयोग",
"vlmNotUsed": "प्रयोग भएन",
"coverageTitle": "हाल मोडेल कभरेज",
"coverageBody": "{count} प्रमाणित प्रोडक्सन मोडेल मार्ग। कभरेज सीमित छ र बढ्दैछ।",
"whyLabel": "किन?",
"whatToDoLabel": "तपाईं के गर्न सक्नुहुन्छ",
"errNoCoverage": "CropPilot सँग यस बालीका लागि हाल प्रमाणित रोग मोडेल छैन।",
"errModelFailure": "समर्थित रोग मोडेल उपलब्ध थियो, तर विश्लेषण पूरा हुन सकेन। कृपया पुनः प्रयास गर्नुहोस्।",
"noDiagnosis": "निदान छैन",
"statusNotSupported": "समर्थित छैन",
"statusFailed": "असफल",
"downloadSummary": "सारांश डाउनलोड गर्नुहोस्",
"shareSummary": "सारांश साझा गर्नुहोस्",
"summaryCopied": "सारांश क्लिपबोर्डमा कपी भयो",
"analyzeAnotherPhoto": "अर्को फोटो विश्लेषण गर्नुहोस्",
"stepsTitle": "विश्लेषण चरण",
"stepUpload": "फोटो अपलोड हुँदैछ",
"stepQuality": "तस्बिर गुणस्तर जाँचिँदैछ",
"stepRouting": "रोग विशेषज्ञ छानिँदैछ",
"stepAnalysis": "विश्लेषण चलिरहेछ",
"stepVerify": "नतिजा प्रमाणीकरण हुँदैछ",
"supportedCropsNote": "प्रमाणित विशेषज्ञ भएका बालीहरू",
"cropUnknownWeakEvidence": "सही रोग विशेषज्ञ छान्न पर्याप्त प्रमाणसहित CropPilot ले बाली पहिचान गर्न सकेन।",
"unknownCropWhy": "उपलब्ध मोडेलले कमजोर नतिजा दियो, तर तस्बिरले बाली पुष्टि गर्न पर्याप्त प्रमाण दिँदैन।",
"modelOutputs": "मोडेल आउटपुट",
"modelOutputsInterpretation": "पारदर्शिताका लागि कच्चा मोडेल आउटपुट देखाइएको हो; यसलाई प्रमाणित रोग निदान मानिँदैन।",
"rawScoreLabel": "कच्चा स्कोर",
},
"assistant": {
"title": "AI सहायक",
"placeholder": "मूल्य, मौसम, योजनाबारे सोध्नुहोस्…",
"send": "पठाउनुहोस्",
"offline": "सहायक अनुपलब्ध छ। कृपया पछि प्रयास गर्नुहोस्।",
"offlineBackend": "सहायक अनुपलब्ध छ। ब्याकएन्ड चलेको हेर्नुहोस्।",
"sources": "स्रोतहरू",
"newChat": "नयाँ च्याट",
"welcome": "नमस्कार! म **CropPilot AI** हुँ — तपाईंको बुद्धिमान कृषि सहायक। 🌾\n\nम मद्दत गर्न सक्छु:\n\n- **बाली व्यवस्थापन** — छर्ने, सिँचाइ, मल समयतालिका\n- **रोग पहिचान** — बाली रोग पहिचान र उपचार गर्नुहोस्\n- **बजार विश्लेषण** — ताजा मण्डी मूल्य र प्रवृत्ति\n- **सरकारी योजना** — योग्य योजना खोज्नुहोस्\n- **मौसम अन्तर्दृष्टि** — पूर्वानुमान र बालीमा प्रभाव\n\nआज आफ्नो खेतबारे के जान्न चाहनुहुन्छ?",
"welcomeTitle": "CropPilot मा स्वागत छ",
"welcomePreview": "नमस्कार! म CropPilot AI हुँ…",
"newChatTitle": "नयाँ च्याट",
"newChatPreview": "कुराकानी सुरु गर्नुहोस्…",
"promptPaddy": "गहुँ खेतीका उत्कृष्ट अभ्यास",
"promptDisease": "टमाटर पात डढेलो पहिचान गर्नुहोस्",
"promptMarket": "चालु मण्डी मूल्य",
"promptSchemes": "किसानका लागि सरकारी योजना",
"suggestTitle": "खेतीबारे जे पनि सोध्नुहोस् — बाली, रोग, बजार, योजना र थप",
"cardCrop": "बाली सल्लाह",
"cardCropBody": "गहुँ खेतीका उत्कृष्ट अभ्यास",
"cardCropQuery": "गहुँ खेतीका उत्कृष्ट अभ्यास के हुन्?",
"cardDisease": "रोग सहायता",
"cardDiseaseBody": "टमाटरमा पात डढेलो पहिचान र उपचार गर्नुहोस्",
"cardDiseaseQuery": "टमाटर बिरुवामा पात डढेलो कसरी पहिचान र उपचार गर्ने?",
"cardMarket": "बजार प्रश्न",
"cardMarketBody": "धान र गहुँका चालु मण्डी मूल्य",
"cardMarketQuery": "तेलंगानामा धान र गहुँका चालु मण्डी मूल्य के हुन्?",
"cardScheme": "योजना जानकारी",
"cardSchemeBody": "साना किसानका लागि सरकारी योजना",
"cardSchemeQuery": "भारतमा साना किसानका रूपमा म कुन सरकारी योजनाका योग्य हुँ?",
"cardWeather": "मौसम प्रश्न",
"cardWeatherBody": "आगामी मौसम र बालीमा प्रभाव",
"cardWeatherQuery": "आगामी मौसमले मेरा खरीफ बालीमा कस्तो असर गर्छ?",
"cardPlan": "खेत योजना",
"cardPlanBody": "बाली चक्र र माटो व्यवस्थापन सुझाव",
"cardPlanQuery": "आफ्नो खेतका लागि कस्तो बाली चक्र अपनाउने?",
"sideNewChat": "नयाँ च्याट",
"sideSearch": "कुराकानी खोज्नुहोस्…",
"sideNoFound": "कुराकानी भेटिएनन्",
"sideNoYet": "अझै कुराकानी छैनन्",
"sideClose": "साइडबार बन्द गर्नुहोस्",
"sideOpen": "साइडबार खोल्नुहोस्",
"sideDelete": "कुराकानी मेटाउनुहोस्",
"inputDefault": "बाली, रोग, बजार, योजनाबारे सोध्नुहोस्…",
"voiceError": "आवाज त्रुटि",
"voiceUnreachable": "आवाज सेवा पहुँचबाहिर",
"micDenied": "माइक्रोफोन पहुँच अस्वीकृत",
"paletteSearch": "पृष्ठ खोज्नुहोस् वा आदेश लेख्नुहोस्…",
"paletteEmpty": "नतिजा भेटिएनन्।",
"errorTitle": "केही गलत भयो",
"errorFallback": "अप्रत्याशित त्रुटि भयो। कृपया पुनः प्रयास गर्नुहोस्।",
"notFoundTitle": "पृष्ठ भेटिएन",
"notFoundBody": "तपाईंले खोजेको पृष्ठ छैन वा सारिएको छ।",
"goDashboard": "ड्यासबोर्डमा जानुहोस्",
"goHome": "होम जानुहोस्",
"loadingApp": "CropPilot लोड हुँदैछ…",
"themeToggle": "थिम टगल गर्नुहोस्",
"themeCurrent": "हाल थिम: {theme}। {next} का लागि क्लिक गर्नुहोस्",
"themeLight": "उज्यालो",
"themeDark": "गाढा",
"themeSystem": "प्रणाली",
"attachFiles": "फाइल संलग्न गर्नुहोस्",
"attachDocs": "तस्बिर र कागजात",
"takePhoto": "फोटो लिनुहोस्",
"copyResponse": "जवाफ कपी गर्नुहोस्",
"copied": "कपी भयो",
"helpful": "उपयोगी",
"notHelpful": "उपयोगी छैन",
"fileTypeUnsupported": "\"{type}\" फाइल प्रकार समर्थित छैन",
"sourcesCount": "{count} स्रोत",
"sourcesCountPlural": "{count} स्रोत",
},
"maps": {
"loading": "लोड हुँदैछ…",
"searchLocation": "गाउँ, सहर, बजार वा पिन कोड खोज्नुहोस्",
"clearSearch": "खोज सफा गर्नुहोस्",
"searchFailed": "स्थान भेटिएन। अर्को खोज प्रयास गर्नुहोस्।",
"noResults": "मिल्दा स्थान भेटिएनन्।",
"useMyLocation": "मेरो स्थान प्रयोग गर्नुहोस्",
"resetView": "भारत दृश्य रिसेट गर्नुहोस्",
"fullscreen": "पूर्ण-स्क्रिन नक्सा",
"mapLabel": "भारतको CropPilot कृषि नक्सा",
"location": "स्थान",
"locationInsights": "स्थान जानकारी",
"placeUnavailable": "स्थान नाम उपलब्ध छैन — निर्देशांक देखाइएको छ।",
"weather": "मौसम",
"weatherMapTitle": "मौसम नक्सा",
"rainRadar": "वर्षा राडार",
"weatherUnavailable": "मौसम जानकारी अस्थायी अनुपलब्ध छ।",
"humidity": "आर्द्रता",
"wind": "हावा",
"rain": "वर्षा",
"feelsLike": "जस्तो लाग्छ",
"wmoCode": "WMO कोड {code}",
"updatedJustNow": "अहिले अद्यावधिक",
"updatedMinutesAgo": "{count} मि. अघि अद्यावधिक",
"updatedHoursAgo": "{count} घण्टाअघि अद्यावधिक",
"sourceOpenMeteo": "स्रोत: Open-Meteo",
"nearbyMarkets": "नजिकका बजारहरू",
"commodityFilter": "जिन्सअनुसार छान्नुहोस्",
"allCommodities": "सबै जिन्स",
"searchArea": "यस क्षेत्रमा खोज्नुहोस्",
"marketsUnavailable": "नजिक बजार डाटा लोड हुन सकेन।",
"noMappedMarkets": "नजिक नक्सा निर्देशांक भएका बजार भेटिएनन्।",
"noReportedPrice": "यस बजारका लागि अझै दर्ता मूल्य छैन।",
"latestReported": "ताजा दर्ता: {date}",
"sourceAgmarknet": "स्रोत: AGMARKNET",
"quintal": "क्विन्टल",
"unmappedNote": "यहाँ थप {count} बजारका नक्सा निर्देशांक अझै छैनन्; ती बजार बुद्धिमत्तामा सूचीबद्ध छन्।",
"closeDetails": "बजार विवरण बन्द गर्नुहोस्",
"viewMarketIntel": "बजार बुद्धिमत्ता हेर्नुहोस्",
"cropPilotActions": "CropPilot कार्यहरू",
"openMarketIntel": "बजार बुद्धिमत्ता",
"analyzeDisease": "बाली रोग विश्लेषण",
"askAssistant": "CropPilot AI लाई सोध्नुहोस्",
"legendSelected": "छानिएको स्थान",
"legendMarkets": "बजारहरू",
"markets": "बजारहरू",
"toggleMarkets": "बजार मार्कर खोल्नुहोस्/बन्द गर्नुहोस्",
"pickHint": "स्थान छान्न नक्सामा क्लिक गर्नुहोस्",
"collapseSheet": "प्यानल सानो गर्नुहोस्",
"expandSheet": "प्यानल ठूलो गर्नुहोस्",
"geoDenied": "स्थान पहुँच अस्वीकृत। बरु आफ्नो स्थान खोज्न सक्नुहुन्छ।",
"geoUnavailable": "हाल स्थान उपलब्ध छैन। खोज प्रयास गर्नुहोस्।",
"geoTimeout": "स्थान अनुरोध समय सकियो। पुनः प्रयास वा खोज गर्नुहोस्।",
"geoUnsupported": "यस ब्राउजरमा जियोलोकेसन समर्थित छैन। कृपया खोज्नुहोस्।",
"mapUnavailable": "यस डिभाइसमा अन्तरक्रियात्मक नक्सा अनुपलब्ध छ (WebGL बन्द)। खोज र स्थान जानकारी तल चल्छ।",
"agriSnapshot": "कृषि स्न्यापसट",
"commonCrops": "सामान्य बालीहरू",
"soil": "माटो",
"rainfall": "वर्षा",
"seasonRain": "{season} मा {mm} मिमी",
"forecastLabel": "पूर्वानुमान",
"texture": "बनोट",
"organicCarbon": "प्राङ्गारिक कार्बन",
"clay": "चिम्ट्याइलो माटो",
"sand": "बालुवा",
"silt": "पाँगो",
"nitrogen": "नाइट्रोजन",
"sourceSoilGrids": "स्रोत: SoilGrids",
"resolutionM": "रिजोलुसन: {m} मि",
"modelledEstimateNote": "मोडेल अनुमान, प्रयोगशाला माटो परीक्षण होइन",
"modelledBadge": "मोडेल-आधारित",
"soilUnavailable": "यस स्थानका लागि माटो डाटा उपलब्ध छैन।",
"today": "आज",
"last7days": "विगत 7 दिन",
"thisMonth": "यस महिना",
"season": "सिजन",
"reanalysisNote": "पुनर्विश्लेषण/पूर्वानुमान अनुमान, स्टेसन डाटा होइन",
"rainfallUnavailable": "यस स्थानका लागि वर्षा डाटा उपलब्ध छैन।",
"crops": "बालीहरू",
"commonlyTraded": "क्षेत्र मण्डीमा हाल व्यापार जिन्सहरू",
"cropsUnavailable": "यस क्षेत्रका लागि बाली व्यापार डाटा उपलब्ध छैन।",
"suitabilityTitle": "वातावरणीय उपयुक्तता अनुमान",
"water": "जलस्रोत",
"waterUnavailable": "यस स्थानका लागि पानी डाटा उपलब्ध छैन।",
"waterNote": "भूमिगत पानी अवलोकन आवधिक हुन्छन् र जलाशय भण्डार खेत-सिँचाइ उपलब्धता देखाउँदैन।",
"diseaseContext": "रोग सन्दर्भ",
"diseaseUnavailable": "यस क्षेत्रका लागि रोग सन्दर्भ उपलब्ध छैन।",
"selectedLocation": "छानिएको स्थान",
"viewFullMap": "पूरा नक्सा हेर्नुहोस्",
"yourLocation": "तपाईंको स्थान",
},
"markets": {
"title": "बजार बुद्धिमत्ता",
"subtitle": "AGMARKNET बाट ताजा दर्ता मण्डी मूल्य",
"state": "राज्य",
"district": "जिल्ला",
"market": "बजार",
"commodity": "जिन्स",
"days": "दिन",
"latestPrice": "ताजा दर्ता मूल्य: {price} प्रति क्विन्टल",
"arrivalDate": "आगमन मिति: {date}",
"empty": "डाटाबेसमा मिल्दो ताजा दर्ता मूल्य भेटिएन।",
"unavailableTitle": "बजार डाटा हाल अनुपलब्ध छ",
"tryAgain": "पुनः प्रयास गर्नुहोस्",
"signInRequired": "साइन इन आवश्यक",
"signInPrompt": "बजार बुद्धिमत्ता हेर्न साइन इन गर्नुहोस्।",
"signInNeeded": "बजार बुद्धिमत्ता हेर्न साइन इन गर्नुहोस्।",
"offline": "बजार सेवामा पुग्न सकिएन। जडान फर्केपछि भण्डारित अवलोकन देखिनेछन्।",
"loadError": "यो खण्ड लोड गर्दा केही गलत भयो। तपाईंका भण्डारित अवलोकन सुरक्षित छन्।",
"loadErrorShort": "यो खण्ड लोड गर्दा केही गलत भयो।",
"allStates": "सबै राज्यहरू",
"allDistricts": "सबै जिल्लाहरू",
"selectStateFirst": "पहिले राज्य छान्नुहोस्",
"allMarkets": "सबै बजारहरू",
"selectCommodity": "जिन्स छान्नुहोस्",
"allVarieties": "सबै जातहरू",
"allGrades": "सबै ग्रेडहरू",
"variety": "जात",
"grade": "ग्रेड",
"statesReporting": "रिपोर्टिङ राज्यहरू",
"marketsReporting": "रिपोर्टिङ बजारहरू",
"commoditiesReported": "दर्ता जिन्सहरू",
"latestObservation": "ताजा अवलोकन",
"storedObservations": "भण्डारित अवलोकन देखाइँदैछ",
"storedObservationsBody": "यस छनोटका लागि स्रोतले हाल अवलोकन प्रकाशित गरेको छैन। तलका मान ताजा भण्डारित रिपोर्ट हुन्, नयाँ मूल्य होइनन्।",
"noRecentPrice": "हाल दर्ता मूल्य छैन",
"emptyHint": "अर्को राज्य, जिल्ला, जिन्स वा बजार प्रयास गर्नुहोस्। अर्को स्रोत प्रकाशनपछि नयाँ रिपोर्ट यहाँ देखिनेछन्।",
"selectionSummary": "छनोट सारांश",
"reportedMarkets": "दर्ता बजारहरू",
"observationsInTable": "तालिकामा अवलोकन",
"trendPoints": "प्रवृत्ति बिन्दु",
"comingLater": "पछि आउँदैछ",
"comingLaterBody": "मूल्य पूर्वानुमान र बिक्री सिफारिस अझै यस दृश्यको भाग होइनन्। यहाँ दर्ता अवलोकन मात्र देखाइएको छ।",
"searchStates": "राज्य खोज्नुहोस्…",
"searchDistricts": "जिल्ला खोज्नुहोस्…",
"searchMarkets": "बजार खोज्नुहोस्…",
"noMatchState": "मिल्दो राज्य छैन।",
"noMatchDistrict": "मिल्दो जिल्ला छैन।",
"noMatchMarket": "मिल्दो बजार छैन।",
"tableSearch": "लोड नतिजामा खोज्नुहोस्…",
"thMin": "न्यून रु",
"thMax": "अधिक रु",
"thModal": "मोडल रु",
"thArrivals": "आगमन",
"thObserved": "अवलोकन",
"showingCount": "{from}–{to} मध्ये {total}",
"prevPage": "अघिल्लो पृष्ठ",
"nextPage": "अर्को पृष्ठ",
"priceRs": "रु{value}",
"minMaxLine": "न्यून रु{min} · अधिक रु{max}",
"arrivalsLine": "आगमन: {value}",
"freshNone": "हाल अवलोकन उपलब्ध छैन",
"freshLatest": "ताजा दर्ता: {date}",
"freshStale": "डाटा ढिलो हुन सक्छ",
"sourceLabel": "स्रोत: {name}",
"sourceBody": "दर्ता मण्डी मूल्य बजारले प्रकाशित अवलोकन हुन् र ढिलो आउन सक्छन्। ती भावी मूल्यको ग्यारेन्टी होइनन्।",
"sourceResource": "स्रोत: {id}",
"cmpNoData": "तुलना उपलब्ध छैन",
"cmpNoDataBody": "यस छनोटका लागि अझै दर्ता मूल्य छैन।",
"cmpTitle": "बजार तुलना",
"cmpBody": "मिल्दो जात, ग्रेड र एकाइ भएका पङ्क्ति मात्र तुलना गरिन्छ। मूल्य प्रति बजार ताजा दर्ता अवलोकन हुन्।",
"cmpMinMax": "न्यूनदेखि अधिक रु",
"histNoData": "मूल्य इतिहास छैन",
"histNoDataBody": "छानिएको बजार र जिन्सका लागि यस अवधिमा दर्ता अवलोकन छैन।",
"histTitle": "दर्ता मोडल मूल्य प्रवृत्ति",
"histUnit": "Rs प्रति {unit}",
"histModal": "मोडल",
"histMax": "अधिक",
"histMin": "न्यून",
"histCount": "{count} अवलोकन",
"histObserved": "{label} मा अवलोकन",
"cmpUnspecified": "अनिश्चित जात र ग्रेड",
},
"schemes": {
"title": "सरकारी योजना",
"subtitle": "कृषि योजना, अनुदान र कल्याण कार्यक्रम खोज्नुहोस् र आवेदन दिनुहोस्",
"search": "नाम, विवरण, ट्यागबाट योजना खोज्नुहोस्…",
"all": "सबै",
"noFound": "योजना भेटिएनन्",
"noFoundBody": "आफ्नो खोज वा फिल्टर बदल्नुहोस्",
"viewDetail": "विवरण हेर्नुहोस्",
"eligibility": "योग्यता",
"benefits": "लाभ",
"howToApply": "आवेदन कसरी दिने",
"close": "बन्द गर्नुहोस्",
"moreDetails": "थप विवरण",
"applicationProcess": "आवेदन प्रक्रिया:",
"funding": "कोष:",
"checkEligibility": "योग्यता हेर्नुहोस्",
"ministry": "मन्त्रालय:",
"eligibilityCriteria": "योग्यता मापदण्ड",
"requiredDocuments": "आवश्यक कागजात",
"active": "सक्रिय",
"inactive": "निष्क्रिय",
"applyNow": "अहिले आवेदन दिनुहोस्",
},
"analytics": {
"title": "विश्लेषण",
"subtitle": "आफ्नो खेत प्रदर्शनको व्यापक अन्तर्दृष्टि",
"tabRevenue": "आम्दानी",
"tabYield": "उत्पादन",
"tabCropHealth": "बाली स्वास्थ्य",
"tabWater": "पानी प्रयोग",
"tabFertilizer": "मल प्रयोग",
"tabMarket": "बजार विश्लेषण",
"statRevenue": "कुल आम्दानी",
"statYield": "औसत उत्पादन/हे",
"statHealth": "स्वास्थ्य स्कोर",
"statWater": "पानी दक्षता",
"rangeCustom": "अनुकूल",
"chRevenueMonthly": "मासिक आम्दानी",
"chRevenueByCrop": "बालीअनुसार आम्दानी",
"chRevenueCumulative": "सञ्चित आम्दानी",
"chYieldByCrop": "बालीअनुसार उत्पादन",
"chYieldTrend": "उत्पादन प्रवृत्ति",
"chYieldVsTarget": "उत्पादन वि. लक्ष्य",
"chYieldPerHa": "प्रति हेक्टर उत्पादन",
"chYieldTopBottom": "उत्कृष्ट र कमजोर बालीहरू",
"chHealthOverall": "समग्र स्वास्थ्य",
"chHealthRadar": "स्वास्थ्य मेट्रिक्स राडार",
"chHealthTrend": "स्वास्थ्य स्कोर प्रवृत्ति",
"chHealthByPlot": "प्लटअनुसार स्वास्थ्य",
"chHealthTimeline": "स्वास्थ्य सूचना समयरेखा",
"chPriceTrends": "मूल्य प्रवृत्ति - शीर्ष 5 जिन्स",
"chPriceHeatmap": "मूल्य हिटम्याप - जिन्स वि. महिना",
"chBestTimes": "उत्तम बिक्री समय",
"chTrade": "निर्यात / आयात विश्लेषण",
"chVolume": "व्यापार परिमाण",
"chInsights": "AI अन्तर्दृष्टि",
"chWaterDaily": "वर्षासहित दैनिक पानी प्रयोग",
"chWaterByCrop": "बालीअनुसार पानी प्रयोग",
"chWaterEff": "पानी दक्षता (प्रति किलो उत्पादन लिटर)",
"chWaterSave": "पानी बचत सुझाव",
"chWaterSchedule": "तालिका सिफारिस",
"chFertBreakdown": "मल प्रकार विभाजन",
"chFertCost": "सिफारिस वि. लागत विश्लेषण",
"chFertNPK": "समयसँग N / P / K प्रयोग",
"statVolatility": "मूल्य अस्थिरता सूचकांक",
"statGainers": "शीर्ष वृद्धि",
"statLosers": "शीर्ष गिरावट",
"statVolume": "कुल परिमाण",
"trendLow": "कम",
"thCommodity": "जिन्स",
"expShort": "नि",
"impShort": "आ",
},
"voice": {
"start": "आवाज इनपुट सुरु गर्नुहोस्",
"stop": "रोक्नुहोस्",
"listening": "सुन्दैछ…",
"transcribing": "लेखिँदैछ…",
"thinking": "सोच्दैछ…",
"speaking": "बोल्दैछ…",
"unavailable": "यस डिभाइसमा आवाज इनपुट अनुपलब्ध छ।",
"audioUnavailable": "यस भाषाका लागि बोलिएको आउटपुट अनुपलब्ध छ।",
"recording": "रेकर्ड हुँदैछ…",
},
"errors": {
"network": "नेटवर्क त्रुटि। आफ्नो जडान हेरेर पुनः प्रयास गर्नुहोस्।",
"unauthorized": "सत्र सकियो। कृपया पुनः साइन इन गर्नुहोस्।",
"notFound": "भेटिएन।",
},
"crops": {
"rice": "चामल",
"paddy": "धान",
"wheat": "गहुँ",
"cotton": "कपास",
"maize": "मकै",
"sugarcane": "उखु",
"tomato": "गोलभेँडा",
"potato": "आलु",
"onion": "प्याज",
"soybean": "भटमास",
"groundnut": "बदाम",
"chilli": "खुर्सानी",
},
}

emit("ne", T)
