# Complete Punjabi (pa) catalog. Run from frontend/: python scripts/tr-pa.py
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emit_locale import emit

T = {
"common": {
"appName": "CropPilot",
"loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…",
"retry": "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
"cancel": "ਰੱਦ ਕਰੋ",
"close": "ਬੰਦ ਕਰੋ",
"save": "ਸੰਭਾਲੋ",
"search": "ਖੋਜੋ",
"noData": "ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
"errorGeneric": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"prevSlide": "ਪਿਛਲੀ ਸਲਾਈਡ",
"nextSlide": "ਅਗਲੀ ਸਲਾਈਡ",
"menu": "ਮੋਬਾਈਲ ਮੈਨੂ ਖੋਲ੍ਹੋ/ਬੰਦ ਕਰੋ",
"language": "ਭਾਸ਼ਾ",
"selectLanguage": "ਭਾਸ਼ਾ ਚੁਣੋ",
"commandPalette": "ਕਮਾਂਡ ਪੈਲੇਟ",
},
"navigation": {
"dashboard": "ਡੈਸ਼ਬੋਰਡ",
"markets": "ਮੰਡੀਆਂ",
"weather": "ਮੌਸਮ",
"disease": "ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ",
"schemes": "ਸਕੀਮਾਂ",
"analytics": "ਵਿਸ਼ਲੇਸ਼ਣ",
"maps": "ਨਕਸ਼ੇ",
"assistant": "AI ਸਹਾਇਕ",
},
"auth": {
"signIn": "ਸਾਈਨ ਇਨ ਕਰੋ",
"signOut": "ਸਾਈਨ ਆਊਟ ਕਰੋ",
"welcomeBack": "ਮੁੜ ਜੀ ਆਇਆਂ ਨੂੰ",
"signInSubtitle": "ਆਪਣੇ CropPilot ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ",
"email": "ਈਮੇਲ",
"password": "ਪਾਸਵਰਡ",
"enterPassword": "ਆਪਣਾ ਪਾਸਵਰਡ ਲਿਖੋ",
"rememberMe": "ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ",
"signingIn": "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ…",
"signInBtn": "ਸਾਈਨ ਇਨ",
"noAccount": "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
"registerLink": "ਰਜਿਸਟਰ ਕਰੋ",
"emailRequired": "ਈਮੇਲ ਜ਼ਰੂਰੀ ਹੈ",
"emailInvalid": "ਗਲਤ ਈਮੇਲ ਪਤਾ",
"passwordRequired": "ਪਾਸਵਰਡ ਜ਼ਰੂਰੀ ਹੈ",
"passwordMin": "ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਵੇ",
"invalidCredentials": "ਗਲਤ ਜਾਣਕਾਰੀ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"createAccount": "ਖਾਤਾ ਬਣਾਓ",
"registerSubtitle": "CropPilot ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ ਅਤੇ ਸਮਾਰਟ ਖੇਤੀ ਸ਼ੁਰੂ ਕਰੋ",
"fullName": "ਪੂਰਾ ਨਾਮ",
"fullNamePlaceholder": "ਆਪਣਾ ਪੂਰਾ ਨਾਮ",
"phone": "ਫੋਨ ਨੰਬਰ",
"selectState": "ਰਾਜ ਚੁਣੋ",
"selectDistrict": "ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
"createPassword": "ਪਾਸਵਰਡ ਬਣਾਓ",
"confirmPassword": "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
"confirmPasswordPlaceholder": "ਆਪਣੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
"registerBtn": "ਰਜਿਸਟਰ ਕਰੋ",
"registering": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਹੋ ਰਹੀ ਹੈ…",
"haveAccount": "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
"signInLink": "ਸਾਈਨ ਇਨ ਕਰੋ",
"nameRequired": "ਨਾਮ ਜ਼ਰੂਰੀ ਹੈ",
"phoneInvalid": "ਗਲਤ ਫੋਨ ਨੰਬਰ",
"phoneLong": "ਫੋਨ ਨੰਬਰ ਬਹੁਤ ਲੰਬਾ ਹੈ",
"selectStateRequired": "ਕਿਰਪਾ ਕਰਕੇ ਰਾਜ ਚੁਣੋ",
"selectDistrictRequired": "ਕਿਰਪਾ ਕਰਕੇ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
"passwordMismatch": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
"showPassword": "ਪਾਸਵਰਡ ਦਿਖਾਓ",
"hidePassword": "ਪਾਸਵਰਡ ਲੁਕਾਓ",
"nameMin": "ਪੂਰਾ ਨਾਮ ਘੱਟੋ-ਘੱਟ 2 ਅੱਖਰਾਂ ਦਾ ਹੋਵੇ",
"phoneMin": "ਫੋਨ ਨੰਬਰ ਘੱਟੋ-ਘੱਟ 10 ਅੰਕਾਂ ਦਾ ਹੋਵੇ",
"confirmRequired": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
"acceptTerms": "ਤੁਹਾਨੂੰ ਨਿਯਮ ਵ ਸ਼ਰਤਾਂ ਸਵੀਕਾਰ ਕਰਨੀਆਂ ਹੋਣਗੀਆਂ",
"registerFailed": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"acceptPrefix": "ਮੈਂ ਸਵੀਕਾਰ ਕਰਦਾ ਹਾਂ",
"termsService": "ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ",
"termsAnd": "ਅਤੇ",
"privacyPolicy": "ਪਰਦੇਦਾਰੀ ਨੀਤੀ",
"creatingAccount": "ਖਾਤਾ ਬਣ ਰਿਹਾ ਹੈ…",
"authLayoutTitle": "CropPilot ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
"authLayoutBody": "ਆਧੁਨਿਕ ਖੇਤੀ ਲਈ ਓਪਨ-ਸੋਰਸ ਪਲੇਟਫਾਰਮ। ਡੈਸ਼ਬੋਰਡ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
},
"landing": {
"badge": "ਮੁਫ਼ਤ ਅਤੇ ਓਪਨ-ਸੋਰਸ ਸਾਫਟਵੇਅਰ",
"tagline": "ਸਿਆਣੀ ਖੇਤੀ ਲਈ ਓਪਨ-ਸੋਰਸ ਔਜ਼ਾਰ।",
"heroBody": "ਫ਼ਸਲ ਦੀ ਸਿਹਤ, ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ, ਮੌਸਮੀ ਜਾਣਕਾਰੀ ਅਤੇ ਦਰਜ ਮੰਡੀ ਬਾਜ਼ਾਰ ਭਾਅ ਲਈ ਕਿਸਾਨ-ਕੇਂਦਰਿਤ ਪਲੇਟਫਾਰਮ।",
"openApp": "CropPilot ਖੋਲ੍ਹੋ",
"viewGithub": "GitHub ਉੱਤੇ ਵੇਖੋ",
"featuresTitle": "ਤੁਸੀਂ ਕੀ ਕਰ ਸਕਦੇ ਹੋ",
"featCrop": "ਫ਼ਸਲ ਦੀ ਸਿਹਤ",
"featCropBody": "ਫ਼ਸਲ ਦੀ ਹਾਲਤ ਅਤੇ ਸਬੰਧਤ ਖੇਤ ਜਾਣਕਾਰੀ ਵੇਖੋ।",
"featDisease": "ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ",
"featDiseaseBody": "ਸਹਿਯੋਗੀ ਬਿਮਾਰੀ ਪਛਾਣ ਪ੍ਰਕਿਰਿਆਵਾਂ ਲਈ ਫ਼ਸਲ ਤਸਵੀਰਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ।",
"featWeather": "ਮੌਸਮੀ ਜਾਣਕਾਰੀ",
"featWeatherBody": "ਖੇਤੀ ਫੈਸਲਿਆਂ ਲਈ ਲਾਭਦਾਇਕ ਮੌਸਮੀ ਜਾਣਕਾਰੀ ਵੇਖੋ।",
"featMarket": "ਮੰਡੀ ਜਾਣਕਾਰੀ",
"featMarketBody": "AGMARKNET ਤੋਂ ਸਰਕਾਰੀ ਖੁੱਲ੍ਹੇ ਡਾਟੇ ਰਾਹੀਂ ਦਰਜ ਮੰਡੀ ਭਾਅ ਵੇਖੋ।",
"appTitle": "ਐਪਲੀਕੇਸ਼ਨ",
"appBody": "ਖੇਤ ਝਲਕ, ਮੌਸਮ, ਫ਼ਸਲ ਸਿਹਤ ਅਤੇ ਮੰਡੀ ਹਿੱਸਿਆਂ ਨਾਲ CropPilot ਡੈਸ਼ਬੋਰਡ।",
"appCaption": "ਨਮੂਨਾ ਡਾਟੇ ਨਾਲ ਚੱਲਦਾ CropPilot ਡੈਸ਼ਬੋਰਡ।",
"appAlt": "ਨਮੂਨਾ ਡਾਟੇ ਨਾਲ ਖੇਤ ਝਲਕ, ਮੌਸਮ, ਫ਼ਸਲ ਸਿਹਤ ਅਤੇ ਮੰਡੀ ਹਿੱਸੇ ਦਿਖਾਉਂਦਾ CropPilot ਡੈਸ਼ਬੋਰਡ ਸਕ੍ਰੀਨਸ਼ਾਟ",
"marketTitle": "ਮੰਡੀ ਜਾਣਕਾਰੀ",
"marketBody": "ਰਾਜ, ਜ਼ਿਲ੍ਹਾ, ਮੰਡੀ, ਜਿਨਸ, ਕਿਸਮ, ਗ੍ਰੇਡ ਅਤੇ ਮਿਆਦ ਅਨੁਸਾਰ ਤਾਜ਼ਾ ਦਰਜ ਮੰਡੀ ਭਾਅ ਵੇਖੋ, ਨਾਲੇ ਰੁਝਾਨ ਅਤੇ ਮੰਡੀ ਤੁਲਨਾ।",
"marketSource": "ਸਰੋਤ: ਸਰਕਾਰੀ ਖੁੱਲ੍ਹੇ ਡਾਟੇ ਰਾਹੀਂ AGMARKNET। ਕੀਮਤਾਂ ਨਿਰੀਖਣ ਮਿਤੀਆਂ ਨਾਲ ਦਰਜ ਨਿਰੀਖਣ ਹਨ, ਮੌਜੂਦਾ ਬਾਜ਼ਾਰ ਭਾਅ ਵਜੋਂ ਕਦੇ ਪੇਸ਼ ਨਹੀਂ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ।",
"marketCta": "ਮੰਡੀ ਭਾਅ ਵੇਖੋ",
"whyTitle": "ਕਿਸਾਨਾਂ ਲਈ ਬਣਾਇਆ। ਖੁੱਲ੍ਹੇਪਣ ਨਾਲ ਬਣਾਇਆ।",
"whyBody": "CropPilot ਮੁਫ਼ਤ ਅਤੇ ਓਪਨ-ਸੋਰਸ ਸਾਫਟਵੇਅਰ ਹੈ ਜੋ ਖੇਤੀ ਔਜ਼ਾਰ ਅਤੇ ਜਾਣਕਾਰੀ ਸੌਖੀ ਬਣਾਉਂਦਾ ਹੈ। ਇਹ MIT ਲਾਇਸੰਸ ਉੱਤੇ ਚੱਲਦਾ ਹੈ ਅਤੇ ਵਿਕਾਸ GitHub ਉੱਤੇ ਪਾਰਦਰਸ਼ੀ ਹੁੰਦਾ ਹੈ।",
"archTitle": "ਆਰਕੀਟੈਕਚਰ",
"archBody": "ਖੇਤ ਅਤੇ ਸਥਾਨਕ ਡਾਟੇ ਲਈ PostgreSQL ਅਤੇ PostGIS, ਪਿਛੋਕੜ ਕੰਮਾਂ ਲਈ Celery ਵਰਕਰ ਅਤੇ ਬਿਮਾਰੀ ਪਛਾਣ ਲਈ PyTorch ਵਿਜ਼ਨ ਮਾਡਲਾਂ ਨਾਲ FastAPI ਸੇਵਾ ਉੱਤੇ ਅਧਾਰਤ Next.js ਫਰੰਟਐਂਡ। ਸਭ ਕੁਝ Docker Compose ਨਾਲ ਸਥਾਨਕ ਚੱਲਦਾ ਹੈ।",
"ossTitle": "GitHub ਉੱਤੇ ਓਪਨ ਸੋਰਸ",
"ossBody": "ਕੋਡ ਵੇਖੋ, ਮਸਲੇ ਦਰਜ ਕਰੋ ਅਤੇ ਸੁਧਾਰਾਂ ਵਿੱਚ ਯੋਗਦਾਨ ਦਿਓ। MIT ਲਾਇਸੰਸਸ਼ੁਦਾ।",
"footerTag": "ਓਪਨ-ਸੋਰਸ ਖੇਤੀ ਪਲੇਟਫਾਰਮ।",
"footerDocs": "ਦਸਤਾਵੇਜ਼",
"navFeatures": "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
"navArchitecture": "ਆਰਕੀਟੈਕਚਰ",
"toggleMenu": "ਮੈਨੂ ਖੋਲ੍ਹੋ/ਬੰਦ ਕਰੋ",
"footerLabel": "ਫੁੱਟਰ",
},
"dashboard": {
"welcomeBack": "ਮੁੜ ਜੀ ਆਇਆਂ ਨੂੰ, {name}",
"farmer": "ਕਿਸਾਨ",
"selectFarm": "ਖੇਤ ਚੁਣੋ",
"allFarms": "ਸਾਰੇ ਖੇਤ",
"wFarmOverview": "ਖੇਤ ਝਲਕ",
"wWeather": "ਅੱਜ ਦਾ ਮੌਸਮ",
"wCropHealth": "ਫ਼ਸਲ ਸਿਹਤ",
"wDiseaseAlerts": "ਬਿਮਾਰੀ ਸੂਚਨਾਵਾਂ",
"wRevenue": "ਆਮਦਨ",
"wExpenses": "ਖਰਚ",
"wNetProfit": "ਸ਼ੁੱਧ ਲਾਭ",
"wYield": "ਝਾੜ",
"wMarketTrends": "ਮੰਡੀ ਰੁਝਾਨ",
"wSchemes": "ਸਕੀਮ ਸਿਫਾਰਸ਼ਾਂ",
"wNotifications": "ਸੂਚਨਾਵਾਂ",
"wQuickActions": "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
"vsLastMonth": "ਪਿਛਲੇ ਮਹੀਨੇ ਦੇ ਮੁਕਾਬਲੇ",
"totalYield": "ਕੁੱਲ ਝਾੜ",
"perHectare": "ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ",
"noAlerts": "ਕੋਈ ਸਰਗਰਮ ਬਿਮਾਰੀ ਸੂਚਨਾ ਨਹੀਂ",
"cropsHealthy": "ਤੁਹਾਡੀਆਂ ਫ਼ਸਲਾਂ ਸਿਹਤਮੰਦ ਹਨ",
"noNotifications": "ਸੂਚਨਾਵਾਂ ਨਹੀਂ",
"qaScan": "ਫ਼ਸਲਾਂ ਸਕੈਨ ਕਰੋ",
"qaWeather": "ਮੌਸਮ ਵੇਖੋ",
"qaMarkets": "ਮੰਡੀਆਂ ਵੇਖੋ",
"qaAssistant": "AI ਸਹਾਇਕ",
"statFarms": "ਕੁੱਲ ਖੇਤ",
"statArea": "ਕੁੱਲ ਰਕਬਾ",
"statPlots": "ਸਰਗਰਮ ਪਲਾਟ",
"statSeason": "ਮੌਜੂਦਾ ਸੀਜ਼ਨ",
"notifMarkRead": "ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਨਿਸ਼ਾਨ ਲਗਾਓ",
"marginLabel": "ਮਾਰਜਨ:",
},
"weather": {
"title": "ਮੌਸਮ",
"subtitle": "ਤੁਹਾਡੇ ਖੇਤ ਲਈ ਤਾਜ਼ਾ ਮੌਸਮ ਡਾਟਾ ਅਤੇ ਭਵਿੱਖਬਾਣੀ",
"searchLocation": "ਸਥਾਨ ਖੋਜੋ…",
"noLocations": "ਸਥਾਨ ਨਹੀਂ ਮਿਲੇ",
"hourly": "ਘੰਟੇਵਾਰ ਭਵਿੱਖਬਾਣੀ",
"details": "ਮੌਸਮ ਵੇਰਵੇ",
"rainProbability": "ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ",
"windSpeed": "ਹਵਾ ਦੀ ਗਤੀ",
"humidity": "ਨਮੀ",
"uvIndex": "UV ਸੂਚਕ",
"pressure": "ਦਬਾਅ",
"visibility": "ਦਿੱਖ",
"weekly": "7-ਦਿਨਾ ਭਵਿੱਖਬਾਣੀ",
"feelsLike": "{temp}° ਜਿਹਾ ਲੱਗਦਾ ਹੈ",
"highShort": "ਵੱਧ: {temp}°",
"lowShort": "ਘੱਟ: {temp}°",
},
"disease": {
"title": "ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ",
"subtitle": "AI ਨਾਲ ਚੱਲਣ ਵਾਲੀ ਬਿਮਾਰੀ ਜਾਂਚ ਲਈ ਫ਼ਸਲ ਤਸਵੀਰਾਂ ਅੱਪਲੋਡ ਕਰੋ ਜਾਂ ਲਓ",
"newDetection": "ਨਵੀਂ ਜਾਂਚ",
"analyzing": "ਤੁਹਾਡੀ ਫ਼ਸਲ ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ…",
"analyzingBody": "AI ਬਿਮਾਰੀ ਨਮੂਨੇ ਸਕੈਨ ਕਰ ਰਿਹਾ ਹੈ",
"readyTitle": "ਜਾਂਚ ਲਈ ਤਿਆਰ",
"readyBody": "ਤੁਰੰਤ AI ਬਿਮਾਰੀ ਪਛਾਣ ਅਤੇ ਇਲਾਜ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਪ੍ਰਭਾਵਿਤ ਫ਼ਸਲ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ ਜਾਂ ਲਓ",
"confidence": "AI ਭਰੋਸਾ",
"cameraTitle": "ਕੈਮਰਾ ਕੈਪਚਰ",
"cameraBody": "ਪ੍ਰਭਾਵਿਤ ਫ਼ਸਲ ਦੀ ਫੋਟੋ ਲਓ",
"cameraHint": "ਪ੍ਰਭਾਵਿਤ ਪੱਤੇ ਜਾਂ ਫਲ ਫਰੇਮ ਵਿੱਚ ਰੱਖੋ",
"activateCamera": "ਕੈਮਰਾ ਚਾਲੂ ਕਰੋ",
"capture": "ਕੈਪਚਰ ਕਰੋ",
"retake": "ਮੁੜ ਲਓ",
"uploadTitle": "ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ",
"uploadHint": "ਡਰੈਗ ਅਤੇ ਡਰਾਪ ਜਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ",
"dropHint": "ਅੱਪਲੋਡ ਲਈ ਡਰੈਗ ਤੇ ਡਰਾਪ ਜਾਂ ਕਲਿੱਕ ਕਰੋ",
"dropFormats": "JPG, PNG, WEBP 10MB ਤੱਕ",
"changeImage": "ਤਸਵੀਰ ਬਦਲੋ",
"fileTooBig": "ਫਾਈਲ ਦਾ ਆਕਾਰ 10MB ਤੋਂ ਘੱਟ ਹੋਵੇ।",
"resultTitle": "ਜਾਂਚ ਨਤੀਜਾ",
"detectedDisease": "ਮਿਲੀ ਬਿਮਾਰੀ",
"confidenceScore": "ਭਰੋਸਾ ਸਕੋਰ",
"treatmentAvailable": "ਇਲਾਜ ਸਿਫਾਰਸ਼ ਉਪਲਬਧ",
"aiAnalysis": "AI ਨਾਲ ਚੱਲਦਾ ਵਿਸ਼ਲੇਸ਼ਣ",
"symptoms": "ਲੱਛਣ",
"recommendedActions": "ਸਿਫਾਰਸ਼ੀ ਕਾਰਵਾਈਆਂ",
"preventiveMeasures": "ਰੋਕਥਾਮ ਉਪਾਅ",
"historyTitle": "ਜਾਂਚ ਇਤਿਹਾਸ",
"thDate": "ਮਿਤੀ",
"thCrop": "ਫ਼ਸਲ",
"thDisease": "ਬਿਮਾਰੀ",
"thConfidence": "ਭਰੋਸਾ",
"thStatus": "ਸਥਿਤੀ",
"sevLow": "ਘੱਟ",
"sevModerate": "ਦਰਮਿਆਨਾ",
"sevHigh": "ਵੱਧ",
"sevCritical": "ਗੰਭੀਰ",
"pastDetections": "{count} ਪਿਛਲੀਆਂ ਜਾਂਚਾਂ",
"searchHistory": "ਫ਼ਸਲ ਜਾਂ ਬਿਮਾਰੀ ਨਾਲ ਖੋਜੋ…",
"noDetections": "ਜਾਂਚਾਂ ਨਹੀਂ ਮਿਲੀਆਂ",
"stageCheckingPhoto": "ਫੋਟੋ ਗੁਣਵੱਤਾ ਜਾਂਚੀ ਜਾ ਰਹੀ ਹੈ…",
"stageAnalyzing": "ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ…",
"cropHintLabel": "ਫ਼ਸਲ (ਵਿਕਲਪਿਕ - ਸਹੀ ਮਾਹਰ ਚੁਣਨ ਵਿੱਚ ਮਦਦਗਾਰ)",
"cropHintAuto": "ਆਟੋ (ਕੋਈ ਸੰਕੇਤ ਨਹੀਂ)",
"unknownCrop": "ਅਣਜਾਣ ਫ਼ਸਲ",
"uncertainTitle": "CropPilot ਸਮੱਸਿਆ ਦੀ ਪੱਕੀ ਪਛਾਣ ਨਾ ਕਰ ਸਕਿਆ",
"uncertainBody": "ਜਾਂਚ ਲਈ ਤਸਵੀਰ ਸਬੂਤ ਨਾਕਾਫੀ ਸਨ। ਹੇਠਲੇ ਵਿਕਲਪ ਅੰਦਾਜ਼ੇ ਹਨ, ਜਾਂਚ ਨਹੀਂ।",
"possibleCauses": "ਸੰਭਾਵਿਤ ਵਿਕਲਪ",
"analyzeAnotherHint": "ਚੰਗੀ ਰੌਸ਼ਨੀ ਵਿੱਚ ਇੱਕ ਪ੍ਰਭਾਵਿਤ ਪੱਤੇ ਦੀ ਨਜ਼ਦੀਕੀ ਫੋਟੋ ਨਾਲ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"supportedCrops": "ਪ੍ਰਮਾਣਿਤ ਮਾਹਰ ਵਾਲੀਆਂ ਫ਼ਸਲਾਂ",
"capabilitiesOffline": "ਜਾਂਚ ਸੇਵਾ ਸੂਚੀ ਤੱਕ ਪਹੁੰਚ ਨਾ ਹੋ ਸਕੀ। ਫਿਰ ਵੀ ਅੱਪਲੋਡ ਅਜ਼ਮਾ ਸਕਦੇ ਹੋ।",
"bandHigh": "ਵੱਧ",
"bandMedium": "ਦਰਮਿਆਨਾ",
"bandLow": "ਘੱਟ",
"bandUnverified": "ਅਪ੍ਰਮਾਣਿਤ ਸਕੋਰ",
"bandUnknown": "ਅਣਜਾਣ",
"statusDiagnosed": "ਸੰਭਾਵਿਤ ਜਾਂਚ",
"statusProbable": "ਸੰਭਾਵਿਤ - ਤਸਦੀਕ ਲੋੜੀਂਦੀ",
"statusUncertain": "ਅਨਿਸ਼ਚਿਤ",
"statusInsufficientImage": "ਫੋਟੋ ਬੇਕਾਰ",
"statusUnsupportedCrop": "ਫ਼ਸਲ ਅਜੇ ਸਹਿਯੋਗੀ ਨਹੀਂ",
"statusError": "ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਫਲ",
"uncalibratedScore": "ਮਾਡਲ ਸਕੋਰ (ਅਣਕੈਲੀਬਰੇਟਿਡ)",
"uncalibratedScoreHint": "ਕੱਚਾ ਮਾਡਲ ਆਉਟਪੁੱਟ, ਕੈਲੀਬਰੇਟਿਡ ਸੰਭਾਵਨਾ ਨਹੀਂ।",
"uploadedPhoto": "ਅੱਪਲੋਡ ਕੀਤੀ ਫੋਟੋ",
"evidenceTitle": "ਵਿਸ਼ਲੇਸ਼ਣ ਵੇਰਵੇ",
"routingMode": "ਰੂਟਿੰਗ",
"modelsUsed": "ਵਰਤੇ ਮਾਡਲ",
"fieldValidation": "ਖੇਤ ਤਸਦੀਕ",
"imageQuality": "ਤਸਵੀਰ ਗੁਣਵੱਤਾ",
"latencyLabel": "ਵਿਸ਼ਲੇਸ਼ਣ ਸਮਾਂ",
"researchBadge": "ਖੋਜ ਮਾਡਲ",
"notVerified": "ਪ੍ਰਮਾਣਿਤ ਨਹੀਂ",
"guidanceFor": "ਸੇਧ:",
"guidanceSource": "ਸਰੋਤ",
"similarConditions": "ਮਿਲਦੀਆਂ ਹਾਲਤਾਂ",
"noGuidance": "CropPilot ਕੋਲ ਇਸ ਜਾਂਚ ਲਈ ਅਜੇ ਪ੍ਰਮਾਣਿਤ ਸੇਧ ਨਹੀਂ।",
"imageNotRetained": "ਸਿਰਫ਼ ਸੈਸ਼ਨ ਇਤਿਹਾਸ - ਤਸਵੀਰਾਂ ਸਾਂਭੀਆਂ ਨਹੀਂ ਜਾਂਦੀਆਂ।",
"errNetwork": "ਨੈੱਟਵਰਕ ਗਲਤੀ। ਆਪਣਾ ਕੁਨੈਕਸ਼ਨ ਵੇਖੋ ਅਤੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"errTooLarge": "ਤਸਵੀਰ ਬਹੁਤ ਵੱਡੀ ਹੈ। 10 MB ਤੋਂ ਛੋਟੀ ਫੋਟੋ ਵਰਤੋ।",
"errPoorQuality": "ਫੋਟੋ ਗੁਣਵੱਤਾ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਬਹੁਤ ਖਰਾਬ ਹੈ। ਇੱਕ ਪ੍ਰਭਾਵਿਤ ਪੱਤੇ ਦੀ ਨਜ਼ਦੀਕੀ ਫੋਟੋ ਲਓ।",
"errUnsupportedCrop": "CropPilot ਕੋਲ ਉਸ ਫ਼ਸਲ ਲਈ ਅਜੇ ਪ੍ਰਮਾਣਿਤ ਮਾਹਰ ਨਹੀਂ।",
"errInvalid": "ਉਹ ਫਾਈਲ ਤਸਵੀਰ ਵਜੋਂ ਪੜ੍ਹੀ ਨਾ ਜਾ ਸਕੀ। JPG ਜਾਂ PNG ਫੋਟੋ ਅਜ਼ਮਾਓ।",
"errNoModel": "ਇਸ ਵੇਲੇ ਕੋਈ ਪ੍ਰਮਾਣਿਤ ਜਾਂਚ ਮਾਡਲ ਉਪਲਬਧ ਨਹੀਂ। ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"errServer": "ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਫਲ। ਸਪੱਸ਼ਟ ਫੋਟੋ ਨਾਲ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"analysisIncomplete": "ਵਿਸ਼ਲੇਸ਼ਣ ਅਧੂਰਾ",
"noVerifiedDiagnosis": "ਪ੍ਰਮਾਣਿਤ ਜਾਂਚ ਨਹੀਂ",
"analysisStatusLabel": "ਵਿਸ਼ਲੇਸ਼ਣ ਸਥਿਤੀ",
"cropLabel": "ਫ਼ਸਲ",
"cropNotIdentified": "ਪਛਾਣੀ ਨਹੀਂ ਗਈ",
"cropUnsupported": "ਅਸਮਰਥਿਤ",
"cropSourceUser": "ਤੁਸੀਂ ਚੁਣੀ (ਰੂਟਿੰਗ ਸੰਕੇਤ, ਮਾਡਲ ਸਬੂਤ ਨਹੀਂ)",
"cropSourceUnknown": "ਇਸ ਫੋਟੋ ਤੋਂ ਪਛਾਣੀ ਨਹੀਂ ਗਈ",
"selectCropPrompt": "ਕੀ ਤੁਹਾਨੂੰ ਫ਼ਸਲ ਪਤਾ ਹੈ? ਚੁਣਨ ਨਾਲ CropPilot ਨੂੰ ਸਹੀ ਮਾਹਰ ਚੁਣਨ ਵਿੱਚ ਮਦਦ ਮਿਲਦੀ ਹੈ।",
"analyzeAgain": "ਮੁੜ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
"retryAnalysis": "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
"coverageBadge": "ਮਾਡਲ ਕਵਰੇਜ ਉਪਲਬਧ ਨਹੀਂ",
"serviceBadge": "ਸੇਵਾ ਉਪਲਬਧ ਨਹੀਂ",
"temporaryAnalysisFailure": "ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਥਾਈ ਅਸਫਲ",
"modelFailureBody": "ਸਹਿਯੋਗੀ ਬਿਮਾਰੀ ਮਾਡਲ ਉਪਲਬਧ ਸੀ, ਪਰ ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ ਨਾ ਹੋ ਸਕਿਆ।",
"photoNeedsImprovement": "ਫੋਟੋ ਸੁਧਾਰ ਲੋੜੀਂਦਾ",
"noSpecialistAvailable": "CropPilot ਕੋਲ ਇਸ ਫ਼ਸਲ ਲਈ ਫਿਲਹਾਲ ਪ੍ਰਮਾਣਿਤ ਬਿਮਾਰੀ ਮਾਡਲ ਨਹੀਂ।",
"cropUnknownNoModel": "CropPilot ਇਸ ਫੋਟੋ ਤੋਂ ਫ਼ਸਲ ਨਾ ਪਛਾਣ ਸਕਿਆ, ਇਸ ਲਈ ਪ੍ਰਮਾਣਿਤ ਬਿਮਾਰੀ ਮਾਡਲ ਚੁਣਿਆ ਨਾ ਜਾ ਸਕਿਆ।",
"noCoverageTitle": "ਫ਼ਸਲ ਫਿਲਹਾਲ ਸਹਿਯੋਗੀ ਨਹੀਂ",
"lowConfidenceTitle": "ਜਾਂਚ ਅਨਿਸ਼ਚਿਤ",
"lowConfidenceBody": "ਭਰੋਸੇਯੋਗ ਜਾਂਚ ਲਈ ਉਪਲਬਧ ਮਾਡਲ ਲੋੜੀਂਦੇ ਸਹਿਮਤ ਨਾ ਹੋਏ।",
"confidenceNotAvailable": "ਉਪਲਬਧ ਨਹੀਂ",
"cropIdentification": "ਫ਼ਸਲ ਪਛਾਣ",
"cropSource": "ਫ਼ਸਲ ਸਰੋਤ",
"routingLabel": "ਰੂਟਿੰਗ",
"specialistsLabel": "ਮਾਹਰ",
"specialistsNone": "ਕੋਈ ਯੋਗ ਨਹੀਂ",
"calibrationLabel": "ਕੈਲੀਬਰੇਸ਼ਨ",
"calibrationUnavailable": "ਉਪਲਬਧ ਨਹੀਂ (ਕੱਚੇ ਮਾਡਲ ਸਕੋਰ)",
"vlmLabel": "VLM ਫਾਲਬੈਕ",
"vlmNotConfigured": "ਸੰਰਚਿਤ ਨਹੀਂ",
"vlmUsed": "ਸਮੀਖਿਆ ਲਈ ਵਰਤਿਆ",
"vlmNotUsed": "ਵਰਤਿਆ ਨਹੀਂ",
"coverageTitle": "ਮੌਜੂਦਾ ਮਾਡਲ ਕਵਰੇਜ",
"coverageBody": "{count} ਪ੍ਰਮਾਣਿਤ ਪ੍ਰੋਡਕਸ਼ਨ ਮਾਡਲ ਰਸਤੇ। ਕਵਰੇਜ ਸੀਮਤ ਹੈ ਅਤੇ ਵੱਧ ਰਹੀ ਹੈ।",
"whyLabel": "ਕਿਉਂ?",
"whatToDoLabel": "ਤੁਸੀਂ ਕੀ ਕਰ ਸਕਦੇ ਹੋ",
"errNoCoverage": "CropPilot ਕੋਲ ਇਸ ਫ਼ਸਲ ਲਈ ਫਿਲਹਾਲ ਪ੍ਰਮਾਣਿਤ ਬਿਮਾਰੀ ਮਾਡਲ ਨਹੀਂ।",
"errModelFailure": "ਸਹਿਯੋਗੀ ਬਿਮਾਰੀ ਮਾਡਲ ਉਪਲਬਧ ਸੀ, ਪਰ ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ ਨਾ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"noDiagnosis": "ਜਾਂਚ ਨਹੀਂ",
"statusNotSupported": "ਸਹਿਯੋਗੀ ਨਹੀਂ",
"statusFailed": "ਅਸਫਲ",
"downloadSummary": "ਸਾਰ ਡਾਊਨਲੋਡ ਕਰੋ",
"shareSummary": "ਸਾਰ ਸਾਂਝਾ ਕਰੋ",
"summaryCopied": "ਸਾਰ ਕਲਿੱਪਬੋਰਡ ਉੱਤੇ ਕਾਪੀ ਹੋਇਆ",
"analyzeAnotherPhoto": "ਹੋਰ ਫੋਟੋ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
"stepsTitle": "ਵਿਸ਼ਲੇਸ਼ਣ ਪੜਾਅ",
"stepUpload": "ਫੋਟੋ ਅੱਪਲੋਡ ਹੋ ਰਹੀ ਹੈ",
"stepQuality": "ਤਸਵੀਰ ਗੁਣਵੱਤਾ ਜਾਂਚੀ ਜਾ ਰਹੀ ਹੈ",
"stepRouting": "ਬਿਮਾਰੀ ਮਾਹਰ ਚੁਣੇ ਜਾ ਰਹੇ ਹਨ",
"stepAnalysis": "ਵਿਸ਼ਲੇਸ਼ਣ ਚੱਲ ਰਿਹਾ ਹੈ",
"stepVerify": "ਨਤੀਜੇ ਦੀ ਤਸਦੀਕ ਹੋ ਰਹੀ ਹੈ",
"supportedCropsNote": "ਪ੍ਰਮਾਣਿਤ ਮਾਹਰ ਵਾਲੀਆਂ ਫ਼ਸਲਾਂ",
"cropUnknownWeakEvidence": "ਸਹੀ ਬਿਮਾਰੀ ਮਾਹਰ ਚੁਣਨ ਲਈ ਲੋੜੀਂਦੇ ਸਬੂਤਾਂ ਨਾਲ CropPilot ਫ਼ਸਲ ਨਾ ਪਛਾਣ ਸਕਿਆ।",
"unknownCropWhy": "ਉਪਲਬਧ ਮਾਡਲ ਨੇ ਕਮਜ਼ੋਰ ਨਤੀਜੇ ਦਿੱਤੇ, ਪਰ ਤਸਵੀਰ ਫ਼ਸਲ ਦੀ ਪੁਸ਼ਟੀ ਲਈ ਲੋੜੀਂਦੇ ਸਬੂਤ ਨਹੀਂ ਦਿੰਦੀ।",
"modelOutputs": "ਮਾਡਲ ਆਉਟਪੁੱਟ",
"modelOutputsInterpretation": "ਪਾਰਦਰਸ਼ਤਾ ਲਈ ਕੱਚੇ ਮਾਡਲ ਆਉਟਪੁੱਟ ਦਿਖਾਏ ਗਏ ਹਨ; ਇਹਨਾਂ ਨੂੰ ਪ੍ਰਮਾਣਿਤ ਬਿਮਾਰੀ ਜਾਂਚ ਨਾ ਸਮਝਿਆ ਜਾਵੇ।",
"rawScoreLabel": "ਕੱਚਾ ਸਕੋਰ",
},
"assistant": {
"title": "AI ਸਹਾਇਕ",
"placeholder": "ਕੀਮਤਾਂ, ਮੌਸਮ, ਸਕੀਮਾਂ ਬਾਰੇ ਪੁੱਛੋ…",
"send": "ਭੇਜੋ",
"offline": "ਸਹਾਇਕ ਉਪਲਬਧ ਨਹੀਂ। ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"offlineBackend": "ਸਹਾਇਕ ਉਪਲਬਧ ਨਹੀਂ। ਵੇਖੋ ਬੈਕਐਂਡ ਚੱਲ ਰਿਹਾ ਹੈ।",
"sources": "ਸਰੋਤ",
"newChat": "ਨਵੀਂ ਚੈਟ",
"welcome": "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ **CropPilot AI** ਹਾਂ — ਤੁਹਾਡਾ ਸਿਆਣਾ ਖੇਤੀ ਸਹਾਇਕ। 🌾\n\nਮੈਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ:\n\n- **ਫ਼ਸਲ ਪ੍ਰਬੰਧਨ** — ਬਿਜਾਈ, ਸਿੰਚਾਈ, ਖਾਦ ਸਮਾਂ-ਸਾਰਣੀ\n- **ਬਿਮਾਰੀ ਪਛਾਣ** — ਫ਼ਸਲ ਬਿਮਾਰੀਆਂ ਪਛਾਣੋ ਅਤੇ ਇਲਾਜ ਕਰੋ\n- **ਮੰਡੀ ਵਿਸ਼ਲੇਸ਼ਣ** — ਤਾਜ਼ਾ ਮੰਡੀ ਭਾਅ ਅਤੇ ਰੁਝਾਨ\n- **ਸਰਕਾਰੀ ਸਕੀਮਾਂ** — ਯੋਗ ਸਕੀਮਾਂ ਲੱਭੋ\n- **ਮੌਸਮੀ ਸਮਝ** — ਭਵਿੱਖਬਾਣੀ ਅਤੇ ਫ਼ਸਲਾਂ ਉੱਤੇ ਅਸਰ\n\nਅੱਜ ਆਪਣੇ ਖੇਤ ਬਾਰੇ ਕੀ ਜਾਣਨਾ ਚਾਹੋਗੇ?",
"welcomeTitle": "CropPilot ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
"welcomePreview": "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ CropPilot AI ਹਾਂ…",
"newChatTitle": "ਨਵੀਂ ਚੈਟ",
"newChatPreview": "ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ…",
"promptPaddy": "ਕਣਕ ਦੀ ਕਾਸ਼ਤ ਦੇ ਵਧੀਆ ਤਰੀਕੇ",
"promptDisease": "ਟਮਾਟਰ ਪੱਤੇ ਦੀ ਝੁਲਸ ਪਛਾਣੋ",
"promptMarket": "ਮੌਜੂਦਾ ਮੰਡੀ ਭਾਅ",
"promptSchemes": "ਕਿਸਾਨਾਂ ਲਈ ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
"suggestTitle": "ਖੇਤੀ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ — ਫ਼ਸਲਾਂ, ਬਿਮਾਰੀਆਂ, ਮੰਡੀਆਂ, ਸਕੀਮਾਂ ਅਤੇ ਹੋਰ",
"cardCrop": "ਫ਼ਸਲ ਸਲਾਹ",
"cardCropBody": "ਕਣਕ ਦੀ ਕਾਸ਼ਤ ਦੇ ਵਧੀਆ ਤਰੀਕੇ",
"cardCropQuery": "ਕਣਕ ਦੀ ਕਾਸ਼ਤ ਦੇ ਵਧੀਆ ਤਰੀਕੇ ਕੀ ਹਨ?",
"cardDisease": "ਬਿਮਾਰੀ ਮਦਦ",
"cardDiseaseBody": "ਟਮਾਟਰ ਵਿੱਚ ਪੱਤੇ ਦੀ ਝੁਲਸ ਪਛਾਣੋ ਅਤੇ ਇਲਾਜ ਕਰੋ",
"cardDiseaseQuery": "ਟਮਾਟਰ ਬੂਟਿਆਂ ਵਿੱਚ ਪੱਤੇ ਦੀ ਝੁਲਸ ਕਿਵੇਂ ਪਛਾਣਾਂ ਅਤੇ ਇਲਾਜ ਕਰਾਂ?",
"cardMarket": "ਮੰਡੀ ਸਵਾਲ",
"cardMarketBody": "ਝੋਨੇ ਅਤੇ ਕਣਕ ਦੇ ਮੌਜੂਦਾ ਮੰਡੀ ਭਾਅ",
"cardMarketQuery": "ਤੇਲੰਗਾਨਾ ਵਿੱਚ ਝੋਨੇ ਅਤੇ ਕਣਕ ਦੇ ਮੌਜੂਦਾ ਮੰਡੀ ਭਾਅ ਕੀ ਹਨ?",
"cardScheme": "ਸਕੀਮ ਜਾਣਕਾਰੀ",
"cardSchemeBody": "ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
"cardSchemeQuery": "ਭਾਰਤ ਵਿੱਚ ਛੋਟੇ ਕਿਸਾਨ ਵਜੋਂ ਮੈਂ ਕਿਹੜੀਆਂ ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਦਾ ਯੋਗ ਹਾਂ?",
"cardWeather": "ਮੌਸਮ ਸਵਾਲ",
"cardWeatherBody": "ਆਉਣ ਵਾਲਾ ਮੌਸਮ ਅਤੇ ਫ਼ਸਲਾਂ ਉੱਤੇ ਅਸਰ",
"cardWeatherQuery": "ਆਉਣ ਵਾਲਾ ਮੌਸਮ ਮੇਰੀਆਂ ਸਾਉਣੀ ਫ਼ਸਲਾਂ ਉੱਤੇ ਕਿਵੇਂ ਅਸਰ ਪਾਵੇਗਾ?",
"cardPlan": "ਖੇਤ ਯੋਜਨਾ",
"cardPlanBody": "ਫ਼ਸਲ ਚੱਕਰ ਅਤੇ ਮਿੱਟੀ ਪ੍ਰਬੰਧਨ ਸੁਝਾਅ",
"cardPlanQuery": "ਆਪਣੇ ਖੇਤ ਲਈ ਫ਼ਸਲ ਦਾ ਕਿਹੜਾ ਚੱਕਰ ਅਪਣਾਵਾਂ?",
"sideNewChat": "ਨਵੀਂ ਚੈਟ",
"sideSearch": "ਗੱਲਬਾਤ ਖੋਜੋ…",
"sideNoFound": "ਗੱਲਬਾਤ ਨਹੀਂ ਮਿਲੀ",
"sideNoYet": "ਅਜੇ ਗੱਲਬਾਤ ਨਹੀਂ",
"sideClose": "ਸਾਈਡਬਾਰ ਬੰਦ ਕਰੋ",
"sideOpen": "ਸਾਈਡਬਾਰ ਖੋਲ੍ਹੋ",
"sideDelete": "ਗੱਲਬਾਤ ਮਿਟਾਓ",
"inputDefault": "ਫ਼ਸਲਾਂ, ਬਿਮਾਰੀਆਂ, ਮੰਡੀਆਂ, ਸਕੀਮਾਂ ਬਾਰੇ ਪੁੱਛੋ…",
"voiceError": "ਆਵਾਜ਼ ਗਲਤੀ",
"voiceUnreachable": "ਆਵਾਜ਼ ਸੇਵਾ ਪਹੁੰਚ ਤੋਂ ਬਾਹਰ",
"micDenied": "ਮਾਈਕ੍ਰੋਫੋਨ ਪਹੁੰਚ ਰੱਦ",
"paletteSearch": "ਪੰਨੇ ਖੋਜੋ ਜਾਂ ਕਮਾਂਡ ਲਿਖੋ…",
"paletteEmpty": "ਨਤੀਜੇ ਨਹੀਂ ਮਿਲੇ।",
"errorTitle": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
"errorFallback": "ਅਚਾਨਕ ਗਲਤੀ ਹੋਈ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"notFoundTitle": "ਪੰਨਾ ਨਹੀਂ ਮਿਲਿਆ",
"notFoundBody": "ਜੋ ਪੰਨਾ ਤੁਸੀਂ ਲੱਭ ਰਹੇ ਹੋ ਉਹ ਮੌਜੂਦ ਨਹੀਂ ਜਾਂ ਹਿਲਾਇਆ ਗਿਆ ਹੈ।",
"goDashboard": "ਡੈਸ਼ਬੋਰਡ ਉੱਤੇ ਜਾਓ",
"goHome": "ਘਰ ਜਾਓ",
"loadingApp": "CropPilot ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…",
"themeToggle": "ਥੀਮ ਬਦਲੋ",
"themeCurrent": "ਮੌਜੂਦਾ ਥੀਮ: {theme}। {next} ਲਈ ਕਲਿੱਕ ਕਰੋ",
"themeLight": "ਚਾਨਣ",
"themeDark": "ਗੂੜ੍ਹਾ",
"themeSystem": "ਸਿਸਟਮ",
"attachFiles": "ਫਾਈਲਾਂ ਨੱਥੀ ਕਰੋ",
"attachDocs": "ਤਸਵੀਰਾਂ ਤੇ ਦਸਤਾਵੇਜ਼",
"takePhoto": "ਫੋਟੋ ਲਓ",
"copyResponse": "ਜਵਾਬ ਕਾਪੀ ਕਰੋ",
"copied": "ਕਾਪੀ ਹੋਇਆ",
"helpful": "ਲਾਭਦਾਇਕ",
"notHelpful": "ਲਾਭਦਾਇਕ ਨਹੀਂ",
"fileTypeUnsupported": "\"{type}\" ਫਾਈਲ ਕਿਸਮ ਸਹਿਯੋਗੀ ਨਹੀਂ",
"sourcesCount": "{count} ਸਰੋਤ",
"sourcesCountPlural": "{count} ਸਰੋਤ",
},
"maps": {
"loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…",
"searchLocation": "ਪਿੰਡ, ਕਸਬਾ, ਮੰਡੀ ਜਾਂ ਪਿੰਨ ਕੋਡ ਖੋਜੋ",
"clearSearch": "ਖੋਜ ਸਾਫ਼ ਕਰੋ",
"searchFailed": "ਸਥਾਨ ਨਹੀਂ ਮਿਲਿਆ। ਹੋਰ ਖੋਜ ਅਜ਼ਮਾਓ।",
"noResults": "ਮਿਲਦੇ ਸਥਾਨ ਨਹੀਂ ਮਿਲੇ।",
"useMyLocation": "ਮੇਰੀ ਸਥਿਤੀ ਵਰਤੋ",
"resetView": "ਭਾਰਤ ਦ੍ਰਿਸ਼ ਰੀਸੈਟ ਕਰੋ",
"fullscreen": "ਪੂਰੀ-ਸਕ੍ਰੀਨ ਨਕਸ਼ਾ",
"mapLabel": "ਭਾਰਤ ਦਾ CropPilot ਖੇਤੀ ਨਕਸ਼ਾ",
"location": "ਸਥਾਨ",
"locationInsights": "ਸਥਾਨ ਜਾਣਕਾਰੀ",
"placeUnavailable": "ਸਥਾਨ ਦਾ ਨਾਮ ਉਪਲਬਧ ਨਹੀਂ — ਨਿਰਦੇਸ਼ਾਂਕ ਦਿਖਾਏ ਗਏ ਹਨ।",
"weather": "ਮੌਸਮ",
"weatherMapTitle": "ਮੌਸਮ ਨਕਸ਼ਾ",
"rainRadar": "ਮੀਂਹ ਰਾਡਾਰ",
"weatherUnavailable": "ਮੌਸਮ ਜਾਣਕਾਰੀ ਅਸਥਾਈ ਉਪਲਬਧ ਨਹੀਂ।",
"humidity": "ਨਮੀ",
"wind": "ਹਵਾ",
"rain": "ਮੀਂਹ",
"feelsLike": "ਮਹਿਸੂਸ ਹੁੰਦਾ ਹੈ",
"wmoCode": "WMO ਕੋਡ {code}",
"updatedJustNow": "ਹੁਣੇ ਅੱਪਡੇਟ ਹੋਇਆ",
"updatedMinutesAgo": "{count} ਮਿੰਟ ਪਹਿਲਾਂ ਅੱਪਡੇਟ ਹੋਇਆ",
"updatedHoursAgo": "{count} ਘੰਟੇ ਪਹਿਲਾਂ ਅੱਪਡੇਟ ਹੋਇਆ",
"sourceOpenMeteo": "ਸਰੋਤ: Open-Meteo",
"nearbyMarkets": "ਨੇੜਲੀਆਂ ਮੰਡੀਆਂ",
"commodityFilter": "ਜਿਨਸ ਅਨੁਸਾਰ ਛਾਂਟੋ",
"allCommodities": "ਸਾਰੀਆਂ ਜਿਨਸਾਂ",
"searchArea": "ਇਸ ਖੇਤਰ ਵਿੱਚ ਖੋਜੋ",
"marketsUnavailable": "ਨੇੜਲੀ ਮੰਡੀ ਡਾਟਾ ਲੋਡ ਨਾ ਹੋ ਸਕਿਆ।",
"noMappedMarkets": "ਨੇੜੇ ਨਕਸ਼ਾ ਨਿਰਦੇਸ਼ਾਂਕਾਂ ਵਾਲੀਆਂ ਮੰਡੀਆਂ ਨਹੀਂ ਮਿਲੀਆਂ।",
"noReportedPrice": "ਇਸ ਮੰਡੀ ਲਈ ਅਜੇ ਦਰਜ ਭਾਅ ਨਹੀਂ।",
"latestReported": "ਤਾਜ਼ਾ ਦਰਜ: {date}",
"sourceAgmarknet": "ਸਰੋਤ: AGMARKNET",
"quintal": "ਕੁਇੰਟਲ",
"unmappedNote": "ਇੱਥੇ ਹੋਰ {count} ਮੰਡੀਆਂ ਦੇ ਨਕਸ਼ਾ ਨਿਰਦੇਸ਼ਾਂਕ ਅਜੇ ਨਹੀਂ; ਉਹ ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ ਵਿੱਚ ਦਰਜ ਹਨ।",
"closeDetails": "ਮੰਡੀ ਵੇਰਵੇ ਬੰਦ ਕਰੋ",
"viewMarketIntel": "ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ ਵੇਖੋ",
"cropPilotActions": "CropPilot ਕਾਰਵਾਈਆਂ",
"openMarketIntel": "ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ",
"analyzeDisease": "ਫ਼ਸਲ ਬਿਮਾਰੀ ਵਿਸ਼ਲੇਸ਼ਣ",
"askAssistant": "CropPilot AI ਨੂੰ ਪੁੱਛੋ",
"legendSelected": "ਚੁਣਿਆ ਸਥਾਨ",
"legendMarkets": "ਮੰਡੀਆਂ",
"markets": "ਮੰਡੀਆਂ",
"toggleMarkets": "ਮੰਡੀ ਮਾਰਕਰ ਚਾਲੂ/ਬੰਦ ਕਰੋ",
"pickHint": "ਸਥਾਨ ਚੁਣਨ ਲਈ ਨਕਸ਼ੇ ਉੱਤੇ ਕਲਿੱਕ ਕਰੋ",
"collapseSheet": "ਪੈਨਲ ਛੋਟਾ ਕਰੋ",
"expandSheet": "ਪੈਨਲ ਵੱਡਾ ਕਰੋ",
"geoDenied": "ਸਥਾਨ ਪਹੁੰਚ ਰੱਦ। ਇਸ ਦੀ ਬਜਾਏ ਆਪਣਾ ਸਥਾਨ ਖੋਜ ਸਕਦੇ ਹੋ।",
"geoUnavailable": "ਮੌਜੂਦਾ ਸਥਾਨ ਉਪਲਬਧ ਨਹੀਂ। ਖੋਜ ਅਜ਼ਮਾਓ।",
"geoTimeout": "ਸਥਾਨ ਬੇਨਤੀ ਦਾ ਸਮਾਂ ਖਤਮ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਖੋਜੋ।",
"geoUnsupported": "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਜੀਓਲੋਕੇਸ਼ਨ ਸਹਿਯੋਗੀ ਨਹੀਂ। ਕਿਰਪਾ ਕਰਕੇ ਖੋਜੋ।",
"mapUnavailable": "ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਇੰਟਰਐਕਟਿਵ ਨਕਸ਼ਾ ਉਪਲਬਧ ਨਹੀਂ (WebGL ਬੰਦ)। ਖੋਜ ਅਤੇ ਸਥਾਨ ਜਾਣਕਾਰੀ ਹੇਠਾਂ ਚੱਲਦੀ ਹੈ।",
"agriSnapshot": "ਖੇਤੀ ਸਨੈਪਸ਼ਾਟ",
"commonCrops": "ਆਮ ਫ਼ਸਲਾਂ",
"soil": "ਮਿੱਟੀ",
"rainfall": "ਮੀਂਹ",
"seasonRain": "{season} ਵਿੱਚ {mm} ਮਿਮੀ",
"forecastLabel": "ਭਵਿੱਖਬਾਣੀ",
"texture": "ਬਣਤਰ",
"organicCarbon": "ਜੈਵਿਕ ਕਾਰਬਨ",
"clay": "ਚੀਕਣੀ ਮਿੱਟੀ",
"sand": "ਰੇਤ",
"silt": "ਸਿਲਟ",
"nitrogen": "ਨਾਈਟ੍ਰੋਜਨ",
"sourceSoilGrids": "ਸਰੋਤ: SoilGrids",
"resolutionM": "ਰੈਜ਼ੋਲਿਊਸ਼ਨ: {m} ਮੀ",
"modelledEstimateNote": "ਮਾਡਲ ਅਨੁਮਾਨ, ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਮਿੱਟੀ ਜਾਂਚ ਨਹੀਂ",
"modelledBadge": "ਮਾਡਲ-ਅਧਾਰਿਤ",
"soilUnavailable": "ਇਸ ਸਥਾਨ ਲਈ ਮਿੱਟੀ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ।",
"today": "ਅੱਜ",
"last7days": "ਪਿਛਲੇ 7 ਦਿਨ",
"thisMonth": "ਇਸ ਮਹੀਨੇ",
"season": "ਸੀਜ਼ਨ",
"reanalysisNote": "ਮੁੜ-ਵਿਸ਼ਲੇਸ਼ਣ/ਭਵਿੱਖਬਾਣੀ ਅਨੁਮਾਨ, ਸਟੇਸ਼ਨ ਡਾਟਾ ਨਹੀਂ",
"rainfallUnavailable": "ਇਸ ਸਥਾਨ ਲਈ ਮੀਂਹ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ।",
"crops": "ਫ਼ਸਲਾਂ",
"commonlyTraded": "ਖੇਤਰ ਮੰਡੀਆਂ ਵਿੱਚ ਹਾਲ ਵਪਾਰੀਆਂ ਜਿਨਸਾਂ",
"cropsUnavailable": "ਇਸ ਖੇਤਰ ਲਈ ਫ਼ਸਲ ਵਪਾਰ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ।",
"suitabilityTitle": "ਵਾਤਾਵਰਣ ਅਨੁਕੂਲਤਾ ਅਨੁਮਾਨ",
"water": "ਜਲ ਸਰੋਤ",
"waterUnavailable": "ਇਸ ਸਥਾਨ ਲਈ ਪਾਣੀ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ।",
"waterNote": "ਧਰਤੀ ਹੇਠਲੇ ਪਾਣੀ ਦੇ ਨਿਰੀਖਣ ਸਮੇਂ-ਸਮੇਂ ਉੱਤੇ ਹੁੰਦੇ ਹਨ ਅਤੇ ਭੰਡਾਰ ਪਾਣੀ ਖੇਤ ਸਿੰਚਾਈ ਉਪਲਬਧਤਾ ਨਹੀਂ ਦੱਸਦਾ।",
"diseaseContext": "ਬਿਮਾਰੀ ਸੰਦਰਭ",
"diseaseUnavailable": "ਇਸ ਖੇਤਰ ਲਈ ਬਿਮਾਰੀ ਸੰਦਰਭ ਉਪਲਬਧ ਨਹੀਂ।",
"selectedLocation": "ਚੁਣਿਆ ਸਥਾਨ",
"viewFullMap": "ਪੂਰਾ ਨਕਸ਼ਾ ਵੇਖੋ",
"yourLocation": "ਤੁਹਾਡਾ ਸਥਾਨ",
},
"markets": {
"title": "ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ",
"subtitle": "AGMARKNET ਤੋਂ ਤਾਜ਼ਾ ਦਰਜ ਮੰਡੀ ਭਾਅ",
"state": "ਰਾਜ",
"district": "ਜ਼ਿਲ੍ਹਾ",
"market": "ਮੰਡੀ",
"commodity": "ਜਿਨਸ",
"days": "ਦਿਨ",
"latestPrice": "ਤਾਜ਼ਾ ਦਰਜ ਭਾਅ: {price} ਪ੍ਰਤੀ ਕੁਇੰਟਲ",
"arrivalDate": "ਆਮਦ ਮਿਤੀ: {date}",
"empty": "ਡਾਟਾਬੇਸ ਵਿੱਚ ਮਿਲਦਾ ਤਾਜ਼ਾ ਦਰਜ ਭਾਅ ਨਹੀਂ ਮਿਲਿਆ।",
"unavailableTitle": "ਮੰਡੀ ਡਾਟਾ ਫਿਲਹਾਲ ਉਪਲਬਧ ਨਹੀਂ",
"tryAgain": "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
"signInRequired": "ਸਾਈਨ ਇਨ ਲੋੜੀਂਦਾ",
"signInPrompt": "ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ ਵੇਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
"signInNeeded": "ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ ਵੇਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
"offline": "ਮੰਡੀ ਸੇਵਾ ਤੱਕ ਪਹੁੰਚ ਨਾ ਹੋ ਸਕੀ। ਕੁਨੈਕਸ਼ਨ ਮੁੜਨ ਉੱਤੇ ਸਾਂਭੇ ਨਿਰੀਖਣ ਦਿਸਣਗੇ।",
"loadError": "ਇਹ ਹਿੱਸਾ ਲੋਡ ਕਰਦਿਆਂ ਕੁਝ ਗਲਤ ਹੋਇਆ। ਤੁਹਾਡੇ ਸਾਂਭੇ ਨਿਰੀਖਣ ਸੁਰੱਖਿਅਤ ਹਨ।",
"loadErrorShort": "ਇਹ ਹਿੱਸਾ ਲੋਡ ਕਰਦਿਆਂ ਕੁਝ ਗਲਤ ਹੋਇਆ।",
"allStates": "ਸਾਰੇ ਰਾਜ",
"allDistricts": "ਸਾਰੇ ਜ਼ਿਲ੍ਹੇ",
"selectStateFirst": "ਪਹਿਲਾਂ ਰਾਜ ਚੁਣੋ",
"allMarkets": "ਸਾਰੀਆਂ ਮੰਡੀਆਂ",
"selectCommodity": "ਜਿਨਸ ਚੁਣੋ",
"allVarieties": "ਸਾਰੀਆਂ ਕਿਸਮਾਂ",
"allGrades": "ਸਾਰੇ ਗ੍ਰੇਡ",
"variety": "ਕਿਸਮ",
"grade": "ਗ੍ਰੇਡ",
"statesReporting": "ਰਿਪੋਰਟਿੰਗ ਰਾਜ",
"marketsReporting": "ਰਿਪੋਰਟਿੰਗ ਮੰਡੀਆਂ",
"commoditiesReported": "ਦਰਜ ਜਿਨਸਾਂ",
"latestObservation": "ਤਾਜ਼ਾ ਨਿਰੀਖਣ",
"storedObservations": "ਸਾਂਭੇ ਨਿਰੀਖਣ ਦਿਖਾਏ ਜਾ ਰਹੇ ਹਨ",
"storedObservationsBody": "ਇਸ ਚੋਣ ਲਈ ਸਰੋਤ ਨੇ ਹਾਲ ਨਿਰੀਖਣ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਕੀਤਾ। ਹੇਠਲੇ ਮੁੱਲ ਤਾਜ਼ਾ ਸਾਂਭੀਆਂ ਰਿਪੋਰਟਾਂ ਹਨ, ਨਵੇਂ ਭਾਅ ਨਹੀਂ।",
"noRecentPrice": "ਹਾਲ ਦਰਜ ਭਾਅ ਨਹੀਂ",
"emptyHint": "ਕੋਈ ਹੋਰ ਰਾਜ, ਜ਼ਿਲ੍ਹਾ, ਜਿਨਸ ਜਾਂ ਮੰਡੀ ਅਜ਼ਮਾਓ। ਅਗਲੇ ਪ੍ਰਕਾਸ਼ਨ ਤੋਂ ਬਾਅਦ ਨਵੀਆਂ ਰਿਪੋਰਟਾਂ ਇੱਥੇ ਦਿਸਣਗੀਆਂ।",
"selectionSummary": "ਚੋਣ ਸਾਰ",
"reportedMarkets": "ਦਰਜ ਮੰਡੀਆਂ",
"observationsInTable": "ਸਾਰਣੀ ਵਿੱਚ ਨਿਰੀਖਣ",
"trendPoints": "ਰੁਝਾਨ ਬਿੰਦੂ",
"comingLater": "ਬਾਅਦ ਵਿੱਚ ਆ ਰਿਹਾ ਹੈ",
"comingLaterBody": "ਕੀਮਤ ਭਵਿੱਖਬਾਣੀ ਅਤੇ ਵਿਕਰੀ ਸਿਫਾਰਸ਼ਾਂ ਅਜੇ ਇਸ ਦ੍ਰਿਸ਼ ਦਾ ਹਿੱਸਾ ਨਹੀਂ। ਇੱਥੇ ਸਿਰਫ਼ ਦਰਜ ਨਿਰੀਖਣ ਦਿਖਾਏ ਗਏ ਹਨ।",
"searchStates": "ਰਾਜ ਖੋਜੋ…",
"searchDistricts": "ਜ਼ਿਲ੍ਹੇ ਖੋਜੋ…",
"searchMarkets": "ਮੰਡੀਆਂ ਖੋਜੋ…",
"noMatchState": "ਮਿਲਦਾ ਰਾਜ ਨਹੀਂ।",
"noMatchDistrict": "ਮਿਲਦਾ ਜ਼ਿਲ੍ਹਾ ਨਹੀਂ।",
"noMatchMarket": "ਮਿਲਦੀ ਮੰਡੀ ਨਹੀਂ।",
"tableSearch": "ਲੋਡ ਨਤੀਜਿਆਂ ਵਿੱਚ ਖੋਜੋ…",
"thMin": "ਘੱਟੋ ਰੁ",
"thMax": "ਵੱਧ ਰੁ",
"thModal": "ਮੋਡਲ ਰੁ",
"thArrivals": "ਆਮਦ",
"thObserved": "ਨਿਰੀਖਣ",
"showingCount": "{from}–{to} ਕੁੱਲ {total} ਵਿੱਚੋਂ",
"prevPage": "ਪਿਛਲਾ ਪੰਨਾ",
"nextPage": "ਅਗਲਾ ਪੰਨਾ",
"priceRs": "ਰੁ{value}",
"minMaxLine": "ਘੱਟੋ ਰੁ{min} · ਵੱਧ ਰੁ{max}",
"arrivalsLine": "ਆਮਦ: {value}",
"freshNone": "ਹਾਲ ਨਿਰੀਖਣ ਉਪਲਬਧ ਨਹੀਂ",
"freshLatest": "ਤਾਜ਼ਾ ਦਰਜ: {date}",
"freshStale": "ਡਾਟਾ ਦੇਰੀ ਨਾਲ ਹੋ ਸਕਦਾ ਹੈ",
"sourceLabel": "ਸਰੋਤ: {name}",
"sourceBody": "ਦਰਜ ਮੰਡੀ ਭਾਅ ਮੰਡੀਆਂ ਦੇ ਪ੍ਰਕਾਸ਼ਿਤ ਨਿਰੀਖਣ ਹਨ ਅਤੇ ਦੇਰੀ ਨਾਲ ਆ ਸਕਦੇ ਹਨ। ਇਹ ਭਵਿੱਖੀ ਭਾਅ ਦੀ ਗਾਰੰਟੀ ਨਹੀਂ।",
"sourceResource": "ਸਰੋਤ: {id}",
"cmpNoData": "ਤੁਲਨਾ ਉਪਲਬਧ ਨਹੀਂ",
"cmpNoDataBody": "ਇਸ ਚੋਣ ਲਈ ਅਜੇ ਦਰਜ ਭਾਅ ਨਹੀਂ।",
"cmpTitle": "ਮੰਡੀ ਤੁਲਨਾ",
"cmpBody": "ਸਿਰਫ਼ ਮਿਲਦੀ ਕਿਸਮ, ਗ੍ਰੇਡ ਅਤੇ ਇਕਾਈ ਵਾਲੀਆਂ ਕਤਾਰਾਂ ਮਿਲਾਈਆਂ ਜਾਂਦੀਆਂ ਹਨ। ਭਾਅ ਪ੍ਰਤੀ ਮੰਡੀ ਤਾਜ਼ਾ ਦਰਜ ਨਿਰੀਖਣ ਹਨ।",
"cmpMinMax": "ਘੱਟੋ ਤੋਂ ਵੱਧ ਰੁ",
"histNoData": "ਭਾਅ ਇਤਿਹਾਸ ਨਹੀਂ",
"histNoDataBody": "ਚੁਣੀ ਮੰਡੀ ਅਤੇ ਜਿਨਸ ਲਈ ਇਸ ਮਿਆਦ ਵਿੱਚ ਦਰਜ ਨਿਰੀਖਣ ਨਹੀਂ।",
"histTitle": "ਦਰਜ ਮੋਡਲ ਭਾਅ ਰੁਝਾਨ",
"histUnit": "ਰੁ ਪ੍ਰਤੀ {unit}",
"histModal": "ਮੋਡਲ",
"histMax": "ਵੱਧ",
"histMin": "ਘੱਟ",
"histCount": "{count} ਨਿਰੀਖਣ",
"histObserved": "{label} ਨੂੰ ਨਿਰੀਖਣ",
"cmpUnspecified": "ਅਨਿਸ਼ਚਿਤ ਕਿਸਮ ਅਤੇ ਗ੍ਰੇਡ",
},
"schemes": {
"title": "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
"subtitle": "ਖੇਤੀ ਸਕੀਮਾਂ, ਸਬਸਿਡੀ ਅਤੇ ਭਲਾਈ ਪ੍ਰੋਗਰਾਮ ਲੱਭੋ ਅਤੇ ਅਰਜ਼ੀ ਦਿਓ",
"search": "ਨਾਮ, ਵੇਰਵੇ, ਟੈਗ ਨਾਲ ਸਕੀਮਾਂ ਖੋਜੋ…",
"all": "ਸਾਰੇ",
"noFound": "ਸਕੀਮਾਂ ਨਹੀਂ ਮਿਲੀਆਂ",
"noFoundBody": "ਆਪਣੀ ਖੋਜ ਜਾਂ ਫਿਲਟਰ ਬਦਲੋ",
"viewDetail": "ਵੇਰਵੇ ਵੇਖੋ",
"eligibility": "ਯੋਗਤਾ",
"benefits": "ਲਾਭ",
"howToApply": "ਅਰਜ਼ੀ ਕਿਵੇਂ ਦੇਣੀ",
"close": "ਬੰਦ ਕਰੋ",
"moreDetails": "ਹੋਰ ਵੇਰਵੇ",
"applicationProcess": "ਅਰਜ਼ੀ ਪ੍ਰਕਿਰਿਆ:",
"funding": "ਫੰਡਿੰਗ:",
"checkEligibility": "ਯੋਗਤਾ ਵੇਖੋ",
"ministry": "ਮੰਤਰਾਲਾ:",
"eligibilityCriteria": "ਯੋਗਤਾ ਮਾਪਦੰਡ",
"requiredDocuments": "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
"active": "ਸਰਗਰਮ",
"inactive": "ਅਸਰਗਰਮ",
"applyNow": "ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ",
},
"analytics": {
"title": "ਵਿਸ਼ਲੇਸ਼ਣ",
"subtitle": "ਆਪਣੇ ਖੇਤ ਪ੍ਰਦਰਸ਼ਨ ਦੀ ਵਿਆਪਕ ਸਮਝ",
"tabRevenue": "ਆਮਦਨ",
"tabYield": "ਝਾੜ",
"tabCropHealth": "ਫ਼ਸਲ ਸਿਹਤ",
"tabWater": "ਪਾਣੀ ਦੀ ਵਰਤੋਂ",
"tabFertilizer": "ਖਾਦ ਦੀ ਵਰਤੋਂ",
"tabMarket": "ਮੰਡੀ ਵਿਸ਼ਲੇਸ਼ਣ",
"statRevenue": "ਕੁੱਲ ਆਮਦਨ",
"statYield": "ਔਸਤ ਝਾੜ/ਹੈ",
"statHealth": "ਸਿਹਤ ਸਕੋਰ",
"statWater": "ਪਾਣੀ ਕੁਸ਼ਲਤਾ",
"rangeCustom": "ਕਸਟਮ",
"chRevenueMonthly": "ਮਾਸਿਕ ਆਮਦਨ",
"chRevenueByCrop": "ਫ਼ਸਲ ਅਨੁਸਾਰ ਆਮਦਨ",
"chRevenueCumulative": "ਸੰਚਯੀ ਆਮਦਨ",
"chYieldByCrop": "ਫ਼ਸਲ ਅਨੁਸਾਰ ਝਾੜ",
"chYieldTrend": "ਝਾੜ ਰੁਝਾਨ",
"chYieldVsTarget": "ਝਾੜ ਬਨਾਮ ਟੀਚਾ",
"chYieldPerHa": "ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਝਾੜ",
"chYieldTopBottom": "ਸਿਖਰ ਅਤੇ ਹੇਠਲੀਆਂ ਫ਼ਸਲਾਂ",
"chHealthOverall": "ਸਮੁੱਚੀ ਸਿਹਤ",
"chHealthRadar": "ਸਿਹਤ ਮਾਪਦੰਡ ਰਾਡਾਰ",
"chHealthTrend": "ਸਿਹਤ ਸਕੋਰ ਰੁਝਾਨ",
"chHealthByPlot": "ਪਲਾਟ ਅਨੁਸਾਰ ਸਿਹਤ",
"chHealthTimeline": "ਸਿਹਤ ਸੂਚਨਾ ਸਮਾਂ-ਰੇਖਾ",
"chPriceTrends": "ਭਾਅ ਰੁਝਾਨ - ਪ੍ਰਮੁੱਖ 5 ਜਿਨਸਾਂ",
"chPriceHeatmap": "ਭਾਅ ਹੀਟਮੈਪ - ਜਿਨਸ ਬਨਾਮ ਮਹੀਨਾ",
"chBestTimes": "ਵਧੀਆ ਵਿਕਰੀ ਸਮੇਂ",
"chTrade": "ਨਿਰਯਾਤ / ਆਯਾਤ ਵਿਸ਼ਲੇਸ਼ਣ",
"chVolume": "ਵਪਾਰ ਮਾਤਰਾ",
"chInsights": "AI ਸਮਝ",
"chWaterDaily": "ਮੀਂਹ ਨਾਲ ਰੋਜ਼ਾਨਾ ਪਾਣੀ ਦੀ ਵਰਤੋਂ",
"chWaterByCrop": "ਫ਼ਸਲ ਅਨੁਸਾਰ ਪਾਣੀ ਦੀ ਵਰਤੋਂ",
"chWaterEff": "ਪਾਣੀ ਕੁਸ਼ਲਤਾ (ਪ੍ਰਤੀ ਕਿਲੋ ਝਾੜ ਲਿਟਰ)",
"chWaterSave": "ਪਾਣੀ ਬਚਤ ਸੁਝਾਅ",
"chWaterSchedule": "ਸਮਾਂ-ਸਾਰਣੀ ਸਿਫਾਰਸ਼ਾਂ",
"chFertBreakdown": "ਖਾਦ ਕਿਸਮ ਵੰਡ",
"chFertCost": "ਸਿਫਾਰਸ਼ ਬਨਾਮ ਲਾਗਤ ਵਿਸ਼ਲੇਸ਼ਣ",
"chFertNPK": "ਸਮੇਂ ਨਾਲ N / P / K ਵਰਤੋਂ",
"statVolatility": "ਭਾਅ ਅਸਥਿਰਤਾ ਸੂਚਕ",
"statGainers": "ਸਿਖਰ ਵਾਧਾ",
"statLosers": "ਸਿਖਰ ਗਿਰਾਵਟ",
"statVolume": "ਕੁੱਲ ਮਾਤਰਾ",
"trendLow": "ਘੱਟ",
"thCommodity": "ਜਿਨਸ",
"expShort": "ਨਿਰ",
"impShort": "ਆਯਾ",
},
"voice": {
"start": "ਆਵਾਜ਼ ਇਨਪੁੱਟ ਸ਼ੁਰੂ ਕਰੋ",
"stop": "ਰੋਕੋ",
"listening": "ਸੁਣ ਰਹੇ ਹਾਂ…",
"transcribing": "ਲਿਖਿਆ ਜਾ ਰਿਹਾ ਹੈ…",
"thinking": "ਸੋਚ ਰਹੇ ਹਾਂ…",
"speaking": "ਬੋਲ ਰਹੇ ਹਾਂ…",
"unavailable": "ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਆਵਾਜ਼ ਇਨਪੁੱਟ ਉਪਲਬਧ ਨਹੀਂ।",
"audioUnavailable": "ਇਸ ਭਾਸ਼ਾ ਲਈ ਬੋਲਿਆ ਆਉਟਪੁੱਟ ਉਪਲਬਧ ਨਹੀਂ।",
"recording": "ਰਿਕਾਰਡ ਹੋ ਰਿਹਾ ਹੈ…",
},
"errors": {
"network": "ਨੈੱਟਵਰਕ ਗਲਤੀ। ਆਪਣਾ ਕੁਨੈਕਸ਼ਨ ਵੇਖੋ ਅਤੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
"unauthorized": "ਸੈਸ਼ਨ ਖਤਮ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਸਾਈਨ ਇਨ ਕਰੋ।",
"notFound": "ਨਹੀਂ ਮਿਲਿਆ।",
},
"crops": {
"rice": "ਚੌਲ",
"paddy": "ਝੋਨਾ",
"wheat": "ਕਣਕ",
"cotton": "ਨਰਮਾ",
"maize": "ਮੱਕੀ",
"sugarcane": "ਗੰਨਾ",
"tomato": "ਟਮਾਟਰ",
"potato": "ਆਲੂ",
"onion": "ਪਿਆਜ਼",
"soybean": "ਸੋਇਆਬੀਨ",
"groundnut": "ਮੂੰਗਫਲੀ",
"chilli": "ਮਿਰਚ",
},
}

emit("pa", T)
