# Complete Tamil (ta) catalog. Run from frontend/: python scripts/tr-ta.py
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emit_locale import emit

T = {
"common": {
"appName": "CropPilot",
"loading": "ஏற்றுகிறது…",
"retry": "மீண்டும் முயல்க",
"cancel": "ரத்து செய்",
"close": "மூடு",
"save": "சேமி",
"search": "தேடு",
"noData": "தரவு இல்லை.",
"errorGeneric": "ஏதோ தவறு நடந்தது. மீண்டும் முயல்க.",
"prevSlide": "முந்தைய ஸ்லைடு",
"nextSlide": "அடுத்த ஸ்லைடு",
"menu": "மொபைல் மெனுவை மாற்று",
"language": "மொழி",
"selectLanguage": "மொழியைத் தேர்வு செய்",
"commandPalette": "கமாண்ட் பலகை",
},
"navigation": {
"dashboard": "டாஷ்போர்டு",
"markets": "சந்தைகள்",
"weather": "வானிலை",
"disease": "நோய் கண்டறிதல்",
"schemes": "திட்டங்கள்",
"analytics": "பகுப்பாய்வு",
"maps": "வரைபடங்கள்",
"assistant": "AI உதவியாளர்",
},
"auth": {
"signIn": "உள்நுழை",
"signOut": "வெளியேறு",
"welcomeBack": "மீண்டும் வருக",
"signInSubtitle": "உங்கள் CropPilot கணக்கில் உள்நுழையுங்கள்",
"email": "மின்னஞ்சல்",
"password": "கடவுச்சொல்",
"enterPassword": "உங்கள் கடவுச்சொல்லை உள்ளிடுக",
"rememberMe": "என்னை நினைவில் கொள்",
"signingIn": "உள்நுழைகிறது…",
"signInBtn": "உள்நுழை",
"noAccount": "கணக்கு இல்லையா?",
"registerLink": "பதிவு செய்",
"emailRequired": "மின்னஞ்சல் தேவை",
"emailInvalid": "தவறான மின்னஞ்சல் முகவரி",
"passwordRequired": "கடவுச்சொல் தேவை",
"passwordMin": "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்",
"invalidCredentials": "தவறான விவரங்கள். மீண்டும் முயல்க.",
"createAccount": "கணக்கை உருவாக்கு",
"registerSubtitle": "CropPilot-இல் சேர்ந்து ஸ்மார்ட் விவசாயத்தைத் தொடங்குங்கள்",
"fullName": "முழு பெயர்",
"fullNamePlaceholder": "உங்கள் முழு பெயர்",
"phone": "தொலைபேசி எண்",
"selectState": "மாநிலத்தைத் தேர்வு செய்",
"selectDistrict": "மாவட்டத்தைத் தேர்வு செய்",
"createPassword": "கடவுச்சொல்லை உருவாக்கு",
"confirmPassword": "கடவுச்சொல்லை உறுதி செய்",
"confirmPasswordPlaceholder": "உங்கள் கடவுச்சொல்லை உறுதி செய்க",
"registerBtn": "பதிவு செய்",
"registering": "பதிவாகிறது…",
"haveAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
"signInLink": "உள்நுழை",
"nameRequired": "பெயர் தேவை",
"phoneInvalid": "தவறான தொலைபேசி எண்",
"phoneLong": "தொலைபேசி எண் மிக நீளமானது",
"selectStateRequired": "மாநிலத்தைத் தேர்வு செய்க",
"selectDistrictRequired": "மாவட்டத்தைத் தேர்வு செய்க",
"passwordMismatch": "கடவுச்சொற்கள் பொருந்தவில்லை",
"showPassword": "கடவுச்சொல்லைக் காட்டு",
"hidePassword": "கடவுச்சொல்லை மறை",
"nameMin": "முழு பெயர் குறைந்தது 2 எழுத்துகள் இருக்க வேண்டும்",
"phoneMin": "தொலைபேசி எண் குறைந்தது 10 இலக்கங்கள் இருக்க வேண்டும்",
"confirmRequired": "உங்கள் கடவுச்சொல்லை உறுதி செய்க",
"acceptTerms": "நிபந்தனைகளை ஏற்க வேண்டும்",
"registerFailed": "பதிவு தோல்வி. மீண்டும் முயல்க.",
"acceptPrefix": "நான் ஏற்கிறேன்",
"termsService": "சேவை நிபந்தனைகள்",
"termsAnd": "மற்றும்",
"privacyPolicy": "தனியுரிமைக் கொள்கை",
"creatingAccount": "கணக்கு உருவாகிறது…",
"authLayoutTitle": "CropPilot-க்கு வருக",
"authLayoutBody": "நவீன விவசாயத்திற்கான திறந்த மென்பொருள் தளம். டாஷ்போர்டுக்கு உள்நுழையுங்கள்.",
},
"landing": {
"badge": "இலவச திறந்த மென்பொருள்",
"tagline": "ஸ்மார்ட் விவசாயத்திற்கான திறந்த கருவிகள்.",
"heroBody": "பயிர் நலம், நோய் கண்டறிதல், வானிலை தகவல் மற்றும் பதிவான மண்டி சந்தை விலைகளுக்கான விவசாயி மைய தளம்.",
"openApp": "CropPilot-ஐத் திற",
"viewGithub": "GitHub-இல் பார்",
"featuresTitle": "நீங்கள் செய்யக்கூடியவை",
"featCrop": "பயிர் நலம்",
"featCropBody": "பயிர் நிலை மற்றும் தொடர்புடைய வயல் தகவலைக் கண்காணியுங்கள்.",
"featDisease": "நோய் கண்டறிதல்",
"featDiseaseBody": "ஆதரிக்கப்படும் நோய் கண்டறிதலுக்கு பயிர் படங்களைப் பகுப்பாய்வு செய்க.",
"featWeather": "வானிலை தகவல்",
"featWeatherBody": "விவசாய முடிவுகளுக்கு பயனுள்ள வானிலை தகவலைப் பார்க்கவும்.",
"featMarket": "சந்தை தகவல்",
"featMarketBody": "AGMARKNET அரசு திறந்த தரவு மூலம் பதிவான மண்டி விலைகளை ஆராயுங்கள்.",
"appTitle": "செயலி",
"appBody": "பண்ணை கண்ணோட்டம், வானிலை, பயிர் நலம், சந்தை பிரிவுகளுடன் CropPilot டாஷ்போர்டு.",
"appCaption": "மாதிரி தரவுடன் இயங்கும் CropPilot டாஷ்போர்டு.",
"appAlt": "மாதிரி தரவுடன் பண்ணை கண்ணோட்டம், வானிலை, பயிர் நலம், சந்தை பிரிவுகளைக் காட்டும் CropPilot டாஷ்போர்டு திரைப்படம்",
"marketTitle": "சந்தை தகவல்",
"marketBody": "மாநிலம், மாவட்டம், சந்தை, பொருள், ரகம், தரம், காலத்தால் சமீபத்திய பதிவான மண்டி விலைகளைப் பார்த்து, போக்கு மற்றும் சந்தை ஒப்பீட்டையும் காண்க.",
"marketSource": "மூலம்: அரசு திறந்த தரவு வழி AGMARKNET. விலைகள் கண்காணிப்பு தேதிகளுடன் பதிவான அவதானிப்புகள், நடப்பு சந்தை விலைகளாக ஒருபோதும் காட்டப்படுவதில்லை.",
"marketCta": "சந்தை விலைகளை ஆராய்க",
"whyTitle": "விவசாயிகளுக்காக உருவானது. வெளிப்படையாக உருவானது.",
"whyBody": "CropPilot இலவச திறந்த மென்பொருள்; விவசாய கருவிகளையும் தகவலையும் எளிதாக்குகிறது. MIT உரிமத்தில் இயங்குகிறது, உருவாக்கம் GitHub-இல் வெளிப்படையாக நடக்கிறது.",
"archTitle": "கட்டமைப்பு",
"archBody": "பண்ணை மற்றும் இட தரவுக்கு PostgreSQL, PostGIS, பின்னணி பணிகளுக்கு Celery, நோய் கண்டறிதலுக்கு PyTorch பார்வை மாதிரிகளுடன் FastAPI சேவையில் இயங்கும் Next.js முகப்பு. அனைத்தும் Docker Compose உடன் உள்ளூரில் இயங்கும்.",
"ossTitle": "GitHub-இல் திறந்த மூலம்",
"ossBody": "குறியீட்டைப் பாருங்கள், சிக்கல்களைப் பதிவு செய்யுங்கள், மேம்பாடுகளுக்கு பங்களியுங்கள். MIT உரிமம்.",
"footerTag": "திறந்த விவசாய தளம்.",
"footerDocs": "ஆவணங்கள்",
"navFeatures": "அம்சங்கள்",
"navArchitecture": "கட்டமைப்பு",
"toggleMenu": "மெனுவை மாற்று",
"footerLabel": "அடிக்குறிப்பு",
},
"dashboard": {
"welcomeBack": "மீண்டும் வருக, {name}",
"farmer": "விவசாயி",
"selectFarm": "பண்ணையைத் தேர்வு செய்",
"allFarms": "அனைத்து பண்ணைகள்",
"wFarmOverview": "பண்ணை கண்ணோட்டம்",
"wWeather": "இன்றைய வானிலை",
"wCropHealth": "பயிர் நலம்",
"wDiseaseAlerts": "நோய் எச்சரிக்கைகள்",
"wRevenue": "வருவாய்",
"wExpenses": "செலவுகள்",
"wNetProfit": "நிகர லாபம்",
"wYield": "மகசூல்",
"wMarketTrends": "சந்தை போக்குகள்",
"wSchemes": "திட்ட பரிந்துரைகள்",
"wNotifications": "அறிவிப்புகள்",
"wQuickActions": "விரைவு செயல்கள்",
"vsLastMonth": "கடந்த மாதத்துடன் ஒப்பிடுகையில்",
"totalYield": "மொத்த மகசூல்",
"perHectare": "ஹெக்டேருக்கு",
"noAlerts": "செயலில் நோய் எச்சரிக்கை இல்லை",
"cropsHealthy": "உங்கள் பயிர்கள் நலமாக உள்ளன",
"noNotifications": "அறிவிப்புகள் இல்லை",
"qaScan": "பயிர்களை ஸ்கேன் செய்",
"qaWeather": "வானிலையைப் பார்",
"qaMarkets": "சந்தைகளைப் பார்",
"qaAssistant": "AI உதவியாளர்",
"statFarms": "மொத்த பண்ணைகள்",
"statArea": "மொத்த பரப்பு",
"statPlots": "செயலில் மனைகள்",
"statSeason": "நடப்பு பருவம்",
"notifMarkRead": "அனைத்தையும் படித்ததாகக் குறி",
"marginLabel": "லாபம்:",
},
"weather": {
"title": "வானிலை",
"subtitle": "உங்கள் பண்ணைக்கான நேரடி வானிலை தரவு மற்றும் முன்னறிவிப்பு",
"searchLocation": "இடத்தைத் தேடு…",
"noLocations": "இடங்கள் இல்லை",
"hourly": "மணிநேர முன்னறிவிப்பு",
"details": "வானிலை விவரங்கள்",
"rainProbability": "மழை வாய்ப்பு",
"windSpeed": "காற்று வேகம்",
"humidity": "ஈரப்பதம்",
"uvIndex": "UV குறியீடு",
"pressure": "அழுத்தம்",
"visibility": "தெரிவுநிலை",
"weekly": "7-நாள் முன்னறிவிப்பு",
"feelsLike": "{temp}° போல் உணரப்படுகிறது",
"highShort": "அதிக: {temp}°",
"lowShort": "குறைவு: {temp}°",
},
"disease": {
"title": "நோய் கண்டறிதல்",
"subtitle": "AI நோய் கண்டறிதலுக்கு பயிர் படங்களைப் பதிவேற்றுக அல்லது எடுங்கள்",
"newDetection": "புதிய கண்டறிதல்",
"analyzing": "உங்கள் பயிர் படம் பகுப்பாய்வு செய்யப்படுகிறது…",
"analyzingBody": "AI நோய் வடிவங்களை ஸ்கேன் செய்கிறது",
"readyTitle": "கண்டறிய தயார்",
"readyBody": "உடனடி AI நோய் கண்டறிதல் மற்றும் சிகிச்சை பரிந்துரைகளுக்கு பாதித்த பயிரின் புகைப்படத்தைப் பதிவேற்றுக அல்லது எடுங்கள்",
"confidence": "AI நம்பிக்கை",
"cameraTitle": "கேமரா பிடிப்பு",
"cameraBody": "பாதித்த பயிரின் புகைப்படம் எடுங்கள்",
"cameraHint": "பாதித்த இலைகள் அல்லது பழங்களை சட்டத்தில் வையுங்கள்",
"activateCamera": "கேமராவைத் தொடங்கு",
"capture": "பிடி",
"retake": "மீண்டும் எடு",
"uploadTitle": "படத்தைப் பதிவேற்று",
"uploadHint": "இழுத்து விடுக அல்லது உலாவுக",
"dropHint": "பதிவேற்ற இழுத்து விடுக அல்லது கிளிக் செய்க",
"dropFormats": "JPG, PNG, WEBP 10MB வரை",
"changeImage": "படத்தை மாற்று",
"fileTooBig": "கோப்பு 10MB-க்குள் இருக்க வேண்டும்.",
"resultTitle": "கண்டறிதல் முடிவு",
"detectedDisease": "கண்ட நோய்",
"confidenceScore": "நம்பிக்கை மதிப்பெண்",
"treatmentAvailable": "சிகிச்சை பரிந்துரை உள்ளது",
"aiAnalysis": "AI பகுப்பாய்வு",
"symptoms": "அறிகுறிகள்",
"recommendedActions": "பரிந்துரைக்கப்பட்ட செயல்கள்",
"preventiveMeasures": "தடுப்பு நடவடிக்கைகள்",
"historyTitle": "கண்டறிதல் வரலாறு",
"thDate": "தேதி",
"thCrop": "பயிர்",
"thDisease": "நோய்",
"thConfidence": "நம்பிக்கை",
"thStatus": "நிலை",
"sevLow": "குறைவு",
"sevModerate": "மிதம்",
"sevHigh": "அதிகம்",
"sevCritical": "மிக ஆபத்து",
"pastDetections": "{count} கடந்த கண்டறிதல்கள்",
"searchHistory": "பயிர் அல்லது நோயால் தேடு…",
"noDetections": "கண்டறிதல்கள் இல்லை",
"stageCheckingPhoto": "புகைப்பட தரம் சரிபார்க்கப்படுகிறது…",
"stageAnalyzing": "படம் பகுப்பாய்வு செய்யப்படுகிறது…",
"cropHintLabel": "பயிர் (விருப்பம் - சரியான நிபுணரைத் தேர்வு உதவும்)",
"cropHintAuto": "தானியங்கி (குறிப்பு இல்லை)",
"unknownCrop": "தெரியாத பயிர்",
"uncertainTitle": "CropPilot சிக்கலை உறுதியாகக் கண்டறிய முடியவில்லை",
"uncertainBody": "கண்டறிதலுக்கு பட ஆதாரம் போதவில்லை. கீழே உள்ளவை யூகங்கள், கண்டறிதல் அல்ல.",
"possibleCauses": "சாத்தியமான மாற்றுகள்",
"analyzeAnotherHint": "நல்ல வெளிச்சத்தில் ஒரு பாதித்த இலையின் நெருக்க புகைப்படத்துடன் மீண்டும் முயல்க.",
"supportedCrops": "சரிபார்ந்த நிபுணர் உள்ள பயிர்கள்",
"capabilitiesOffline": "கண்டறிதல் சேவை பட்டியலை அடைய முடியவில்லை. ஆனாலும் பதிவேற்ற முயலலாம்.",
"bandHigh": "அதிகம்",
"bandMedium": "மிதம்",
"bandLow": "குறைவு",
"bandUnverified": "சரிபாராத மதிப்பெண்",
"bandUnknown": "தெரியாது",
"statusDiagnosed": "சாத்தியமான கண்டறிதல்",
"statusProbable": "சாத்தியம் - சரிபார்ப்பு தேவை",
"statusUncertain": "உறுதியில்லை",
"statusInsufficientImage": "புகைப்படம் பயனற்றது",
"statusUnsupportedCrop": "பயிர் இன்னும் ஆதரிக்கப்படவில்லை",
"statusError": "பகுப்பாய்வு தோல்வி",
"uncalibratedScore": "மாதிரி மதிப்பெண் (அளவிடப்படாதது)",
"uncalibratedScoreHint": "மூல மாதிரி வெளியீடு, அளவிட்ட நிகழ்தகவு அல்ல.",
"uploadedPhoto": "பதிவேற்றிய புகைப்படம்",
"evidenceTitle": "பகுப்பாய்வு விவரங்கள்",
"routingMode": "வழிப்படுத்தல்",
"modelsUsed": "பயன்படுத்திய மாதிரிகள்",
"fieldValidation": "வயல் சரிபார்ப்பு",
"imageQuality": "பட தரம்",
"latencyLabel": "பகுப்பாய்வு நேரம்",
"researchBadge": "ஆராய்ச்சி மாதிரி",
"notVerified": "சரிபார்க்கப்படவில்லை",
"guidanceFor": "வழிகாட்டல்:",
"guidanceSource": "மூலம்",
"similarConditions": "ஒத்த நிலைகள்",
"noGuidance": "CropPilot-இடம் இந்த கண்டறிதலுக்கு சரிபார்ந்த வழிகாட்டல் இன்னும் இல்லை.",
"imageNotRetained": "அமர்வு வரலாறு மட்டும் - படங்கள் வைக்கப்படுவதில்லை.",
"errNetwork": "பிணைய பிழை. இணைப்பைச் சரிபார்த்து மீண்டும் முயல்க.",
"errTooLarge": "படம் மிகப் பெரியது. 10 MB-க்குள் புகைப்படம் பயன்படுத்துக.",
"errPoorQuality": "பகுப்பாய்வுக்கு புகைப்பட தரம் மிக மோசம். ஒரு பாதித்த இலையின் நெருக்க படம் எடுங்கள்.",
"errUnsupportedCrop": "CropPilot-இடம் அந்த பயிருக்கு சரிபார்ந்த நிபுணர் இன்னும் இல்லை.",
"errInvalid": "அந்த கோப்பை படமாகப் படிக்க முடியவில்லை. JPG அல்லது PNG முயல்க.",
"errNoModel": "தற்போது சரிபார்ந்த கண்டறிதல் மாதிரி இல்லை. பின்னர் முயல்க.",
"errServer": "பகுப்பாய்வு தோல்வி. தெளிவான புகைப்படத்துடன் மீண்டும் முயல்க.",
"analysisIncomplete": "பகுப்பாய்வு முழுமையடையவில்லை",
"noVerifiedDiagnosis": "சரிபார்ந்த கண்டறிதல் இல்லை",
"analysisStatusLabel": "பகுப்பாய்வு நிலை",
"cropLabel": "பயிர்",
"cropNotIdentified": "அடையாளம் காணப்படவில்லை",
"cropUnsupported": "ஆதரிக்கப்படவில்லை",
"cropSourceUser": "நீங்கள் தேர்வு (வழிப்படுத்தல் குறிப்பு, மாதிரி ஆதாரம் அல்ல)",
"cropSourceUnknown": "இந்த புகைப்படத்திலிருந்து அடையாளம் காணப்படவில்லை",
"selectCropPrompt": "பயிர் தெரியுமா? தேர்வு CropPilot சரியான நிபுணரைத் தேர்வு உதவும்.",
"analyzeAgain": "மீண்டும் பகுப்பாய்வு",
"retryAnalysis": "மீண்டும் முயல்க",
"coverageBadge": "மாதிரி உள்ளடக்கம் இல்லை",
"serviceBadge": "சேவை இல்லை",
"temporaryAnalysisFailure": "பகுப்பாய்வு தற்காலிக தோல்வி",
"modelFailureBody": "ஆதரிக்கப்பட்ட நோய் மாதிரி இருந்தது, ஆனால் பகுப்பாய்வு முடியவில்லை.",
"photoNeedsImprovement": "புகைப்பட மேம்பாடு தேவை",
"noSpecialistAvailable": "CropPilot-இடம் இந்த பயிருக்கு தற்போது சரிபார்ந்த நோய் மாதிரி இல்லை.",
"cropUnknownNoModel": "CropPilot இந்த புகைப்படத்திலிருந்து பயிரை அடையாளம் காண முடியவில்லை, எனவே சரிபார்ந்த நோய் மாதிரியைத் தேர்வு முடியவில்லை.",
"noCoverageTitle": "பயிர் தற்போது ஆதரிக்கப்படவில்லை",
"lowConfidenceTitle": "கண்டறிதல் உறுதியில்லை",
"lowConfidenceBody": "நம்பகமான கண்டறிதலுக்கு உள்ள மாதிரிகள் போதுமான உடன்படவில்லை.",
"confidenceNotAvailable": "இல்லை",
"cropIdentification": "பயிர் அடையாளம்",
"cropSource": "பயிர் மூலம்",
"routingLabel": "வழிப்படுத்தல்",
"specialistsLabel": "நிபுணர்கள்",
"specialistsNone": "தகுதியானவர் யாருமில்லை",
"calibrationLabel": "அளவீடு",
"calibrationUnavailable": "இல்லை (மூல மாதிரி மதிப்பெண்கள்)",
"vlmLabel": "VLM மாற்று",
"vlmNotConfigured": "அமைக்கப்படவில்லை",
"vlmUsed": "மதிப்பாய்வுக்கு பயன்",
"vlmNotUsed": "பயன்படவில்லை",
"coverageTitle": "நடப்பு மாதிரி உள்ளடக்கம்",
"coverageBody": "{count} சரிபார்ந்த தயாரிப்பு மாதிரி பாதைகள். உள்ளடக்கம் குறைவு, விரிவடைகிறது.",
"whyLabel": "ஏன்?",
"whatToDoLabel": "நீங்கள் செய்யக்கூடியவை",
"errNoCoverage": "CropPilot-இடம் இந்த பயிருக்கு தற்போது சரிபார்ந்த நோய் மாதிரி இல்லை.",
"errModelFailure": "ஆதரிக்கப்பட்ட நோய் மாதிரி இருந்தது, ஆனால் பகுப்பாய்வு முடியவில்லை. மீண்டும் முயல்க.",
"noDiagnosis": "கண்டறிதல் இல்லை",
"statusNotSupported": "ஆதரிக்கப்படவில்லை",
"statusFailed": "தோல்வி",
"downloadSummary": "சுருக்கத்தைப் பதிவிறக்கு",
"shareSummary": "சுருக்கத்தைப் பகிர்",
"summaryCopied": "சுருக்கம் கிளிப்போர்டில் நகல்",
"analyzeAnotherPhoto": "வேறு புகைப்படத்தைப் பகுப்பாய்வு",
"stepsTitle": "பகுப்பாய்வு படிகள்",
"stepUpload": "புகைப்படம் பதிவேறுகிறது",
"stepQuality": "பட தரம் சரிபார்க்கப்படுகிறது",
"stepRouting": "நோய் நிபுணர்கள் தேர்வு",
"stepAnalysis": "பகுப்பாய்வு நடக்கிறது",
"stepVerify": "முடிவு சரிபார்ப்பு",
"supportedCropsNote": "சரிபார்ந்த நிபுணர் உள்ள பயிர்கள்",
"cropUnknownWeakEvidence": "சரியான நோய் நிபுணரைத் தேர்வு போதிய ஆதாரத்துடன் CropPilot பயிரை அடையாளம் காண முடியவில்லை.",
"unknownCropWhy": "உள்ள மாதிரி பலவீன முடிவுகள் தந்தது, ஆனால் படம் பயிரை உறுதி செய்ய போதிய ஆதாரம் தரவில்லை.",
"modelOutputs": "மாதிரி வெளியீடுகள்",
"modelOutputsInterpretation": "வெளிப்படைக்கு மூல மாதிரி வெளியீடுகள் காட்டப்பட்டுள்ளன; அவை சரிபார்ந்த நோய் கண்டறிதல் அல்ல.",
"rawScoreLabel": "மூல மதிப்பெண்",
},
"assistant": {
"title": "AI உதவியாளர்",
"placeholder": "விலைகள், வானிலை, திட்டங்கள் பற்றி கேளுங்கள்…",
"send": "அனுப்பு",
"offline": "உதவியாளர் இல்லை. பின்னர் முயல்க.",
"offlineBackend": "உதவியாளர் இல்லை. பின்தளம் இயங்குகிறதா பாருங்கள்.",
"sources": "மூலங்கள்",
"newChat": "புதிய அரட்டை",
"welcome": "வணக்கம்! நான் **CropPilot AI** — உங்கள் அறிவார்ந்த விவசாய உதவியாளர். 🌾\n\nஉதவ முடியும்:\n\n- **பயிர் மேலாண்மை** — விதைப்பு, நீர்ப்பாசனம், உர அட்டவணை\n- **நோய் கண்டறிதல்** — பயிர் நோய்களைக் கண்டு சிகிச்சை\n- **சந்தை பகுப்பாய்வு** — நேரடி மண்டி விலைகள், போக்குகள்\n- **அரசு திட்டங்கள்** — தகுதி திட்டங்களைக் காண்க\n- **வானிலை நுண்ணறிவு** — முன்னறிவிப்பு, பயிர் தாக்கம்\n\nஇன்று பண்ணை பற்றி என்ன தெரிய வேண்டும்?",
"welcomeTitle": "CropPilot-க்கு வருக",
"welcomePreview": "வணக்கம்! நான் CropPilot AI…",
"newChatTitle": "புதிய அரட்டை",
"newChatPreview": "உரையாடலைத் தொடங்கு…",
"promptPaddy": "கோதுமை சாகுபடி சிறந்த முறைகள்",
"promptDisease": "தக்காளி இலை கருகலைக் கண்டறி",
"promptMarket": "நடப்பு மண்டி விலைகள்",
"promptSchemes": "விவசாயிகளுக்கு அரசு திட்டங்கள்",
"suggestTitle": "விவசாயம் பற்றி எதுவும் கேளுங்கள் — பயிர்கள், நோய்கள், சந்தைகள், திட்டங்கள்",
"cardCrop": "பயிர் ஆலோசனை",
"cardCropBody": "கோதுமை சாகுபடி சிறந்த முறைகள்",
"cardCropQuery": "கோதுமை சாகுபடி சிறந்த முறைகள் யாவை?",
"cardDisease": "நோய் உதவி",
"cardDiseaseBody": "தக்காளியில் இலை கருகலைக் கண்டு சிகிச்சை",
"cardDiseaseQuery": "தக்காளி செடிகளில் இலை கருகலை எப்படி கண்டு சிகிச்சை?",
"cardMarket": "சந்தை கேள்விகள்",
"cardMarketBody": "நெல், கோதுமை நடப்பு மண்டி விலைகள்",
"cardMarketQuery": "தெலுங்கானாவில் நெல், கோதுமை நடப்பு மண்டி விலைகள் என்ன?",
"cardScheme": "திட்ட தகவல்",
"cardSchemeBody": "சிறு விவசாயிகளுக்கு அரசு திட்டங்கள்",
"cardSchemeQuery": "இந்தியாவில் சிறு விவசாயியாக எந்த அரசு திட்டங்களுக்கு தகுதி?",
"cardWeather": "வானிலை கேள்வி",
"cardWeatherBody": "வரவிருக்கும் வானிலை, பயிர் தாக்கம்",
"cardWeatherQuery": "வரவிருக்கும் வானிலை என் காரீப் பயிர்களை எப்படி பாதிக்கும்?",
"cardPlan": "பண்ணை திட்டம்",
"cardPlanBody": "பயிர் சுழற்சி, மண் மேலாண்மை குறிப்புகள்",
"cardPlanQuery": "பண்ணைக்கு என்ன பயிர் சுழற்சி பின்பற்ற?",
"sideNewChat": "புதிய அரட்டை",
"sideSearch": "உரையாடல்களைத் தேடு…",
"sideNoFound": "உரையாடல்கள் இல்லை",
"sideNoYet": "இன்னும் உரையாடல் இல்லை",
"sideClose": "பக்கப்பட்டியை மூடு",
"sideOpen": "பக்கப்பட்டியைத் திற",
"sideDelete": "உரையாடலை நீக்கு",
"inputDefault": "பயிர்கள், நோய்கள், சந்தைகள், திட்டங்கள் பற்றி கேளுங்கள்…",
"voiceError": "குரல் பிழை",
"voiceUnreachable": "குரல் சேவை எட்டவில்லை",
"micDenied": "மைக் அனுமதி மறுப்பு",
"paletteSearch": "பக்கங்களைத் தேடுக அல்லது கட்டளையைத் தட்டுக…",
"paletteEmpty": "முடிவுகள் இல்லை.",
"errorTitle": "ஏதோ தவறு",
"errorFallback": "எதிர்பாரா பிழை. மீண்டும் முயல்க.",
"notFoundTitle": "பக்கம் இல்லை",
"notFoundBody": "நீங்கள் தேடும் பக்கம் இல்லை அல்லது நகர்ந்துள்ளது.",
"goDashboard": "டாஷ்போர்டுக்குச் செல்",
"goHome": "முகப்புக்குச் செல்",
"loadingApp": "CropPilot ஏறுகிறது…",
"themeToggle": "தீமை மாற்று",
"themeCurrent": "நடப்பு தீம்: {theme}. {next}-க்கு கிளிக்",
"themeLight": "வெளிச்சம்",
"themeDark": "இருள்",
"themeSystem": "கணினி",
"attachFiles": "கோப்புகளை இணை",
"attachDocs": "படங்கள் & ஆவணங்கள்",
"takePhoto": "புகைப்படம் எடு",
"copyResponse": "பதிலை நகல்",
"copied": "நகலானது",
"helpful": "பயனுள்ளது",
"notHelpful": "பயனில்லை",
"fileTypeUnsupported": "\"{type}\" கோப்பு வகை ஆதரிக்கப்படவில்லை",
"sourcesCount": "{count} மூலம்",
"sourcesCountPlural": "{count} மூலங்கள்",
},
"maps": {
"loading": "ஏறுகிறது…",
"searchLocation": "கிராமம், ஊர், சந்தை அல்லது PIN தேடு",
"clearSearch": "தேடலை அழி",
"searchFailed": "இடம் இல்லை. வேறு தேடு.",
"noResults": "பொருந்தும் இடங்கள் இல்லை.",
"useMyLocation": "என் இடத்தைப் பயன்",
"resetView": "இந்திய காட்சியை மீட்டமை",
"fullscreen": "முழுத்திரை வரைபடம்",
"mapLabel": "இந்திய CropPilot விவசாய வரைபடம்",
"location": "இடம்",
"locationInsights": "இட நுண்ணறிவு",
"placeUnavailable": "இடப் பெயர் இல்லை — ஆயங்கள் காட்டப்பட்டுள்ளன.",
"weather": "வானிலை",
"weatherMapTitle": "வானிலை வரைபடம்",
"rainRadar": "மழை ரேடார்",
"weatherUnavailable": "வானிலை தகவல் தற்காலிகமில்லை.",
"humidity": "ஈரப்பதம்",
"wind": "காற்று",
"rain": "மழை",
"feelsLike": "உணரப்படுவது",
"wmoCode": "WMO குறியீடு {code}",
"updatedJustNow": "இப்போது புதுப்பிப்பு",
"updatedMinutesAgo": "{count} நிமிடம் முன் புதுப்பிப்பு",
"updatedHoursAgo": "{count} மணி முன் புதுப்பிப்பு",
"sourceOpenMeteo": "மூலம்: Open-Meteo",
"nearbyMarkets": "அருகிலுள்ள சந்தைகள்",
"commodityFilter": "பொருளால் வடிகட்டு",
"allCommodities": "அனைத்து பொருட்கள்",
"searchArea": "இந்த பகுதியில் தேடு",
"marketsUnavailable": "அருகிலுள்ள சந்தை தரவு ஏற்ற முடியவில்லை.",
"noMappedMarkets": "அருகில் வரைபட ஆயங்கள் உள்ள சந்தைகள் இல்லை.",
"noReportedPrice": "இந்த சந்தைக்கு பதிவான விலை இன்னும் இல்லை.",
"latestReported": "சமீப பதிவு: {date}",
"sourceAgmarknet": "மூலம்: AGMARKNET",
"quintal": "குவிண்டால்",
"unmappedNote": "இங்கு மேலும் {count} சந்தைகளுக்கு வரைபட ஆயங்கள் இன்னும் இல்லை; அவை சந்தை நுண்ணறிவில் பட்டியல்.",
"closeDetails": "சந்தை விவரங்களை மூடு",
"viewMarketIntel": "சந்தை நுண்ணறிவைப் பார்",
"cropPilotActions": "CropPilot செயல்கள்",
"openMarketIntel": "சந்தை நுண்ணறிவு",
"analyzeDisease": "பயிர் நோய் பகுப்பாய்வு",
"askAssistant": "CropPilot AI-ஐக் கேள்",
"legendSelected": "தேர்ந்த இடம்",
"legendMarkets": "சந்தைகள்",
"markets": "சந்தைகள்",
"toggleMarkets": "சந்தை குறிகளை மாற்று",
"pickHint": "இடத்தைத் தேர்வு வரைபடத்தில் கிளிக்",
"collapseSheet": "பலகையைச் சுருக்கு",
"expandSheet": "பலகையை விரி",
"geoDenied": "இட அணுகல் மறுப்பு. அதற்கு பதில் இடத்தைத் தேடலாம்.",
"geoUnavailable": "நடப்பு இடம் இல்லை. தேட முயல்க.",
"geoTimeout": "இட கோரிக்கை காலாவதி. மீண்டும் முயல்க அல்லது தேடுக.",
"geoUnsupported": "இந்த உலாவியில் புவிஇடம் ஆதரிக்கப்படவில்லை. தேடுக.",
"mapUnavailable": "இந்த சாதனத்தில் ஊடாடும் வரைபடம் இல்லை (WebGL அணைப்பு). தேடல், இட தகவல் கீழே செயல்படும்.",
"agriSnapshot": "விவசாய கண்ணோட்டம்",
"commonCrops": "பொது பயிர்கள்",
"soil": "மண்",
"rainfall": "மழை",
"seasonRain": "{season}-இல் {mm} மிமீ",
"forecastLabel": "முன்னறிவிப்பு",
"texture": "அமைப்பு",
"organicCarbon": "கரிம கார்பன்",
"clay": "களிமண்",
"sand": "மணல்",
"silt": "வண்டல்",
"nitrogen": "நைட்ரஜன்",
"sourceSoilGrids": "மூலம்: SoilGrids",
"resolutionM": "தீர்மானம்: {m} மீ",
"modelledEstimateNote": "மாதிரி மதிப்பீடு, ஆய்வக மண் சோதனை அல்ல",
"modelledBadge": "மாதிரி சார்ந்த",
"soilUnavailable": "இந்த இடத்திற்கு மண் தரவு இல்லை.",
"today": "இன்று",
"last7days": "கடந்த 7 நாட்கள்",
"thisMonth": "இந்த மாதம்",
"season": "பருவம்",
"reanalysisNote": "மறுபகுப்பாய்வு/முன்னறிவிப்பு மதிப்பீடு, நிலைய தரவு அல்ல",
"rainfallUnavailable": "இந்த இடத்திற்கு மழை தரவு இல்லை.",
"crops": "பயிர்கள்",
"commonlyTraded": "பகுதி மண்டிகளில் அண்மையில் வர்த்தக பொருட்கள்",
"cropsUnavailable": "இந்த பகுதிக்கு பயிர் வர்த்தக தரவு இல்லை.",
"suitabilityTitle": "சுற்றுச்சூழல் ஏற்பு மதிப்பீடு",
"water": "நீர் ஆதாரங்கள்",
"waterUnavailable": "இந்த இடத்திற்கு நீர் தரவு இல்லை.",
"waterNote": "நிலத்தடி நீர் அவதானிப்புகள் இடைவெளியில்; நீர்த்தேக்க சேமிப்பு பண்ணை நீர்ப்பாசனத்தைக் குறிக்காது.",
"diseaseContext": "நோய் சூழல்",
"diseaseUnavailable": "இந்த பகுதிக்கு நோய் சூழல் இல்லை.",
"selectedLocation": "தேர்ந்த இடம்",
"viewFullMap": "முழு வரைபடம் பார்",
"yourLocation": "உங்கள் இடம்",
},
"markets": {
"title": "சந்தை நுண்ணறிவு",
"subtitle": "AGMARKNET சமீப பதிவான மண்டி விலைகள்",
"state": "மாநிலம்",
"district": "மாவட்டம்",
"market": "சந்தை",
"commodity": "பொருள்",
"days": "நாட்கள்",
"latestPrice": "சமீப பதிவு விலை: {price} குவிண்டாலுக்கு",
"arrivalDate": "வருகை தேதி: {date}",
"empty": "தரவுத்தளத்தில் பொருந்தும் சமீப பதிவு விலை இல்லை.",
"unavailableTitle": "சந்தை தரவு தற்போது இல்லை",
"tryAgain": "மீண்டும் முயல்க",
"signInRequired": "உள்நுழைவு தேவை",
"signInPrompt": "சந்தை நுண்ணறிவைப் பார்க்க உள்நுழையுங்கள்.",
"signInNeeded": "சந்தை நுண்ணறிவைப் பார்க்க உள்நுழையுங்கள்.",
"offline": "சந்தை சேவையை அடைய முடியவில்லை. இணைப்பு மீண்டதும் சேமித்த அவதானிப்புகள் தெரியும்.",
"loadError": "இந்த பகுதியை ஏற்ற ஏதோ தவறு. சேமித்த அவதானிப்புகள் பாதுகாப்பு.",
"loadErrorShort": "இந்த பகுதியை ஏற்ற ஏதோ தவறு.",
"allStates": "அனைத்து மாநிலங்கள்",
"allDistricts": "அனைத்து மாவட்டங்கள்",
"selectStateFirst": "முதலில் மாநிலம் தேர்வு",
"allMarkets": "அனைத்து சந்தைகள்",
"selectCommodity": "பொருள் தேர்வு",
"allVarieties": "அனைத்து ரகங்கள்",
"allGrades": "அனைத்து தரங்கள்",
"variety": "ரகம்",
"grade": "தரம்",
"statesReporting": "அறிக்கை மாநிலங்கள்",
"marketsReporting": "அறிக்கை சந்தைகள்",
"commoditiesReported": "பதிவான பொருட்கள்",
"latestObservation": "சமீப அவதானிப்பு",
"storedObservations": "சேமித்த அவதானிப்புகள் காட்டப்படுகின்றன",
"storedObservationsBody": "இந்த தேர்வுக்கு மூலம் அண்மை அவதானிப்பு வெளியிடவில்லை. கீழே மதிப்புகள் சமீப சேமித்த அறிக்கைகள், புதிய விலைகள் அல்ல.",
"noRecentPrice": "அண்மை பதிவு விலை இல்லை",
"emptyHint": "வேறு மாநிலம், மாவட்டம், பொருள் அல்லது சந்தை முயல்க. அடுத்த வெளியீட்டுக்குப் பின் புதிய அறிக்கைகள் இங்கே தெரியும்.",
"selectionSummary": "தேர்வு சுருக்கம்",
"reportedMarkets": "பதிவான சந்தைகள்",
"observationsInTable": "அட்டவணை அவதானிப்புகள்",
"trendPoints": "போக்கு புள்ளிகள்",
"comingLater": "பின்னர் வருகிறது",
"comingLaterBody": "விலை முன்னறிவிப்பு, விற்பனை பரிந்துரைகள் இந்த காட்சியில் இன்னும் இல்லை. இங்கே பதிவான அவதானிப்புகள் மட்டும்.",
"searchStates": "மாநிலங்களைத் தேடு…",
"searchDistricts": "மாவட்டங்களைத் தேடு…",
"searchMarkets": "சந்தைகளைத் தேடு…",
"noMatchState": "பொருந்தும் மாநிலம் இல்லை.",
"noMatchDistrict": "பொருந்தும் மாவட்டம் இல்லை.",
"noMatchMarket": "பொருந்தும் சந்தை இல்லை.",
"tableSearch": "ஏற்றிய முடிவுகளில் தேடு…",
"thMin": "குறைந்த ரூ",
"thMax": "அதிக ரூ",
"thModal": "மாதிரி ரூ",
"thArrivals": "வருகை",
"thObserved": "அவதானிப்பு",
"showingCount": "{total}-இல் {from}–{to}",
"prevPage": "முந்தைய பக்கம்",
"nextPage": "அடுத்த பக்கம்",
"priceRs": "ரூ{value}",
"minMaxLine": "குறைந்த ரூ{min} · அதிக ரூ{max}",
"arrivalsLine": "வருகை: {value}",
"freshNone": "அண்மை அவதானிப்பு இல்லை",
"freshLatest": "சமீப பதிவு: {date}",
"freshStale": "தரவு தாமதமாகலாம்",
"sourceLabel": "மூலம்: {name}",
"sourceBody": "பதிவான மண்டி விலைகள் சந்தைகள் வெளியிட்ட அவதானிப்புகள், தாமதமாகலாம். எதிர்கால விலை உத்தரவாதம் இல்லை.",
"sourceResource": "வளம்: {id}",
"cmpNoData": "ஒப்பீடு இல்லை",
"cmpNoDataBody": "இந்த தேர்வுக்கு பதிவான விலைகள் இன்னும் இல்லை.",
"cmpTitle": "சந்தை ஒப்பீடு",
"cmpBody": "பொருந்தும் ரகம், தரம், அலகு வரிசைகள் மட்டும் ஒப்பிடப்படும். விலைகள் சந்தைக்கு சமீப பதிவு அவதானிப்புகள்.",
"cmpMinMax": "குறைந்த முதல் அதிக ரூ",
"histNoData": "விலை வரலாறு இல்லை",
"histNoDataBody": "தேர்ந்த சந்தை, பொருளுக்கு இந்த காலத்தில் பதிவான அவதானிப்புகள் இல்லை.",
"histTitle": "பதிவான மாதிரி விலை போக்கு",
"histUnit": "ரூ ஒரு {unit}-க்கு",
"histModal": "மாதிரி",
"histMax": "அதிக",
"histMin": "குறைவு",
"histCount": "{count} அவதானிப்புகள்",
"histObserved": "{label} அன்று அவதானிப்பு",
"cmpUnspecified": "குறிப்பிடா ரகம், தரம்",
},
"schemes": {
"title": "அரசு திட்டங்கள்",
"subtitle": "விவசாய திட்டங்கள், மானியங்கள், நல திட்டங்களைக் கண்டு விண்ணப்பியுங்கள்",
"search": "பெயர், விளக்கம், குறிச்சொல்லால் திட்டங்களைத் தேடு…",
"all": "அனைத்தும்",
"noFound": "திட்டங்கள் இல்லை",
"noFoundBody": "தேடல் அல்லது வடிகட்டியை மாற்றுக",
"viewDetail": "விவரங்களைப் பார்",
"eligibility": "தகுதி",
"benefits": "பலன்கள்",
"howToApply": "விண்ணப்பிப்பது எப்படி",
"close": "மூடு",
"moreDetails": "மேலும் விவரங்கள்",
"applicationProcess": "விண்ணப்ப செயல்:",
"funding": "நிதி:",
"checkEligibility": "தகுதியைப் பார்",
"ministry": "அமைச்சகம்:",
"eligibilityCriteria": "தகுதி அளவுகோல்கள்",
"requiredDocuments": "தேவை ஆவணங்கள்",
"active": "செயலில்",
"inactive": "செயலற்ற",
"applyNow": "இப்போது விண்ணப்பி",
},
"analytics": {
"title": "பகுப்பாய்வு",
"subtitle": "பண்ணை செயல்திறன் விரிவான நுண்ணறிவு",
"tabRevenue": "வருவாய்",
"tabYield": "மகசூல்",
"tabCropHealth": "பயிர் நலம்",
"tabWater": "நீர் பயன்",
"tabFertilizer": "உர பயன்",
"tabMarket": "சந்தை பகுப்பாய்வு",
"statRevenue": "மொத்த வருவாய்",
"statYield": "சராசரி மகசூல்/ஹெ",
"statHealth": "நல மதிப்பெண்",
"statWater": "நீர் திறன்",
"rangeCustom": "தனிப்பயன்",
"chRevenueMonthly": "மாத வருவாய்",
"chRevenueByCrop": "பயிர் வருவாய்",
"chRevenueCumulative": "திரட்டு வருவாய்",
"chYieldByCrop": "பயிர் மகசூல்",
"chYieldTrend": "மகசூல் போக்கு",
"chYieldVsTarget": "மகசூல் vs இலக்கு",
"chYieldPerHa": "ஹெக்டேர் மகசூல்",
"chYieldTopBottom": "சிறந்த & குறைந்த பயிர்கள்",
"chHealthOverall": "ஒட்டுமொத்த நலம்",
"chHealthRadar": "நல அளவு ரேடார்",
"chHealthTrend": "நல மதிப்பெண் போக்கு",
"chHealthByPlot": "மனை நலம்",
"chHealthTimeline": "நல எச்சரிக்கை காலவரிசை",
"chPriceTrends": "விலை போக்குகள் - முதல் 5 பொருட்கள்",
"chPriceHeatmap": "விலை வெப்ப வரைபடம் - பொருள் vs மாதம்",
"chBestTimes": "சிறந்த விற்பனை நேரங்கள்",
"chTrade": "ஏற்றுமதி / இறக்குமதி பகுப்பாய்வு",
"chVolume": "வர்த்தக அளவு",
"chInsights": "AI நுண்ணறிவுகள்",
"chWaterDaily": "மழையுடன் தின நீர் பயன்",
"chWaterByCrop": "பயிர் நீர் பயன்",
"chWaterEff": "நீர் திறன் (கிலோ மகசூலுக்கு லிட்டர்)",
"chWaterSave": "நீர் சேமிப்பு பரிந்துரைகள்",
"chWaterSchedule": "அட்டவணை பரிந்துரைகள்",
"chFertBreakdown": "உர வகை பிரிவு",
"chFertCost": "பரிந்துரை vs செலவு பகுப்பாய்வு",
"chFertNPK": "காலத்தில் N / P / K பயன்",
"statVolatility": "விலை ஏற்ற இறக்க குறியீடு",
"statGainers": "முதல் ஏற்றங்கள்",
"statLosers": "முதல் இறக்கங்கள்",
"statVolume": "மொத்த அளவு",
"trendLow": "குறைவு",
"thCommodity": "பொருள்",
"expShort": "ஏற்",
"impShort": "இற",
},
"voice": {
"start": "குரல் உள்ளீட்டைத் தொடங்கு",
"stop": "நிறுத்து",
"listening": "கேட்கிறது…",
"transcribing": "எழுதுகிறது…",
"thinking": "சிந்திக்கிறது…",
"speaking": "பேசுகிறது…",
"unavailable": "இந்த சாதனத்தில் குரல் உள்ளீடு இல்லை.",
"audioUnavailable": "இந்த மொழிக்கு பேச்சு வெளியீடு இல்லை.",
"recording": "பதிவாகிறது…",
},
"errors": {
"network": "பிணைய பிழை. இணைப்பைச் சரிபார்த்து மீண்டும் முயல்க.",
"unauthorized": "அமர்வு முடிந்தது. மீண்டும் உள்நுழையுங்கள்.",
"notFound": "இல்லை.",
},
"crops": {
"rice": "அரிசி",
"paddy": "நெல்",
"wheat": "கோதுமை",
"cotton": "பருத்தி",
"maize": "மக்காச்சோளம்",
"sugarcane": "கரும்பு",
"tomato": "தக்காளி",
"potato": "உருளை",
"onion": "வெங்காயம்",
"soybean": "சோயா",
"groundnut": "நிலக்கடலை",
"chilli": "மிளகாய்",
},
}

emit("ta", T)
