# Complete Urdu (ur) catalog. Run from frontend/: python scripts/tr-ur.py
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emit_locale import emit

T = {
"common": {
"appName": "CropPilot",
"loading": "لوڈ ہو رہا ہے…",
"retry": "دوبارہ کوشش کریں",
"cancel": "منسوخ کریں",
"close": "بند کریں",
"save": "محفوظ کریں",
"search": "تلاش کریں",
"noData": "ڈیٹا دستیاب نہیں ہے۔",
"errorGeneric": "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔",
"prevSlide": "پچھلی سلائیڈ",
"nextSlide": "اگلی سلائیڈ",
"menu": "موبائل مینیو کھولیں/بند کریں",
"language": "زبان",
"selectLanguage": "زبان منتخب کریں",
"commandPalette": "کمانڈ پیلیٹ",
},
"navigation": {
"dashboard": "ڈیش بورڈ",
"markets": "منڈیاں",
"weather": "موسم",
"disease": "بیماری کی شناخت",
"schemes": "اسکیمیں",
"analytics": "تجزیات",
"maps": "نقشے",
"assistant": "AI معاون",
},
"auth": {
"signIn": "سائن ان کریں",
"signOut": "سائن آؤٹ کریں",
"welcomeBack": "خوش آمدید",
"signInSubtitle": "اپنے CropPilot اکاؤنٹ میں سائن ان کریں",
"email": "ای میل",
"password": "پاس ورڈ",
"enterPassword": "اپنا پاس ورڈ درج کریں",
"rememberMe": "مجھے یاد رکھیں",
"signingIn": "سائن ان ہو رہا ہے…",
"signInBtn": "سائن ان",
"noAccount": "اکاؤنٹ نہیں ہے؟",
"registerLink": "رجسٹر کریں",
"emailRequired": "ای میل ضروری ہے",
"emailInvalid": "غلط ای میل پتہ",
"passwordRequired": "پاس ورڈ ضروری ہے",
"passwordMin": "پاس ورڈ کم از کم 6 حروف کا ہو",
"invalidCredentials": "غلط معلومات۔ براہ کرم دوبارہ کوشش کریں۔",
"createAccount": "اکاؤنٹ بنائیں",
"registerSubtitle": "CropPilot میں شامل ہوں اور سمارٹ کھیتی شروع کریں",
"fullName": "پورا نام",
"fullNamePlaceholder": "آپ کا پورا نام",
"phone": "فون نمبر",
"selectState": "ریاست منتخب کریں",
"selectDistrict": "ضلع منتخب کریں",
"createPassword": "پاس ورڈ بنائیں",
"confirmPassword": "پاس ورڈ کی تصدیق کریں",
"confirmPasswordPlaceholder": "اپنے پاس ورڈ کی تصدیق کریں",
"registerBtn": "رجسٹر کریں",
"registering": "رجسٹریشن ہو رہی ہے…",
"haveAccount": "پہلے سے اکاؤنٹ ہے؟",
"signInLink": "سائن ان کریں",
"nameRequired": "نام ضروری ہے",
"phoneInvalid": "غلط فون نمبر",
"phoneLong": "فون نمبر بہت طویل ہے",
"selectStateRequired": "براہ کرم ریاست منتخب کریں",
"selectDistrictRequired": "براہ کرم ضلع منتخب کریں",
"passwordMismatch": "پاس ورڈ میل نہیں کھاتے",
"showPassword": "پاس ورڈ دکھائیں",
"hidePassword": "پاس ورڈ چھپائیں",
"nameMin": "پورا نام کم از کم 2 حروف کا ہو",
"phoneMin": "فون نمبر کم از کم 10 ہندسوں کا ہو",
"confirmRequired": "براہ کرم اپنے پاس ورڈ کی تصدیق کریں",
"acceptTerms": "آپ کو شرائط و ضوابط قبول کرنا ہوں گے",
"registerFailed": "رجسٹریشن ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
"acceptPrefix": "میں قبول کرتا ہوں",
"termsService": "شرائط خدمت",
"termsAnd": "اور",
"privacyPolicy": "پرائیویسی پالیسی",
"creatingAccount": "اکاؤنٹ بن رہا ہے…",
"authLayoutTitle": "CropPilot میں خوش آمدید",
"authLayoutBody": "جدید کھیتی کے لیے اوپن سورس پلیٹ فارم۔ ڈیش بورڈ کے لیے سائن ان کریں۔",
},
"landing": {
"badge": "مفت اور اوپن سورس سافٹ ویئر",
"tagline": "ہوشیار کھیتی کے لیے اوپن سورس اوزار۔",
"heroBody": "فصل کی صحت، بیماری کی شناخت، موسمی معلومات اور درج منڈی بازار بھاؤ کے لیے کسان مرکوز پلیٹ فارم۔",
"openApp": "CropPilot کھولیں",
"viewGithub": "GitHub پر دیکھیں",
"featuresTitle": "آپ کیا کر سکتے ہیں",
"featCrop": "فصل کی صحت",
"featCropBody": "فصل کی حالت اور متعلقہ کھیت کی معلومات پر نظر رکھیں۔",
"featDisease": "بیماری کی شناخت",
"featDiseaseBody": "تعاون یافتہ بیماری کی شناخت کے لیے فصل کی تصویروں کا تجزیہ کریں۔",
"featWeather": "موسمی معلومات",
"featWeatherBody": "کھیتی کے فیصلوں کے لیے مفید موسمی معلومات دیکھیں۔",
"featMarket": "منڈی کی معلومات",
"featMarketBody": "AGMARKNET سے سرکاری کھلے ڈیٹا کے ذریعے درج منڈی بھاؤ دیکھیں۔",
"appTitle": "ایپلیکیشن",
"appBody": "کھیت کا جائزہ، موسم، فصل کی صحت اور منڈی کے حصوں کے ساتھ CropPilot ڈیش بورڈ۔",
"appCaption": "نمونہ ڈیٹا کے ساتھ چلتا ہوا CropPilot ڈیش بورڈ۔",
"appAlt": "نمونہ ڈیٹا کے ساتھ کھیت کا جائزہ، موسم، فصل کی صحت اور منڈی کے حصے دکھاتا CropPilot ڈیش بورڈ اسکرین شاٹ",
"marketTitle": "منڈی کی معلومات",
"marketBody": "ریاست، ضلع، منڈی، جنس، قسم، درجے اور مدت کے لحاظ سے تازہ ترین درج منڈی بھاؤ دیکھیں، نیز رجحان اور منڈیوں کا موازنہ کریں۔",
"marketSource": "ماخذ: سرکاری کھلے ڈیٹا کے ذریعے AGMARKNET۔ قیمتیں مشاہدے کی تاریخوں کے ساتھ درج مشاہدات ہیں، موجودہ بازار بھاؤ کے طور پر کبھی پیش نہیں کی جاتیں۔",
"marketCta": "منڈی بھاؤ دیکھیں",
"whyTitle": "کسانوں کے لیے بنایا۔ کھلے پن سے بنایا۔",
"whyBody": "CropPilot مفت اور اوپن سورس سافٹ ویئر ہے جو کھیتی کے اوزار اور معلومات آسان بناتا ہے۔ یہ MIT لائسنس پر چلتا ہے اور تیاری GitHub پر شفاف ہوتی ہے۔",
"archTitle": "آرکیٹیکچر",
"archBody": "کھیت اور مقامی ڈیٹا کے لیے PostgreSQL اور PostGIS، پس پردہ کاموں کے لیے Celery ورکرز اور بیماری کی شناخت کے لیے PyTorch ویژن ماڈلز کے ساتھ FastAPI سروس پر مبنی Next.js فرنٹ اینڈ۔ سب کچھ Docker Compose سے مقامی طور پر چلتا ہے۔",
"ossTitle": "GitHub پر اوپن سورس",
"ossBody": "کوڈ دیکھیں، مسائل درج کریں اور بہتری میں حصہ لیں۔ MIT لائسنس یافتہ۔",
"footerTag": "اوپن سورس زرعی پلیٹ فارم۔",
"footerDocs": "دستاویزات",
"navFeatures": "خصوصیات",
"navArchitecture": "آرکیٹیکچر",
"toggleMenu": "مینیو کھولیں/بند کریں",
"footerLabel": "فوٹر",
},
"dashboard": {
"welcomeBack": "خوش آمدید، {name}",
"farmer": "کسان",
"selectFarm": "کھیت منتخب کریں",
"allFarms": "تمام کھیت",
"wFarmOverview": "کھیت کا جائزہ",
"wWeather": "آج کا موسم",
"wCropHealth": "فصل کی صحت",
"wDiseaseAlerts": "بیماری کی تنبیہات",
"wRevenue": "آمدنی",
"wExpenses": "اخراجات",
"wNetProfit": "خالص منافع",
"wYield": "پیداوار",
"wMarketTrends": "منڈی رجحانات",
"wSchemes": "اسکیم کی سفارشات",
"wNotifications": "اطلاعات",
"wQuickActions": "فوری اقدامات",
"vsLastMonth": "پچھلے مہینے کے مقابلے میں",
"totalYield": "کل پیداوار",
"perHectare": "فی ہیکٹر",
"noAlerts": "کوئی فعال بیماری تنبیہ نہیں",
"cropsHealthy": "آپ کی فصلیں صحت مند ہیں",
"noNotifications": "کوئی اطلاعات نہیں",
"qaScan": "فصلیں اسکین کریں",
"qaWeather": "موسم دیکھیں",
"qaMarkets": "منڈیاں دیکھیں",
"qaAssistant": "AI معاون",
"statFarms": "کل کھیت",
"statArea": "کل رقبہ",
"statPlots": "فعال پلاٹ",
"statSeason": "موجودہ موسم",
"notifMarkRead": "سب کو پڑھا ہوا نشان زد کریں",
"marginLabel": "مارجن:",
},
"weather": {
"title": "موسم",
"subtitle": "آپ کے کھیت کے لیے تازہ موسمی ڈیٹا اور پیشن گوئی",
"searchLocation": "مقام تلاش کریں…",
"noLocations": "کوئی مقام نہیں ملا",
"hourly": "گھنٹہ وار پیشن گوئی",
"details": "موسم کی تفصیلات",
"rainProbability": "بارش کا امکان",
"windSpeed": "ہوا کی رفتار",
"humidity": "نمی",
"uvIndex": "UV انڈیکس",
"pressure": "دباؤ",
"visibility": "حد نظر",
"weekly": "7 روزہ پیشن گوئی",
"feelsLike": "{temp}° جیسا لگتا ہے",
"highShort": "زیادہ: {temp}°",
"lowShort": "کم: {temp}°",
},
"disease": {
"title": "بیماری کی شناخت",
"subtitle": "AI سے چلنے والی بیماری کی تشخیص کے لیے فصل کی تصویریں اپ لوڈ کریں یا لیں",
"newDetection": "نئی جانچ",
"analyzing": "آپ کی فصل کی تصویر کا تجزیہ ہو رہا ہے…",
"analyzingBody": "AI بیماری کے نمونے اسکین کر رہا ہے",
"readyTitle": "تشخیص کے لیے تیار",
"readyBody": "فوری AI بیماری کی شناخت اور علاج کی سفارشات کے لیے متاثرہ فصل کی تصویر اپ لوڈ کریں یا لیں",
"confidence": "AI اعتماد",
"cameraTitle": "کیمرہ کیپچر",
"cameraBody": "متاثرہ فصل کی تصویر لیں",
"cameraHint": "متاثرہ پتے یا پھل فریم میں رکھیں",
"activateCamera": "کیمرہ شروع کریں",
"capture": "کیپچر کریں",
"retake": "دوبارہ لیں",
"uploadTitle": "تصویر اپ لوڈ کریں",
"uploadHint": "ڈریگ اور ڈراپ یا براؤز کریں",
"dropHint": "اپ لوڈ کے لیے ڈریگ و ڈراپ یا کلک کریں",
"dropFormats": "JPG, PNG, WEBP، 10MB تک",
"changeImage": "تصویر بدلیں",
"fileTooBig": "فائل کا سائز 10MB سے کم ہو۔",
"resultTitle": "جانچ کا نتیجہ",
"detectedDisease": "پائی گئی بیماری",
"confidenceScore": "اعتماد اسکور",
"treatmentAvailable": "علاج کی سفارش دستیاب",
"aiAnalysis": "AI سے چلنے والا تجزیہ",
"symptoms": "علامات",
"recommendedActions": "سفارش کردہ اقدامات",
"preventiveMeasures": "احتیاطی تدابیر",
"historyTitle": "جانچ کی تاریخ",
"thDate": "تاریخ",
"thCrop": "فصل",
"thDisease": "بیماری",
"thConfidence": "اعتماد",
"thStatus": "حالت",
"sevLow": "کم",
"sevModerate": "درمیانہ",
"sevHigh": "زیادہ",
"sevCritical": "سنگین",
"pastDetections": "{count} پچھلی جانچیں",
"searchHistory": "فصل یا بیماری سے تلاش کریں…",
"noDetections": "کوئی جانچ نہیں ملی",
"stageCheckingPhoto": "تصویر کا معیار جانچا جا رہا ہے…",
"stageAnalyzing": "تصویر کا تجزیہ ہو رہا ہے…",
"cropHintLabel": "فصل (اختیاری - درست ماہر چننے میں مددگار)",
"cropHintAuto": "خودکار (کوئی اشارہ نہیں)",
"unknownCrop": "نامعلوم فصل",
"uncertainTitle": "CropPilot مسئلے کی پختہ شناخت نہ کر سکا",
"uncertainBody": "تصویر کے شواہد تشخیص کے لیے ناکافی تھے۔ نیچے متبادل اندازے ہیں، تشخیص نہیں۔",
"possibleCauses": "ممکنہ متبادل",
"analyzeAnotherHint": "اچھی روشنی میں ایک متاثرہ پتے کی قریبی تصویر سے دوبارہ کوشش کریں۔",
"supportedCrops": "تصدیق شدہ ماہر والی فصلیں",
"capabilitiesOffline": "تشخیصی سروس کی فہرست تک رسائی نہ ہو سکی۔ پھر بھی اپ لوڈ آزما سکتے ہیں۔",
"bandHigh": "زیادہ",
"bandMedium": "درمیانہ",
"bandLow": "کم",
"bandUnverified": "غیر تصدیق شدہ اسکور",
"bandUnknown": "نامعلوم",
"statusDiagnosed": "ممکنہ تشخیص",
"statusProbable": "ممکنہ - تصدیق درکار",
"statusUncertain": "غیر یقینی",
"statusInsufficientImage": "تصویر ناقابل استعمال",
"statusUnsupportedCrop": "فصل ابھی تعاون یافتہ نہیں",
"statusError": "تجزیہ ناکام",
"uncalibratedScore": "ماڈل اسکور (غیر معیاری)",
"uncalibratedScoreHint": "خام ماڈل آؤٹ پٹ، معیاری احتمال نہیں۔",
"uploadedPhoto": "اپ لوڈ کردہ تصویر",
"evidenceTitle": "تجزیے کی تفصیلات",
"routingMode": "روٹنگ",
"modelsUsed": "استعمال شدہ ماڈل",
"fieldValidation": "کھیت کی توثیق",
"imageQuality": "تصویر کا معیار",
"latencyLabel": "تجزیے کا وقت",
"researchBadge": "تحقیقی ماڈل",
"notVerified": "تصدیق شدہ نہیں",
"guidanceFor": "رہنمائی:",
"guidanceSource": "ماخذ",
"similarConditions": "ملتی جلتی حالتیں",
"noGuidance": "CropPilot کے پاس اس تشخیص کے لیے ابھی تصدیق شدہ رہنمائی نہیں۔",
"imageNotRetained": "صرف سیشن کی تاریخ - تصویریں محفوظ نہیں ہوتیں۔",
"errNetwork": "نیٹ ورک خرابی۔ اپنا کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
"errTooLarge": "تصویر بہت بڑی ہے۔ 10 MB سے چھوٹی تصویر استعمال کریں۔",
"errPoorQuality": "تصویر کا معیار تجزیے کے لیے بہت خراب ہے۔ ایک متاثرہ پتے کی قریبی تصویر لیں۔",
"errUnsupportedCrop": "CropPilot کے پاس اس فصل کے لیے ابھی تصدیق شدہ ماہر نہیں۔",
"errInvalid": "وہ فائل تصویر کے طور پر پڑھی نہ جا سکی۔ JPG یا PNG تصویر آزمائیں۔",
"errNoModel": "ابھی کوئی تصدیق شدہ تشخیصی ماڈل دستیاب نہیں۔ بعد میں کوشش کریں۔",
"errServer": "تجزیہ ناکام۔ واضح تصویر سے دوبارہ کوشش کریں۔",
"analysisIncomplete": "تجزیہ نامکمل",
"noVerifiedDiagnosis": "تصدیق شدہ تشخیص نہیں",
"analysisStatusLabel": "تجزیے کی حالت",
"cropLabel": "فصل",
"cropNotIdentified": "شناخت نہیں ہوئی",
"cropUnsupported": "غیر تعاون یافتہ",
"cropSourceUser": "آپ نے منتخب کی (روٹنگ اشارہ، ماڈل ثبوت نہیں)",
"cropSourceUnknown": "اس تصویر سے شناخت نہیں ہوئی",
"selectCropPrompt": "کیا آپ فصل جانتے ہیں؟ منتخب کرنے سے CropPilot کو درست ماہر چننے میں مدد ملتی ہے۔",
"analyzeAgain": "دوبارہ تجزیہ کریں",
"retryAnalysis": "دوبارہ کوشش کریں",
"coverageBadge": "ماڈل کوریج دستیاب نہیں",
"serviceBadge": "سروس دستیاب نہیں",
"temporaryAnalysisFailure": "تجزیہ عارضی طور پر ناکام",
"modelFailureBody": "تعاون یافتہ بیماری ماڈل دستیاب تھا، مگر تجزیہ مکمل نہ ہو سکا۔",
"photoNeedsImprovement": "تصویر میں بہتری درکار",
"noSpecialistAvailable": "CropPilot کے پاس اس فصل کے لیے فی الحال تصدیق شدہ بیماری ماڈل نہیں۔",
"cropUnknownNoModel": "CropPilot اس تصویر سے فصل نہ پہچان سکا، اس لیے تصدیق شدہ بیماری ماڈل منتخب نہ ہو سکا۔",
"noCoverageTitle": "فصل فی الحال تعاون یافتہ نہیں",
"lowConfidenceTitle": "تشخیص غیر یقینی",
"lowConfidenceBody": "قابل اعتماد تشخیص کے لیے دستیاب ماڈل کافی متفق نہ ہوئے۔",
"confidenceNotAvailable": "دستیاب نہیں",
"cropIdentification": "فصل کی شناخت",
"cropSource": "فصل کا ماخذ",
"routingLabel": "روٹنگ",
"specialistsLabel": "ماہرین",
"specialistsNone": "کوئی اہل نہیں",
"calibrationLabel": "معیاربندی",
"calibrationUnavailable": "دستیاب نہیں (خام ماڈل اسکور)",
"vlmLabel": "VLM فال بیک",
"vlmNotConfigured": "ترتیب شدہ نہیں",
"vlmUsed": "جائزے کے لیے استعمال ہوا",
"vlmNotUsed": "استعمال نہیں ہوا",
"coverageTitle": "موجودہ ماڈل کوریج",
"coverageBody": "{count} تصدیق شدہ پروڈکشن ماڈل راستے۔ کوریج محدود ہے اور بڑھ رہی ہے۔",
"whyLabel": "کیوں؟",
"whatToDoLabel": "آپ کیا کر سکتے ہیں",
"errNoCoverage": "CropPilot کے پاس اس فصل کے لیے فی الحال تصدیق شدہ بیماری ماڈل نہیں۔",
"errModelFailure": "تعاون یافتہ بیماری ماڈل دستیاب تھا، مگر تجزیہ مکمل نہ ہو سکا۔ براہ کرم دوبارہ کوشش کریں۔",
"noDiagnosis": "تشخیص نہیں",
"statusNotSupported": "تعاون یافتہ نہیں",
"statusFailed": "ناکام",
"downloadSummary": "خلاصہ ڈاؤن لوڈ کریں",
"shareSummary": "خلاصہ شیئر کریں",
"summaryCopied": "خلاصہ کلپ بورڈ پر کاپی ہوا",
"analyzeAnotherPhoto": "دوسری تصویر کا تجزیہ کریں",
"stepsTitle": "تجزیے کے مراحل",
"stepUpload": "تصویر اپ لوڈ ہو رہی ہے",
"stepQuality": "تصویر کا معیار جانچا جا رہا ہے",
"stepRouting": "بیماری کے ماہرین منتخب ہو رہے ہیں",
"stepAnalysis": "تجزیہ چل رہا ہے",
"stepVerify": "نتیجے کی توثیق ہو رہی ہے",
"supportedCropsNote": "تصدیق شدہ ماہر والی فصلیں",
"cropUnknownWeakEvidence": "درست بیماری ماہر چننے کے لیے کافی شواہد سے CropPilot فصل نہ پہچان سکا۔",
"unknownCropWhy": "دستیاب ماڈل نے کمزور نتائج دیے، مگر تصویر فصل کی تصدیق کے لیے کافی ثبوت نہیں دیتی۔",
"modelOutputs": "ماڈل آؤٹ پٹ",
"modelOutputsInterpretation": "شفافیت کے لیے خام ماڈل آؤٹ پٹ دکھائے گئے ہیں؛ انہیں تصدیق شدہ بیماری تشخیص نہ سمجھا جائے۔",
"rawScoreLabel": "خام اسکور",
},
"assistant": {
"title": "AI معاون",
"placeholder": "قیمتوں، موسم، اسکیموں کے بارے میں پوچھیں…",
"send": "بھیجیں",
"offline": "معاون دستیاب نہیں۔ براہ کرم بعد میں کوشش کریں۔",
"offlineBackend": "معاون دستیاب نہیں۔ دیکھیں بیک اینڈ چل رہا ہے۔",
"sources": "ذرائع",
"newChat": "نئی چیٹ",
"welcome": "سلام! میں **CropPilot AI** ہوں — آپ کا ذہین زرعی معاون۔ 🌾\n\nمیں مدد کر سکتا ہوں:\n\n- **فصل کا انتظام** — بوائی، آبپاشی، کھاد کا شیڈول\n- **بیماری کی شناخت** — فصل کی بیماریاں پہچانیں اور علاج کریں\n- **منڈی تجزیہ** — تازہ منڈی بھاؤ اور رجحانات\n- **سرکاری اسکیمیں** — اہل اسکیمیں تلاش کریں\n- **موسمی بصیرت** — پیشن گوئی اور فصلوں پر اثر\n\nآج اپنے کھیت کے بارے میں کیا جاننا چاہیں گے؟",
"welcomeTitle": "CropPilot میں خوش آمدید",
"welcomePreview": "سلام! میں CropPilot AI ہوں…",
"newChatTitle": "نئی چیٹ",
"newChatPreview": "گفتگو شروع کریں…",
"promptPaddy": "گندم کی کاشت کے بہترین طریقے",
"promptDisease": "ٹماٹر کے پتے کی جھلسن پہچانیں",
"promptMarket": "موجودہ منڈی بھاؤ",
"promptSchemes": "کسانوں کے لیے سرکاری اسکیمیں",
"suggestTitle": "کھیتی کے بارے میں کچھ بھی پوچھیں — فصلیں، بیماریاں، منڈیاں، اسکیمیں اور مزید",
"cardCrop": "فصل کا مشورہ",
"cardCropBody": "گندم کی کاشت کے بہترین طریقے",
"cardCropQuery": "گندم کی کاشت کے بہترین طریقے کیا ہیں؟",
"cardDisease": "بیماری میں مدد",
"cardDiseaseBody": "ٹماٹر میں پتے کی جھلسن پہچانیں اور علاج کریں",
"cardDiseaseQuery": "ٹماٹر کے پودوں میں پتے کی جھلسن کیسے پہچانوں اور علاج کروں؟",
"cardMarket": "منڈی سوالات",
"cardMarketBody": "دھان اور گندم کے موجودہ منڈی بھاؤ",
"cardMarketQuery": "تلنگانہ میں دھان اور گندم کے موجودہ منڈی بھاؤ کیا ہیں؟",
"cardScheme": "اسکیم کی معلومات",
"cardSchemeBody": "چھوٹے کسانوں کے لیے سرکاری اسکیمیں",
"cardSchemeQuery": "بھارت میں چھوٹے کسان کے طور پر میں کن سرکاری اسکیموں کا اہل ہوں؟",
"cardWeather": "موسم کا سوال",
"cardWeatherBody": "آنے والا موسم اور فصلوں پر اثر",
"cardWeatherQuery": "آنے والا موسم میری خریف فصلوں پر کیسے اثر ڈالے گا؟",
"cardPlan": "کھیت کی منصوبہ بندی",
"cardPlanBody": "فصل کی گردش اور مٹی کے انتظام کی تجاویز",
"cardPlanQuery": "اپنے کھیت کے لیے فصل کی کون سی گردش اپناؤں؟",
"sideNewChat": "نئی چیٹ",
"sideSearch": "گفتگو تلاش کریں…",
"sideNoFound": "کوئی گفتگو نہیں ملی",
"sideNoYet": "ابھی کوئی گفتگو نہیں",
"sideClose": "سائیڈبار بند کریں",
"sideOpen": "سائیڈبار کھولیں",
"sideDelete": "گفتگو حذف کریں",
"inputDefault": "فصلوں، بیماریوں، منڈیوں، اسکیموں کے بارے میں پوچھیں…",
"voiceError": "آواز کی خرابی",
"voiceUnreachable": "آواز سروس ناقابل رسائی",
"micDenied": "مائیکروفون تک رسائی مسترد",
"paletteSearch": "صفحات تلاش کریں یا کمانڈ لکھیں…",
"paletteEmpty": "کوئی نتیجہ نہیں ملا۔",
"errorTitle": "کچھ غلط ہو گیا",
"errorFallback": "غیر متوقع خرابی ہوئی۔ براہ کرم دوبارہ کوشش کریں۔",
"notFoundTitle": "صفحہ نہیں ملا",
"notFoundBody": "جو صفحہ آپ ڈھونڈ رہے ہیں وہ موجود نہیں یا منتقل ہو گیا ہے۔",
"goDashboard": "ڈیش بورڈ پر جائیں",
"goHome": "ہوم پر جائیں",
"loadingApp": "CropPilot لوڈ ہو رہا ہے…",
"themeToggle": "تھیم بدلیں",
"themeCurrent": "موجودہ تھیم: {theme}۔ {next} کے لیے کلک کریں",
"themeLight": "روشن",
"themeDark": "گہرا",
"themeSystem": "سسٹم",
"attachFiles": "فائلیں منسلک کریں",
"attachDocs": "تصاویر و دستاویزات",
"takePhoto": "تصویر لیں",
"copyResponse": "جواب کاپی کریں",
"copied": "کاپی ہوا",
"helpful": "مفید",
"notHelpful": "غیر مفید",
"fileTypeUnsupported": "\"{type}\" فائل کی قسم تعاون یافتہ نہیں",
"sourcesCount": "{count} ماخذ",
"sourcesCountPlural": "{count} ماخذ",
},
"maps": {
"loading": "لوڈ ہو رہا ہے…",
"searchLocation": "گاؤں، قصبہ، منڈی یا پن کوڈ تلاش کریں",
"clearSearch": "تلاش صاف کریں",
"searchFailed": "مقام نہیں ملا۔ دوسری تلاش آزمائیں۔",
"noResults": "کوئی مماثل مقام نہیں ملا۔",
"useMyLocation": "میری لوکیشن استعمال کریں",
"resetView": "بھارت کا منظر ری سیٹ کریں",
"fullscreen": "فل اسکرین نقشہ",
"mapLabel": "بھارت کا CropPilot زرعی نقشہ",
"location": "مقام",
"locationInsights": "مقام کی معلومات",
"placeUnavailable": "مقام کا نام دستیاب نہیں — نقاط دکھائے گئے ہیں۔",
"weather": "موسم",
"weatherMapTitle": "موسم کا نقشہ",
"rainRadar": "بارش ریڈار",
"weatherUnavailable": "موسمی معلومات عارضی طور پر دستیاب نہیں۔",
"humidity": "نمی",
"wind": "ہوا",
"rain": "بارش",
"feelsLike": "محسوس ہوتا ہے",
"wmoCode": "WMO کوڈ {code}",
"updatedJustNow": "ابھی اپ ڈیٹ ہوا",
"updatedMinutesAgo": "{count} منٹ پہلے اپ ڈیٹ ہوا",
"updatedHoursAgo": "{count} گھنٹے پہلے اپ ڈیٹ ہوا",
"sourceOpenMeteo": "ماخذ: Open-Meteo",
"nearbyMarkets": "قریبی منڈیاں",
"commodityFilter": "جنس کے لحاظ سے چھانٹیں",
"allCommodities": "تمام اجناس",
"searchArea": "اس علاقے میں تلاش کریں",
"marketsUnavailable": "قریبی منڈی ڈیٹا لوڈ نہ ہو سکا۔",
"noMappedMarkets": "قریب میں نقشے کے نقاط والی کوئی منڈی نہیں ملی۔",
"noReportedPrice": "اس منڈی کے لیے ابھی کوئی درج بھاؤ نہیں۔",
"latestReported": "تازہ درج: {date}",
"sourceAgmarknet": "ماخذ: AGMARKNET",
"quintal": "کوئنٹل",
"unmappedNote": "یہاں مزید {count} منڈیوں کے نقشے کے نقاط ابھی نہیں؛ وہ مارکیٹ انٹیلیجنس میں درج ہیں۔",
"closeDetails": "منڈی کی تفصیلات بند کریں",
"viewMarketIntel": "مارکیٹ انٹیلیجنس دیکھیں",
"cropPilotActions": "CropPilot اقدامات",
"openMarketIntel": "مارکیٹ انٹیلیجنس",
"analyzeDisease": "فصل کی بیماری کا تجزیہ",
"askAssistant": "CropPilot AI سے پوچھیں",
"legendSelected": "منتخب مقام",
"legendMarkets": "منڈیاں",
"markets": "منڈیاں",
"toggleMarkets": "منڈی مارکر آن/آف کریں",
"pickHint": "مقام چننے کے لیے نقشے پر کلک کریں",
"collapseSheet": "پینل چھوٹا کریں",
"expandSheet": "پینل بڑا کریں",
"geoDenied": "مقام تک رسائی مسترد۔ اس کے بجائے اپنا مقام تلاش کر سکتے ہیں۔",
"geoUnavailable": "موجودہ مقام دستیاب نہیں۔ تلاش آزمائیں۔",
"geoTimeout": "مقام کی درخواست کا وقت ختم۔ دوبارہ کوشش کریں یا تلاش کریں۔",
"geoUnsupported": "اس براؤزر میں جیولوکیشن تعاون یافتہ نہیں۔ براہ کرم تلاش کریں۔",
"mapUnavailable": "اس ڈیوائس پر انٹرایکٹو نقشہ دستیاب نہیں (WebGL بند)۔ تلاش اور مقام کی معلومات نیچے کام کرتی ہیں۔",
"agriSnapshot": "زرعی سنیپ شاٹ",
"commonCrops": "عام فصلیں",
"soil": "مٹی",
"rainfall": "بارش",
"seasonRain": "{season} میں {mm} ملی میٹر",
"forecastLabel": "پیشن گوئی",
"texture": "بناوٹ",
"organicCarbon": "نامیاتی کاربن",
"clay": "چکنی مٹی",
"sand": "ریت",
"silt": "سلٹ",
"nitrogen": "نائٹروجن",
"sourceSoilGrids": "ماخذ: SoilGrids",
"resolutionM": "ریزولوشن: {m} میٹر",
"modelledEstimateNote": "ماڈل تخمینہ، لیب مٹی ٹیسٹ نہیں",
"modelledBadge": "ماڈل پر مبنی",
"soilUnavailable": "اس مقام کے لیے مٹی کا ڈیٹا دستیاب نہیں۔",
"today": "آج",
"last7days": "پچھلے 7 دن",
"thisMonth": "اس ماہ",
"season": "موسم",
"reanalysisNote": "دوبارہ تجزیہ/پیشن گوئی تخمینہ، اسٹیشن ڈیٹا نہیں",
"rainfallUnavailable": "اس مقام کے لیے بارش کا ڈیٹا دستیاب نہیں۔",
"crops": "فصلیں",
"commonlyTraded": "علاقے کی منڈیوں میں حال میں تجارت شدہ اجناس",
"cropsUnavailable": "اس علاقے کے لیے فصل تجارت کا ڈیٹا دستیاب نہیں۔",
"suitabilityTitle": "ماحولیاتی موزونیت کا تخمینہ",
"water": "آبی وسائل",
"waterUnavailable": "اس مقام کے لیے پانی کا ڈیٹا دستیاب نہیں۔",
"waterNote": "زیر زمین پانی کے مشاہدات وقفے وقفے سے ہوتے ہیں اور ذخیرے کا پانی کھیت کی آبپاشی کی دستیابی نہیں بتاتا۔",
"diseaseContext": "بیماری کا سیاق",
"diseaseUnavailable": "اس علاقے کے لیے بیماری کا سیاق دستیاب نہیں۔",
"selectedLocation": "منتخب مقام",
"viewFullMap": "پورا نقشہ دیکھیں",
"yourLocation": "آپ کا مقام",
},
"markets": {
"title": "مارکیٹ انٹیلیجنس",
"subtitle": "AGMARKNET سے تازہ درج منڈی بھاؤ",
"state": "ریاست",
"district": "ضلع",
"market": "منڈی",
"commodity": "جنس",
"days": "دن",
"latestPrice": "تازہ درج بھاؤ: {price} فی کوئنٹل",
"arrivalDate": "آمد کی تاریخ: {date}",
"empty": "ڈیٹابیس میں مماثل تازہ درج بھاؤ نہیں ملا۔",
"unavailableTitle": "منڈی ڈیٹا فی الحال دستیاب نہیں",
"tryAgain": "دوبارہ کوشش کریں",
"signInRequired": "سائن ان ضروری",
"signInPrompt": "مارکیٹ انٹیلیجنس دیکھنے کے لیے سائن ان کریں۔",
"signInNeeded": "مارکیٹ انٹیلیجنس دیکھنے کے لیے سائن ان کریں۔",
"offline": "منڈی سروس تک رسائی نہ ہو سکی۔ کنکشن بحال ہونے پر محفوظ مشاہدات نظر آئیں گے۔",
"loadError": "یہ حصہ لوڈ کرتے کچھ غلط ہوا۔ آپ کے محفوظ مشاہدات سلامت ہیں۔",
"loadErrorShort": "یہ حصہ لوڈ کرتے کچھ غلط ہوا۔",
"allStates": "تمام ریاستیں",
"allDistricts": "تمام اضلاع",
"selectStateFirst": "پہلے ریاست منتخب کریں",
"allMarkets": "تمام منڈیاں",
"selectCommodity": "جنس منتخب کریں",
"allVarieties": "تمام اقسام",
"allGrades": "تمام درجے",
"variety": "قسم",
"grade": "درجہ",
"statesReporting": "رپورٹنگ ریاستیں",
"marketsReporting": "رپورٹنگ منڈیاں",
"commoditiesReported": "درج اجناس",
"latestObservation": "تازہ مشاہدہ",
"storedObservations": "محفوظ مشاہدات دکھائے جا رہے ہیں",
"storedObservationsBody": "اس انتخاب کے لیے ماخذ نے حالیہ مشاہدہ شائع نہیں کیا۔ نیچے اقدار تازہ محفوظ رپورٹس ہیں، نئے بھاؤ نہیں۔",
"noRecentPrice": "حالیہ درج بھاؤ نہیں",
"emptyHint": "کوئی اور ریاست، ضلع، جنس یا منڈی آزمائیں۔ اگلی اشاعت کے بعد نئی رپورٹس یہاں نظر آئیں گی۔",
"selectionSummary": "انتخاب کا خلاصہ",
"reportedMarkets": "درج منڈیاں",
"observationsInTable": "جدول میں مشاہدات",
"trendPoints": "رجحان نکات",
"comingLater": "بعد میں آ رہا ہے",
"comingLaterBody": "قیمت کی پیشن گوئی اور فروخت کی سفارشات ابھی اس منظر کا حصہ نہیں۔ یہاں صرف درج مشاہدات دکھائے گئے ہیں۔",
"searchStates": "ریاستیں تلاش کریں…",
"searchDistricts": "اضلاع تلاش کریں…",
"searchMarkets": "منڈیاں تلاش کریں…",
"noMatchState": "کوئی مماثل ریاست نہیں۔",
"noMatchDistrict": "کوئی مماثل ضلع نہیں۔",
"noMatchMarket": "کوئی مماثل منڈی نہیں۔",
"tableSearch": "لوڈ شدہ نتائج میں تلاش کریں…",
"thMin": "کم از کم روپے",
"thMax": "زیادہ سے زیادہ روپے",
"thModal": "عام روپے",
"thArrivals": "آمد",
"thObserved": "مشاہدہ",
"showingCount": "{from}–{to} از {total}",
"prevPage": "پچھلا صفحہ",
"nextPage": "اگلا صفحہ",
"priceRs": "روپے{value}",
"minMaxLine": "کم روپے{min} · زیادہ روپے{max}",
"arrivalsLine": "آمد: {value}",
"freshNone": "حالیہ مشاہدہ دستیاب نہیں",
"freshLatest": "تازہ درج: {date}",
"freshStale": "ڈیٹا تاخیر سے ہو سکتا ہے",
"sourceLabel": "ماخذ: {name}",
"sourceBody": "درج منڈی بھاؤ منڈیوں کے شائع کردہ مشاہدات ہیں اور تاخیر سے آ سکتے ہیں۔ یہ مستقبل کے بھاؤ کی ضمانت نہیں۔",
"sourceResource": "وسیلہ: {id}",
"cmpNoData": "موازنہ دستیاب نہیں",
"cmpNoDataBody": "اس انتخاب کے لیے ابھی درج بھاؤ نہیں۔",
"cmpTitle": "منڈی کا موازنہ",
"cmpBody": "صرف مماثل قسم، درجے اور اکائی والی قطاریں ملائی جاتی ہیں۔ بھاؤ فی منڈی تازہ درج مشاہدات ہیں۔",
"cmpMinMax": "کم سے زیادہ روپے",
"histNoData": "بھاؤ کی تاریخ نہیں",
"histNoDataBody": "منتخب منڈی اور جنس کے لیے اس مدت میں درج مشاہدات نہیں۔",
"histTitle": "درج عام بھاؤ کا رجحان",
"histUnit": "روپے فی {unit}",
"histModal": "عام",
"histMax": "زیادہ",
"histMin": "کم",
"histCount": "{count} مشاہدات",
"histObserved": "{label} کو مشاہدہ",
"cmpUnspecified": "غیر متعین قسم اور درجہ",
},
"schemes": {
"title": "سرکاری اسکیمیں",
"subtitle": "زرعی اسکیمیں، سبسڈی اور فلاحی پروگرام تلاش کریں اور درخواست دیں",
"search": "نام، تفصیل، ٹیگ سے اسکیمیں تلاش کریں…",
"all": "تمام",
"noFound": "کوئی اسکیم نہیں ملی",
"noFoundBody": "اپنی تلاش یا فلٹر بدلیں",
"viewDetail": "تفصیلات دیکھیں",
"eligibility": "اہلیت",
"benefits": "فوائد",
"howToApply": "درخواست کیسے دیں",
"close": "بند کریں",
"moreDetails": "مزید تفصیلات",
"applicationProcess": "درخواست کا عمل:",
"funding": "فنڈنگ:",
"checkEligibility": "اہلیت دیکھیں",
"ministry": "وزارت:",
"eligibilityCriteria": "اہلیت کے معیار",
"requiredDocuments": "درکار دستاویزات",
"active": "فعال",
"inactive": "غیر فعال",
"applyNow": "ابھی درخواست دیں",
},
"analytics": {
"title": "تجزیات",
"subtitle": "آپ کے کھیت کی کارکردگی کی جامع بصیرت",
"tabRevenue": "آمدنی",
"tabYield": "پیداوار",
"tabCropHealth": "فصل کی صحت",
"tabWater": "پانی کا استعمال",
"tabFertilizer": "کھاد کا استعمال",
"tabMarket": "منڈی تجزیات",
"statRevenue": "کل آمدنی",
"statYield": "اوسط پیداوار/ہیکٹر",
"statHealth": "صحت اسکور",
"statWater": "پانی کی کارکردگی",
"rangeCustom": "اپنی مرضی",
"chRevenueMonthly": "ماہانہ آمدنی",
"chRevenueByCrop": "فصل کے لحاظ سے آمدنی",
"chRevenueCumulative": "مجموعی آمدنی",
"chYieldByCrop": "فی فصل پیداوار",
"chYieldTrend": "پیداوار کا رجحان",
"chYieldVsTarget": "پیداوار بمقابلہ ہدف",
"chYieldPerHa": "فی ہیکٹر پیداوار",
"chYieldTopBottom": "بہترین اور کمزور فصلیں",
"chHealthOverall": "مجموعی صحت",
"chHealthRadar": "صحت کے پیمانوں کا ریڈار",
"chHealthTrend": "صحت اسکور کا رجحان",
"chHealthByPlot": "پلاٹ کے لحاظ سے صحت",
"chHealthTimeline": "صحت تنبیہات کی ٹائم لائن",
"chPriceTrends": "بھاؤ رجحانات - نمایاں 5 اجناس",
"chPriceHeatmap": "بھاؤ ہیٹ میپ - جنس بمقابلہ ماہ",
"chBestTimes": "بہترین فروخت کے اوقات",
"chTrade": "برآمد / درآمد تجزیہ",
"chVolume": "تجارت کا حجم",
"chInsights": "AI بصیرت",
"chWaterDaily": "بارش کے ساتھ روزانہ پانی کا استعمال",
"chWaterByCrop": "فصل کے لحاظ سے پانی کا استعمال",
"chWaterEff": "پانی کی کارکردگی (فی کلو پیداوار لیٹر)",
"chWaterSave": "پانی بچت کی تجاویز",
"chWaterSchedule": "شیڈول کی سفارشات",
"chFertBreakdown": "کھاد کی اقسام کی تقسیم",
"chFertCost": "سفارش بمقابلہ لاگت تجزیہ",
"chFertNPK": "وقت کے ساتھ N / P / K استعمال",
"statVolatility": "بھاؤ اتار چڑھاؤ انڈیکس",
"statGainers": "نمایاں فائدہ",
"statLosers": "نمایاں نقصان",
"statVolume": "کل حجم",
"trendLow": "کم",
"thCommodity": "جنس",
"expShort": "برآمد",
"impShort": "درآمد",
},
"voice": {
"start": "آواز ان پٹ شروع کریں",
"stop": "روکیں",
"listening": "سن رہے ہیں…",
"transcribing": "تحریر ہو رہی ہے…",
"thinking": "سوچ رہے ہیں…",
"speaking": "بول رہے ہیں…",
"unavailable": "اس ڈیوائس پر آواز ان پٹ دستیاب نہیں۔",
"audioUnavailable": "اس زبان کے لیے بولی آؤٹ پٹ دستیاب نہیں۔",
"recording": "ریکارڈ ہو رہا ہے…",
},
"errors": {
"network": "نیٹ ورک خرابی۔ اپنا کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
"unauthorized": "سیشن ختم۔ براہ کرم دوبارہ سائن ان کریں۔",
"notFound": "نہیں ملا۔",
},
"crops": {
"rice": "چاول",
"paddy": "دھان",
"wheat": "گندم",
"cotton": "کپاس",
"maize": "مکئی",
"sugarcane": "گنا",
"tomato": "ٹماٹر",
"potato": "آلو",
"onion": "پیاز",
"soybean": "سویابین",
"groundnut": "مونگ پھلی",
"chilli": "مرچ",
},
}

emit("ur", T)
