import type { GovernmentScheme } from "@/types";

export const MOCK_SCHEMES: GovernmentScheme[] = [
  {
    id: "1",
    scheme_name: "Pradhan Mantri Fasal Bima Yojana",
    scheme_code: "PMFBY",
    description: "Comprehensive crop insurance scheme providing financial support to farmers in case of crop failure due to natural calamities, pests, and diseases. Covers all food crops, oilseeds, and annual horticultural crops.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "All farmers including sharecroppers and tenant farmers growing notified crops in notified areas. No upper limit on land holding. Loanee farmers are covered compulsorily, non-loanee voluntarily.",
    benefits: "Insurance coverage up to 80% of sum insured. Premium rates: Kharif - 2% of sum insured for all food crops and oilseeds, Rabi - 1.5%, Annual commercial/horticultural crops - 5%. Balance premium subsidized equally by Centre and State.",
    application_process: "1. Visit nearest bank branch or common service center\n2. Fill the proposal form with crop details and land documents\n3. Submit before the cutoff date notified by the state\n4. Pay the premium share\n5. Receive acknowledgement with enrollment number",
    documents_required: "Aadhaar Card, Land Records, Bank Account Details, Crop Photos (for claims), Previous year insurance certificate (if any)",
    funding_pattern: "Centre:State = 50:50 for premium subsidy. 100% Central funding for premium in North-Eastern and Himalayan states.",
    beneficiary_type: "Individual farmers",
    category: "Insurance",
    tags: ["crop insurance", "risk management", "natural calamities", "subsidy"],
    is_active: true,
    website_url: "https://pmfby.gov.in",
  },
  {
    id: "2",
    scheme_name: "Pradhan Mantri Kisan Samman Nidhi",
    scheme_code: "PM-KISAN",
    description: "Income support scheme providing direct cash transfer of ₹6,000 per year to all landholding farmer families. Amount is transferred in three equal installments of ₹2,000 every four months.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "All landholding farmer families with cultivable land. Excluded: income tax payers, constitutional office holders, retired pensioners with monthly pension over ₹10,000, professionals like doctors/engineers/lawyers.",
    benefits: "₹6,000 per year per family in three equal installments of ₹2,000 each. Directly credited to Aadhaar-linked bank accounts.",
    application_process: "1. Visit PM-KISAN portal (pmkisan.gov.in)\n2. Click on 'New Farmer Registration'\n3. Enter Aadhaar number and verify via OTP\n4. Fill land details and bank account information\n5. Submit and note the application reference number\n6. Visit nearest CSC for biometric verification if required",
    documents_required: "Aadhaar Card, Land Records (Khasra/Khatauni), Bank Account Details, Passport size photograph",
    funding_pattern: "100% Central funding",
    beneficiary_type: "Individual landholding farmers",
    category: "Income Support",
    tags: ["income support", "cash transfer", "direct benefit", "PM-KISAN"],
    is_active: true,
    website_url: "https://pmkisan.gov.in",
  },
  {
    id: "3",
    scheme_name: "Soil Health Card Scheme",
    scheme_code: "SHC",
    description: "Scheme to issue soil health cards to farmers providing crop-wise recommendations on fertilizers and nutrients required for farms. Cards are issued every 3 years for comprehensive soil health monitoring.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "All farmers in India are eligible. Soil sample collection is done at the rate of one sample per 10 hectares in irrigated areas and one per 25 hectares in rainfed areas.",
    benefits: "Free soil testing. Soil Health Card with recommendations on: NPK dosage, micronutrients, organic matter management. Improvement in soil fertility and crop yield. Reduction in fertilizer cost through balanced usage.",
    application_process: "1. Contact local agriculture department or Krishi Vigyan Kendra\n2. Register for soil sample collection\n3. Agriculture officer visits and collects soil sample\n4. Sample sent to lab for testing\n5. Soil Health Card generated and sent to farmer within 30 days\n6. Follow recommendations for fertilizer application",
    documents_required: "Land records, Farmer ID, Contact information",
    funding_pattern: "100% Central funding",
    beneficiary_type: "All farmers",
    category: "Soil Health",
    tags: ["soil testing", "fertilizer management", "soil health", "nutrient management"],
    is_active: true,
    website_url: "https://soilhealth.dac.gov.in",
  },
  {
    id: "4",
    scheme_name: "Pradhan Mantri Krishi Sinchayee Yojana",
    scheme_code: "PMKSY",
    description: "Holistic scheme for irrigation infrastructure development with the motto 'More Crop Per Drop'. Aims to enhance water use efficiency through precision irrigation and water conservation.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "All farmers with cultivable land. Priority to small and marginal farmers. Farmer Producer Organizations (FPOs) and Self Help Groups (SHGs) also eligible.",
    benefits: "Subsidy up to 55% for small and marginal farmers, 45% for general farmers on micro-irrigation systems. Coverage of up to 5 hectares. Water harvesting structures funding up to ₹50,000 per structure.",
    application_process: "1. Contact District Agriculture Department\n2. Submit application with land documents\n3. Technical inspection by agriculture officer\n4. Sanction letter issued\n5. Install irrigation system through empaneled vendors\n6. Claim subsidy after installation verification",
    documents_required: "Aadhaar Card, Land Records, Bank Account Details, Quotation from empaneled vendor",
    funding_pattern: "Centre:State = 60:40 (general states), 90:10 (NE/Himalayan states), 100% (UTs)",
    beneficiary_type: "Individual farmers, FPOs, SHGs",
    category: "Investment",
    tags: ["irrigation", "water conservation", "micro-irrigation", "subsidy"],
    is_active: true,
    website_url: "https://pmksy.gov.in",
  },
  {
    id: "5",
    scheme_name: "Kisan Credit Card Scheme",
    scheme_code: "KCC",
    description: "Provides farmers with timely access to affordable credit for agricultural operations including crop production, maintenance, marketing, and post-harvest expenses. Also covers animal husbandry and fisheries.",
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    state_jurisdiction: "All India",
    eligibility_criteria: "All farmers - individuals, joint borrowers, tenants, sharecroppers. Farmer Producer Organizations. Also available for animal husbandry and fisheries farmers. No upper age limit.",
    benefits: "Credit limit up to ₹3 lakh at 7% interest rate. Prompt repayment incentive of 3% (effective rate 4%). Crop loan up to ₹1.6 lakh and term loan component. Credit limit valid for 5 years with revolving facility. No processing fee for loans up to ₹3 lakh.",
    application_process: "1. Visit nearest bank branch (any commercial/cooperative/regional rural bank)\n2. Fill KCC application form\n3. Submit land records and identity proof\n4. Bank officer verifies land and farming details\n5. Credit limit sanctioned within 2-4 weeks\n6. Receive KCC and passbook\n7. Withdraw cash as needed within limit",
    documents_required: "Aadhaar Card, Land Records, 2 passport photos, Bank account statement, Proof of farming activity",
    funding_pattern: "Interest subvention by Central Government. Banks provide credit at subsidized rates.",
    beneficiary_type: "Individual farmers, FPOs",
    category: "Investment",
    tags: ["credit", "loan", "interest subsidy", "working capital"],
    is_active: true,
    website_url: "https://pmkisan.gov.in/kcc",
  },
  {
    id: "6",
    scheme_name: "Rashtriya Krishi Vikas Yojana",
    scheme_code: "RKVY",
    description: "State-led agricultural development scheme focusing on pre-harvest, harvest, and post-harvest infrastructure. Supports value chain development, farm mechanization, and climate-resilient agriculture.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "State governments submit project proposals. Individual farmers can access benefits through state-level implementing agencies. Farmer groups, FPOs, and startups in agriculture also eligible.",
    benefits: "Support for farm mechanization (up to 50% subsidy). Post-harvest infrastructure development. Food processing units subsidy. Integrated farming system support. Market infrastructure development.",
    application_process: "1. State governments formulate District Agriculture Plans (DAP)\n2. Projects submitted through State Level Sanctioning Committee\n3. Approved projects implemented through district agencies\n4. Farmers apply to district agriculture department for specific benefits\n5. Subsidy disbursed after verification",
    documents_required: "Varies by state and specific component. Typically: land records, project report, identity proof",
    funding_pattern: "100% Central funding to states",
    beneficiary_type: "States, farmers groups, individual farmers",
    category: "Investment",
    tags: ["infrastructure", "mechanization", "value chain", "state plan"],
    is_active: true,
    website_url: "https://rkvy.nic.in",
  },
  {
    id: "7",
    scheme_name: "National Mission for Sustainable Agriculture",
    scheme_code: "NMSA",
    description: "Mission to promote sustainable agriculture practices focusing on climate change adaptation, water use efficiency, soil health management, and integrated farming systems.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "All farmers practicing or willing to adopt sustainable agriculture practices. Priority to rainfed areas. Farmer groups and FPOs in climate-vulnerable regions.",
    benefits: "Training on climate-resilient practices. Support for organic farming certification. Rainfed area development funding. Integrated farming system model demonstration. Soil conservation measures funding.",
    application_process: "1. Contact state agriculture department or KVK\n2. Register for training programs\n3. Apply for specific component assistance\n4. Technical approval by district committee\n5. Implementation and verification",
    documents_required: "Land records, farmer identification, project proposal (for groups)",
    funding_pattern: "Centre:State = 60:40 (general), 90:10 (NE/Himalayan)",
    beneficiary_type: "Individual farmers, farmer groups, FPOs",
    category: "Soil Health",
    tags: ["sustainable agriculture", "climate change", "organic farming", "rainfed"],
    is_active: true,
    website_url: "https://nmsa.dac.gov.in",
  },
  {
    id: "8",
    scheme_name: "Pradhan Mantri Kisan Maan Dhan Yojana",
    scheme_code: "PM-KMY",
    description: "Social security scheme providing monthly pension of ₹3,000 to all small and marginal farmers after attaining 60 years. Smallest ever contribution scheme with Government matching contribution.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "Small and marginal farmers aged 18-40 years with up to 2 hectares of cultivable land. Excluded: income tax payers, farmers covered under PM-SYM or NPS.",
    benefits: "Monthly pension of ₹3,000 after 60 years. Lifetime pension to spouse after farmer's death. Government contributes equal amount to farmer's contribution. Contribution range: ₹55-₹200 per month based on entry age.",
    application_process: "1. Visit nearest Common Service Center (CSC)\n2. Provide Aadhaar and bank account details\n3. Fill enrollment form with land details\n4. Pay first contribution\n5. Receive enrollment number\n6. Subsequent contributions auto-debited from bank account",
    documents_required: "Aadhaar Card, Land Records, Bank Account Details, Passport photo, Mobile number",
    funding_pattern: "50% farmer contribution, 50% Government matching contribution",
    beneficiary_type: "Small and marginal farmers (up to 2 hectares)",
    category: "Income Support",
    tags: ["pension", "social security", "old age", "small farmers"],
    is_active: true,
    website_url: "https://pmkmy.gov.in",
  },
  {
    id: "9",
    scheme_name: "E-NAM (National Agriculture Market)",
    scheme_code: "e-NAM",
    description: "Pan-India electronic trading portal connecting existing APMC mandis to create a unified national market for agricultural commodities. Provides online bidding, transparent price discovery, and single window payment.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "Participating states (24 states, 5 UTs)",
    eligibility_criteria: "All farmers registered with mandis connected to e-NAM platform. Traders and commission agents with valid licenses. Farmer Producer Organizations registered on portal.",
    benefits: "Access to larger market beyond local mandi. Transparent price discovery through online bidding. Better price realization. Single point payment through integrated system. Quality assaying at nearest mandi.",
    application_process: "1. Register at mandi level or online at enam.gov.in\n2. Provide Aadhaar and bank details for payment\n3. Receive farmer ID and digital signature\n4. Bring produce to nearest e-NAM mandi\n5. Produce quality assaying done\n6. Online bidding across mandis\n7. Accept best price and receive payment directly to bank",
    documents_required: "Aadhaar Card, Land Records, Bank Account Details, Passbook, Mobile number",
    funding_pattern: "100% Central funding for software and infrastructure at mandis",
    beneficiary_type: "Farmers, Traders, Commission Agents, FPOs",
    category: "Market",
    tags: ["e-trading", "market access", "price discovery", "digital platform"],
    is_active: true,
    website_url: "https://enam.gov.in",
  },
  {
    id: "10",
    scheme_name: "Paramparagat Krishi Vikas Yojana",
    scheme_code: "PKVY",
    description: "Scheme to promote organic farming through cluster approach. Provides end-to-end support for organic farming including certification, training, and market linkage for organic produce.",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    department: "Department of Agriculture, Cooperation and Farmers Welfare",
    state_jurisdiction: "All India",
    eligibility_criteria: "All farmers willing to adopt organic farming. Preference to small and marginal farmers. Farmer clusters of 50 hectares or more. Farmers in certified organic areas.",
    benefits: "₹50,000 per hectare for 3 years (₹31,000 for inputs, ₹19,000 for certification and value addition). Free organic certification under PGS-India. Training and capacity building. Market linkage support.",
    application_process: "1. Form farmer cluster of 50+ hectares\n2. Register with state agriculture department or nodal agency\n3. Submit cluster action plan\n4. Receive training on organic practices\n5. Implement organic farming under supervision\n6. Apply for PGS certification\n7. Receive subsidy and market linkage support",
    documents_required: "Land records, Farmer ID, Cluster formation document, Organic farming plan",
    funding_pattern: "100% Central funding to states (implemented through state agencies)",
    beneficiary_type: "Individual farmers and farmer groups/clusters",
    category: "Soil Health",
    tags: ["organic farming", "certification", "cluster", "natural farming"],
    is_active: true,
    website_url: "https://pgsindia-ncof.gov.in",
  },
];

export const SCHEME_CATEGORIES = [
  "All",
  "Insurance",
  "Income Support",
  "Investment",
  "Soil Health",
  "Market",
] as const;
